# Парсинг данных новостных сообществ социальной сети ВКонтакте

## Парсинг публикаций

### Написание функции по извлечению данных публикаций с помощью VK API

In [83]:
pip install vk_api

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: vk_api in /Users/ekaterinamalkova/Library/Python/3.9/lib/python/site-packages (11.10.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /Users/ekaterinamalkova/Library/Python/3.9/lib/python/site-packages (from vk_api) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/ekaterinamalkova/Library/Python/3.9/lib/python/site-packages (from requests<3.0.0,>=2.20.0->vk_api) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/ekaterinamalkova/Library/Python/3.9/lib/python/site-packages (from requests<3.0.0,>=2.20.0->vk_api) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/ekaterinamalkova/Library/Python/3.9/lib/python/site-packages (from requests<3.0.0,>=2.20.0->vk_api) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ekaterinamalkova/Library/Python/3.9/lib/python/site-packages (from requests<3.0.0,>=2.20.0->vk_api) (2026.4.22)
Note: you may need to restart the kernel to use updated packages.

In [1]:
# api_token = #'Вставьте свой ключ доступа'

# используемый личный ключ скрыт из ячейки в целях безопасности аккаунта в соцсети

In [ ]:
# импорт библиотек
import vk_api
from datetime import datetime
import time
import pandas as pd

# инициализация функции для извлечения публикаций
def get_posts(api_token, group_id, count=100, start_offset=5000):
  '''
  Получает тексты постов и пользовательские реакции из сообществ с сайта https://vk.com.
  Собирает посты, пока не дойдет до даты 01.01.2020, либо пока не закончатся посты.

  Параметры:
    api_token: ключ доступа для выполнения запросов к VK API
    group_id: уникальный идентификатор сообщества, начинающийся с '-'
    count: число выгружаемых постов за 1 итерацию
    start_offset: начальная позиция со смещением (сколько последних постов пропускаем перед сбором данных)
  Вывод функции:
    Возвращает all_posts – список из словарей; в каждом словаре содержится информация
                           о конкретной публикации.
  '''
  # инициализация VK API
  vk_session = vk_api.VkApi(token=api_token)
  vk = vk_session.get_api()

  # инициализация словаря, смещения, целевой даты и флага ее достижения
  all_posts = []
  offset = start_offset
  target_date = datetime(2020, 1, 1).timestamp()
  target_flag = False

  print(f'Начинаем сбор с offset = {offset}')
  print(f'Цель: дойти до 01.01.2020')
  print('-' * 50)

  # пока не достигнута целевая дата, цикл в работе
  while not target_flag:
    # отправка запроса к новостной 'стене' сообщества
    response = vk.wall.get(owner_id=group_id,
                           filter='owner',
                           count=count,
                           offset=offset)
    # пустой ответ на запрос сигнализирует об отсутствии постов
    if not response.get('items'):
      print('Постов больше нет')
      break
    # извлечение даты поста из ответа на запрос
    for post in response['items']:
      post_date = post['date']
      post_date_string = datetime.fromtimestamp(post_date).strftime('%Y-%m-%d')
      post_year = datetime.fromtimestamp(post_date).year
      # проверка на достижении целевой даты 01.01.2020
      if post_date <= target_date:
        target_flag = True
        if post_year == 2020 or post_year < 2020:
          print(f'\n- Достигли {post_year} года -')
          print(f'Последний пост: {post['id']} от {post_date_string}')
          break
      # извлечение данных из ответа на запрос в виде словаря и присоединение их к списку со всеми постами
      else:
        all_posts.append({'post_id': post['id'],
                          'date': post_date_string,
                          'text': post['text'],
                          'likes': post.get('likes', {}).get('count', 0),
                          'comments_count': post.get('comments', {}).get('count', 0),
                          'reposts': post.get('reposts', {}).get('count', 0),
                          'views': post.get('views', {}).get('count', 0) if 'views' in post else 0})
    # завершение цикла в случае достижения целевой даты 01.01.2020
    if target_flag:
      break

    print(f'Обработано offset {offset}, собрано {len(all_posts)} постов (последний: {post_date_string})')
    # если цикл продолжается, значение смещения обновляется на число собранных постов (100)
    offset += 100
    # задержка алгоритма для избежания превышения установленных лимитов запросов (rps)
    time.sleep(0.1)

  return all_posts

### Применение функции для выгрузки данных из сообществ

Сообщества университетов Москвы, имеющие суммарный индекс > 1. Сайт: https://brandanalytics.ru/university-rankings/integral/#scroll_anchor

In [ ]:
# ВШЭ
group_id = '-25205856'
name = 'hse.csv'

posts = get_posts(api_token, group_id, start_offset=300)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 300
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 300, собрано 100 постов (последний: 2026-01-13)
Обработано offset 400, собрано 200 постов (последний: 2025-12-08)
Обработано offset 500, собрано 300 постов (последний: 2025-11-13)
Обработано offset 600, собрано 400 постов (последний: 2025-10-18)
Обработано offset 700, собрано 500 постов (последний: 2025-09-26)
Обработано offset 800, собрано 600 постов (последний: 2025-09-01)
Обработано offset 900, собрано 700 постов (последний: 2025-07-24)
Обработано offset 1000, собрано 800 постов (последний: 2025-06-27)
Обработано offset 1100, собрано 900 постов (последний: 2025-05-30)
Обработано offset 1200, собрано 1000 постов (последний: 2025-05-07)
Обработано offset 1300, собрано 1100 постов (последний: 2025-04-15)
Обработано offset 1400, собрано 1200 постов (последний: 2025-03-18)
Обработано offset 1500, собрано 1300 постов (последний: 2025-02-20)
Обработано offset 1600, собрано 1400 постов (последний: 2025-01-20)
Обработано offset 1700, собрано 1500 постов (последний: 2024-12-12)
Обработано offset 1800, собрано 1600 постов (последний: 2024-11-15)
Обработано offset 1900, собрано 1700 постов (последний: 2024-10-15)
Обработано offset 2000, собрано 1800 постов (последний: 2024-09-11)
Обработано offset 2100, собрано 1900 постов (последний: 2024-07-29)
Обработано offset 2200, собрано 2000 постов (последний: 2024-06-12)
Обработано offset 2300, собрано 2100 постов (последний: 2024-05-07)
Обработано offset 2400, собрано 2200 постов (последний: 2024-03-29)
Обработано offset 2500, собрано 2300 постов (последний: 2024-02-22)
Обработано offset 2600, собрано 2400 постов (последний: 2024-01-15)
Обработано offset 2700, собрано 2500 постов (последний: 2023-12-06)
Обработано offset 2800, собрано 2600 постов (последний: 2023-11-07)
Обработано offset 2900, собрано 2700 постов (последний: 2023-10-04)
Обработано offset 3000, собрано 2800 постов (последний: 2023-09-07)
Обработано offset 3100, собрано 2900 постов (последний: 2023-08-04)
Обработано offset 3200, собрано 3000 постов (последний: 2023-07-03)
Обработано offset 3300, собрано 3100 постов (последний: 2023-06-06)
Обработано offset 3400, собрано 3200 постов (последний: 2023-05-13)
Обработано offset 3500, собрано 3300 постов (последний: 2023-04-12)
Обработано offset 3600, собрано 3400 постов (последний: 2023-03-20)
Обработано offset 3700, собрано 3500 постов (последний: 2023-02-14)
Обработано offset 3800, собрано 3600 постов (последний: 2023-01-13)
Обработано offset 3900, собрано 3700 постов (последний: 2022-12-09)
Обработано offset 4000, собрано 3800 постов (последний: 2022-11-16)
Обработано offset 4100, собрано 3900 постов (последний: 2022-10-14)
Обработано offset 4200, собрано 4000 постов (последний: 2022-09-06)
Обработано offset 4300, собрано 4100 постов (последний: 2022-08-02)
Обработано offset 4400, собрано 4200 постов (последний: 2022-07-06)
Обработано offset 4500, собрано 4300 постов (последний: 2022-06-09)
Обработано offset 4600, собрано 4400 постов (последний: 2022-05-18)
Обработано offset 4700, собрано 4500 постов (последний: 2022-04-19)
Обработано offset 4800, собрано 4600 постов (последний: 2022-03-22)
Обработано offset 4900, собрано 4700 постов (последний: 2022-02-11)
Обработано offset 5000, собрано 4800 постов (последний: 2022-01-19)
Обработано offset 5100, собрано 4900 постов (последний: 2021-12-17)
Обработано offset 5200, собрано 5000 постов (последний: 2021-11-29)
Обработано offset 5300, собрано 5100 постов (последний: 2021-11-03)
Обработано offset 5400, собрано 5200 постов (последний: 2021-10-08)
Обработано offset 5500, собрано 5300 постов (последний: 2021-09-14)
Обработано offset 5600, собрано 5400 постов (последний: 2021-08-20)
Обработано offset 5700, собрано 5500 постов (последний: 2021-07-23)
Обработано offset 5800, собрано 5600 постов (последний: 2021-06-29)
Обработано offset 5900, собрано 5700 постов (последний: 2021-06-07)
Обработано offset 6000, собрано 5800 постов (последний: 2021-05-14)
Обработано offset 6100, собрано 5900 постов (последний: 2021-04-21)
Обработано offset 6200, собрано 6000 постов (последний: 2021-04-02)
Обработано offset 6300, собрано 6100 постов (последний: 2021-03-09)
Обработано offset 6400, собрано 6200 постов (последний: 2021-02-10)
Обработано offset 6500, собрано 6300 постов (последний: 2021-01-15)
Обработано offset 6600, собрано 6400 постов (последний: 2020-12-17)
Обработано offset 6700, собрано 6500 постов (последний: 2020-11-24)
Обработано offset 6800, собрано 6600 постов (последний: 2020-11-02)
Обработано offset 6900, собрано 6700 постов (последний: 2020-10-06)
Обработано offset 7000, собрано 6800 постов (последний: 2020-09-08)
Обработано offset 7100, собрано 6900 постов (последний: 2020-08-06)
Обработано offset 7200, собрано 7000 постов (последний: 2020-07-09)
Обработано offset 7300, собрано 7100 постов (последний: 2020-06-12)
Обработано offset 7400, собрано 7200 постов (последний: 2020-05-12)
Обработано offset 7500, собрано 7300 постов (последний: 2020-04-09)
Обработано offset 7600, собрано 7400 постов (последний: 2020-03-05)
Обработано offset 7700, собрано 7500 постов (последний: 2020-01-30)

- Достигли 2019 года -
Последний пост: 52681 от 2019-12-31
Всего собрано постов: 7560
Диапазон дат: 2020-01-01 - 2026-02-17

In [ ]:
# МАИ
group_id = '-50409684'
name = 'mai.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-22)
Обработано offset 100, собрано 200 постов (последний: 2026-03-20)
Обработано offset 200, собрано 300 постов (последний: 2026-01-27)
Обработано offset 300, собрано 400 постов (последний: 2025-12-19)
Обработано offset 400, собрано 500 постов (последний: 2025-11-17)
Обработано offset 500, собрано 600 постов (последний: 2025-10-14)
Обработано offset 600, собрано 700 постов (последний: 2025-09-10)
Обработано offset 700, собрано 800 постов (последний: 2025-08-11)
Обработано offset 800, собрано 900 постов (последний: 2025-07-09)
Обработано offset 900, собрано 1000 постов (последний: 2025-06-06)
Обработано offset 1000, собрано 1100 постов (последний: 2025-05-09)
Обработано offset 1100, собрано 1200 постов (последний: 2025-04-10)
Обработано offset 1200, собрано 1300 постов (последний: 2025-03-07)
Обработано offset 1300, собрано 1400 постов (последний: 2025-01-29)
Обработано offset 1400, собрано 1500 постов (последний: 2024-12-26)
Обработано offset 1500, собрано 1600 постов (последний: 2024-11-23)
Обработано offset 1600, собрано 1700 постов (последний: 2024-10-23)
Обработано offset 1700, собрано 1800 постов (последний: 2024-09-24)
Обработано offset 1800, собрано 1900 постов (последний: 2024-08-29)
Обработано offset 1900, собрано 2000 постов (последний: 2024-07-30)
Обработано offset 2000, собрано 2100 постов (последний: 2024-07-01)
Обработано offset 2100, собрано 2200 постов (последний: 2024-05-31)
Обработано offset 2200, собрано 2300 постов (последний: 2024-05-01)
Обработано offset 2300, собрано 2400 постов (последний: 2024-04-02)
Обработано offset 2400, собрано 2500 постов (последний: 2024-03-02)
Обработано offset 2500, собрано 2600 постов (последний: 2024-02-05)
Обработано offset 2600, собрано 2700 постов (последний: 2024-01-07)
Обработано offset 2700, собрано 2800 постов (последний: 2023-12-14)
Обработано offset 2800, собрано 2900 постов (последний: 2023-11-20)
Обработано offset 2900, собрано 3000 постов (последний: 2023-10-25)
Обработано offset 3000, собрано 3100 постов (последний: 2023-09-27)
Обработано offset 3100, собрано 3200 постов (последний: 2023-09-05)
Обработано offset 3200, собрано 3300 постов (последний: 2023-08-22)
Обработано offset 3300, собрано 3400 постов (последний: 2023-07-31)
Обработано offset 3400, собрано 3500 постов (последний: 2023-07-07)
Обработано offset 3500, собрано 3600 постов (последний: 2023-06-13)
Обработано offset 3600, собрано 3700 постов (последний: 2023-05-19)
Обработано offset 3700, собрано 3800 постов (последний: 2023-04-27)
Обработано offset 3800, собрано 3900 постов (последний: 2023-04-06)
Обработано offset 3900, собрано 4000 постов (последний: 2023-03-14)
Обработано offset 4000, собрано 4100 постов (последний: 2023-02-16)
Обработано offset 4100, собрано 4200 постов (последний: 2023-01-25)
Обработано offset 4200, собрано 4300 постов (последний: 2022-12-28)
Обработано offset 4300, собрано 4400 постов (последний: 2022-12-06)
Обработано offset 4400, собрано 4500 постов (последний: 2022-11-15)
Обработано offset 4500, собрано 4600 постов (последний: 2022-10-25)
Обработано offset 4600, собрано 4700 постов (последний: 2022-10-01)
Обработано offset 4700, собрано 4800 постов (последний: 2022-09-01)
Обработано offset 4800, собрано 4900 постов (последний: 2022-07-29)
Обработано offset 4900, собрано 5000 постов (последний: 2022-06-22)
Обработано offset 5000, собрано 5100 постов (последний: 2022-05-24)
Обработано offset 5100, собрано 5200 постов (последний: 2022-04-22)
Обработано offset 5200, собрано 5300 постов (последний: 2022-03-18)
Обработано offset 5300, собрано 5400 постов (последний: 2022-02-08)
Обработано offset 5400, собрано 5500 постов (последний: 2021-12-30)
Обработано offset 5500, собрано 5600 постов (последний: 2021-12-08)
Обработано offset 5600, собрано 5700 постов (последний: 2021-11-12)
Обработано offset 5700, собрано 5800 постов (последний: 2021-10-14)
Обработано offset 5800, собрано 5900 постов (последний: 2021-09-22)
Обработано offset 5900, собрано 6000 постов (последний: 2021-08-26)
Обработано offset 6000, собрано 6100 постов (последний: 2021-07-20)
Обработано offset 6100, собрано 6200 постов (последний: 2021-06-05)
Обработано offset 6200, собрано 6300 постов (последний: 2021-04-30)
Обработано offset 6300, собрано 6400 постов (последний: 2021-04-07)
Обработано offset 6400, собрано 6500 постов (последний: 2021-02-26)
Обработано offset 6500, собрано 6600 постов (последний: 2021-01-28)
Обработано offset 6600, собрано 6700 постов (последний: 2020-12-11)
Обработано offset 6700, собрано 6800 постов (последний: 2020-11-16)
Обработано offset 6800, собрано 6900 постов (последний: 2020-10-07)
Обработано offset 6900, собрано 7000 постов (последний: 2020-09-04)
Обработано offset 7000, собрано 7100 постов (последний: 2020-07-28)
Обработано offset 7100, собрано 7200 постов (последний: 2020-06-25)
Обработано offset 7200, собрано 7300 постов (последний: 2020-05-22)
Обработано offset 7300, собрано 7400 постов (последний: 2020-04-23)
Обработано offset 7400, собрано 7500 постов (последний: 2020-04-07)
Обработано offset 7500, собрано 7600 постов (последний: 2020-03-17)
Обработано offset 7600, собрано 7700 постов (последний: 2020-02-15)
Обработано offset 7700, собрано 7800 постов (последний: 2020-01-21)

- Достигли 2019 года -
Последний пост: 18456 от 2019-12-31
Всего собрано постов: 7844
Диапазон дат: 2020-01-01 - 2026-05-05

In [ ]:
# МГУ
group_id = '-78019879'
name = 'mgu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-10)
Обработано offset 100, собрано 200 постов (последний: 2026-03-20)
Обработано offset 200, собрано 300 постов (последний: 2026-02-27)
Обработано offset 300, собрано 400 постов (последний: 2026-02-07)
Обработано offset 400, собрано 500 постов (последний: 2026-01-19)
Обработано offset 500, собрано 600 постов (последний: 2025-12-19)
Обработано offset 600, собрано 700 постов (последний: 2025-11-28)
Обработано offset 700, собрано 800 постов (последний: 2025-11-12)
Обработано offset 800, собрано 900 постов (последний: 2025-10-16)
Обработано offset 900, собрано 1000 постов (последний: 2025-09-22)
Обработано offset 1000, собрано 1100 постов (последний: 2025-08-29)
Обработано offset 1100, собрано 1200 постов (последний: 2025-08-05)
Обработано offset 1200, собрано 1300 постов (последний: 2025-07-16)
Обработано offset 1300, собрано 1400 постов (последний: 2025-06-19)
Обработано offset 1400, собрано 1500 постов (последний: 2025-05-24)
Обработано offset 1500, собрано 1600 постов (последний: 2025-04-29)
Обработано offset 1600, собрано 1700 постов (последний: 2025-04-09)
Обработано offset 1700, собрано 1800 постов (последний: 2025-03-17)
Обработано offset 1800, собрано 1900 постов (последний: 2025-02-21)
Обработано offset 1900, собрано 2000 постов (последний: 2025-01-31)
Обработано offset 2000, собрано 2100 постов (последний: 2025-01-13)
Обработано offset 2100, собрано 2200 постов (последний: 2024-12-18)
Обработано offset 2200, собрано 2300 постов (последний: 2024-11-28)
Обработано offset 2300, собрано 2400 постов (последний: 2024-11-11)
Обработано offset 2400, собрано 2500 постов (последний: 2024-10-17)
Обработано offset 2500, собрано 2600 постов (последний: 2024-09-30)
Обработано offset 2600, собрано 2700 постов (последний: 2024-09-06)
Обработано offset 2700, собрано 2800 постов (последний: 2024-08-19)
Обработано offset 2800, собрано 2900 постов (последний: 2024-07-25)
Обработано offset 2900, собрано 3000 постов (последний: 2024-07-04)
Обработано offset 3000, собрано 3100 постов (последний: 2024-06-11)
Обработано offset 3100, собрано 3200 постов (последний: 2024-05-17)
Обработано offset 3200, собрано 3300 постов (последний: 2024-04-12)
Обработано offset 3300, собрано 3400 постов (последний: 2024-03-11)
Обработано offset 3400, собрано 3500 постов (последний: 2024-02-12)
Обработано offset 3500, собрано 3600 постов (последний: 2024-01-16)
Обработано offset 3600, собрано 3700 постов (последний: 2023-12-08)
Обработано offset 3700, собрано 3800 постов (последний: 2023-11-15)
Обработано offset 3800, собрано 3900 постов (последний: 2023-10-13)
Обработано offset 3900, собрано 4000 постов (последний: 2023-09-20)
Обработано offset 4000, собрано 4100 постов (последний: 2023-08-18)
Обработано offset 4100, собрано 4200 постов (последний: 2023-07-13)
Обработано offset 4200, собрано 4300 постов (последний: 2023-06-11)
Обработано offset 4300, собрано 4400 постов (последний: 2023-05-15)
Обработано offset 4400, собрано 4500 постов (последний: 2023-04-14)
Обработано offset 4500, собрано 4600 постов (последний: 2023-03-22)
Обработано offset 4600, собрано 4700 постов (последний: 2023-02-16)
Обработано offset 4700, собрано 4800 постов (последний: 2023-01-13)
Обработано offset 4800, собрано 4900 постов (последний: 2022-12-09)
Обработано offset 4900, собрано 5000 постов (последний: 2022-11-17)
Обработано offset 5000, собрано 5100 постов (последний: 2022-10-20)
Обработано offset 5100, собрано 5200 постов (последний: 2022-09-19)
Обработано offset 5200, собрано 5300 постов (последний: 2022-08-16)
Обработано offset 5300, собрано 5400 постов (последний: 2022-07-12)
Обработано offset 5400, собрано 5500 постов (последний: 2022-06-12)
Обработано offset 5500, собрано 5600 постов (последний: 2022-05-16)
Обработано offset 5600, собрано 5700 постов (последний: 2022-04-18)
Обработано offset 5700, собрано 5800 постов (последний: 2022-03-21)
Обработано offset 5800, собрано 5900 постов (последний: 2022-01-29)
Обработано offset 5900, собрано 6000 постов (последний: 2021-12-02)
Обработано offset 6000, собрано 6100 постов (последний: 2021-10-19)
Обработано offset 6100, собрано 6200 постов (последний: 2021-08-31)
Обработано offset 6200, собрано 6300 постов (последний: 2021-07-23)
Обработано offset 6300, собрано 6400 постов (последний: 2021-06-07)
Обработано offset 6400, собрано 6500 постов (последний: 2021-04-26)
Обработано offset 6500, собрано 6600 постов (последний: 2021-03-16)
Обработано offset 6600, собрано 6700 постов (последний: 2021-02-03)
Обработано offset 6700, собрано 6800 постов (последний: 2020-12-17)
Обработано offset 6800, собрано 6900 постов (последний: 2020-11-12)
Обработано offset 6900, собрано 7000 постов (последний: 2020-10-01)
Обработано offset 7000, собрано 7100 постов (последний: 2020-08-06)
Обработано offset 7100, собрано 7200 постов (последний: 2020-06-28)
Обработано offset 7200, собрано 7300 постов (последний: 2020-05-29)
Обработано offset 7300, собрано 7400 постов (последний: 2020-05-04)
Обработано offset 7400, собрано 7500 постов (последний: 2020-04-09)
Обработано offset 7500, собрано 7600 постов (последний: 2020-02-26)
Обработано offset 7600, собрано 7700 постов (последний: 2020-01-16)

- Достигли 2019 года -
Последний пост: 14835 от 2019-12-31
Всего собрано постов: 7728
Диапазон дат: 2020-01-01 - 2026-05-06

In [ ]:
# РЭУ ПЛЕХАНОВА
group_id = '-1177'
name = 'reu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-29)
Обработано offset 100, собрано 200 постов (последний: 2026-02-18)
Обработано offset 200, собрано 300 постов (последний: 2025-12-15)
Обработано offset 300, собрано 400 постов (последний: 2025-09-14)
Обработано offset 400, собрано 500 постов (последний: 2025-07-17)
Обработано offset 500, собрано 600 постов (последний: 2025-05-21)
Обработано offset 600, собрано 700 постов (последний: 2025-04-09)
Обработано offset 700, собрано 800 постов (последний: 2025-03-06)
Обработано offset 800, собрано 900 постов (последний: 2025-01-21)
Обработано offset 900, собрано 1000 постов (последний: 2024-12-12)
Обработано offset 1000, собрано 1100 постов (последний: 2024-11-04)
Обработано offset 1100, собрано 1200 постов (последний: 2024-09-24)
Обработано offset 1200, собрано 1300 постов (последний: 2024-08-19)
Обработано offset 1300, собрано 1400 постов (последний: 2024-07-10)
Обработано offset 1400, собрано 1500 постов (последний: 2024-06-04)
Обработано offset 1500, собрано 1600 постов (последний: 2024-05-02)
Обработано offset 1600, собрано 1700 постов (последний: 2024-04-02)
Обработано offset 1700, собрано 1800 постов (последний: 2024-03-07)
Обработано offset 1800, собрано 1900 постов (последний: 2024-02-06)
Обработано offset 1900, собрано 2000 постов (последний: 2024-01-03)
Обработано offset 2000, собрано 2100 постов (последний: 2023-11-30)
Обработано offset 2100, собрано 2200 постов (последний: 2023-11-02)
Обработано offset 2200, собрано 2300 постов (последний: 2023-10-06)
Обработано offset 2300, собрано 2400 постов (последний: 2023-09-19)
Обработано offset 2400, собрано 2500 постов (последний: 2023-08-29)
Обработано offset 2500, собрано 2600 постов (последний: 2023-08-08)
Обработано offset 2600, собрано 2700 постов (последний: 2023-07-25)
Обработано offset 2700, собрано 2800 постов (последний: 2023-07-07)
Обработано offset 2800, собрано 2900 постов (последний: 2023-06-23)
Обработано offset 2900, собрано 3000 постов (последний: 2023-06-05)
Обработано offset 3000, собрано 3100 постов (последний: 2023-05-20)
Обработано offset 3100, собрано 3200 постов (последний: 2023-05-03)
Обработано offset 3200, собрано 3300 постов (последний: 2023-04-18)
Обработано offset 3300, собрано 3400 постов (последний: 2023-04-02)
Обработано offset 3400, собрано 3500 постов (последний: 2023-03-20)
Обработано offset 3500, собрано 3600 постов (последний: 2023-03-01)
Обработано offset 3600, собрано 3700 постов (последний: 2023-02-12)
Обработано offset 3700, собрано 3800 постов (последний: 2023-01-16)
Обработано offset 3800, собрано 3900 постов (последний: 2022-12-15)
Обработано offset 3900, собрано 4000 постов (последний: 2022-11-25)
Обработано offset 4000, собрано 4100 постов (последний: 2022-11-07)
Обработано offset 4100, собрано 4200 постов (последний: 2022-10-17)
Обработано offset 4200, собрано 4300 постов (последний: 2022-09-28)
Обработано offset 4300, собрано 4400 постов (последний: 2022-09-08)
Обработано offset 4400, собрано 4500 постов (последний: 2022-08-21)
Обработано offset 4500, собрано 4600 постов (последний: 2022-07-29)
Обработано offset 4600, собрано 4700 постов (последний: 2022-07-11)
Обработано offset 4700, собрано 4800 постов (последний: 2022-06-19)
Обработано offset 4800, собрано 4900 постов (последний: 2022-05-28)
Обработано offset 4900, собрано 5000 постов (последний: 2022-05-11)
Обработано offset 5000, собрано 5100 постов (последний: 2022-04-16)
Обработано offset 5100, собрано 5200 постов (последний: 2022-03-24)
Обработано offset 5200, собрано 5300 постов (последний: 2022-02-18)
Обработано offset 5300, собрано 5400 постов (последний: 2022-01-13)
Обработано offset 5400, собрано 5500 постов (последний: 2021-12-03)
Обработано offset 5500, собрано 5600 постов (последний: 2021-11-04)
Обработано offset 5600, собрано 5700 постов (последний: 2021-09-03)
Обработано offset 5700, собрано 5800 постов (последний: 2021-07-05)
Обработано offset 5800, собрано 5900 постов (последний: 2021-05-26)
Обработано offset 5900, собрано 6000 постов (последний: 2021-04-20)
Обработано offset 6000, собрано 6100 постов (последний: 2021-03-17)
Обработано offset 6100, собрано 6200 постов (последний: 2021-01-22)
Обработано offset 6200, собрано 6300 постов (последний: 2020-11-19)
Обработано offset 6300, собрано 6400 постов (последний: 2020-10-05)
Обработано offset 6400, собрано 6500 постов (последний: 2020-07-31)
Обработано offset 6500, собрано 6600 постов (последний: 2020-05-09)
Обработано offset 6600, собрано 6700 постов (последний: 2020-03-02)

- Достигли 2019 года -
Последний пост: 68835 от 2019-12-31
Всего собрано постов: 6734
Диапазон дат: 2020-01-16 - 2026-05-04

In [ ]:
# МФТИ
group_id = '-932'
name = 'mfti.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-17)
Обработано offset 100, собрано 200 постов (последний: 2026-02-02)
Обработано offset 200, собрано 300 постов (последний: 2025-12-10)
Обработано offset 300, собрано 400 постов (последний: 2025-11-14)
Обработано offset 400, собрано 500 постов (последний: 2025-10-16)
Обработано offset 500, собрано 600 постов (последний: 2025-09-18)
Обработано offset 600, собрано 700 постов (последний: 2025-08-22)
Обработано offset 700, собрано 800 постов (последний: 2025-07-16)
Обработано offset 800, собрано 900 постов (последний: 2025-06-09)
Обработано offset 900, собрано 1000 постов (последний: 2025-05-16)
Обработано offset 1000, собрано 1100 постов (последний: 2025-04-17)
Обработано offset 1100, собрано 1200 постов (последний: 2025-03-25)
Обработано offset 1200, собрано 1300 постов (последний: 2025-03-03)
Обработано offset 1300, собрано 1400 постов (последний: 2025-02-03)
Обработано offset 1400, собрано 1500 постов (последний: 2024-12-25)
Обработано offset 1500, собрано 1600 постов (последний: 2024-11-30)
Обработано offset 1600, собрано 1700 постов (последний: 2024-11-07)
Обработано offset 1700, собрано 1800 постов (последний: 2024-10-15)
Обработано offset 1800, собрано 1900 постов (последний: 2024-09-21)
Обработано offset 1900, собрано 2000 постов (последний: 2024-09-03)
Обработано offset 2000, собрано 2100 постов (последний: 2024-08-07)
Обработано offset 2100, собрано 2200 постов (последний: 2024-07-08)
Обработано offset 2200, собрано 2300 постов (последний: 2024-06-14)
Обработано offset 2300, собрано 2400 постов (последний: 2024-05-23)
Обработано offset 2400, собрано 2500 постов (последний: 2024-05-04)
Обработано offset 2500, собрано 2600 постов (последний: 2024-04-15)
Обработано offset 2600, собрано 2700 постов (последний: 2024-03-27)
Обработано offset 2700, собрано 2800 постов (последний: 2024-02-29)
Обработано offset 2800, собрано 2900 постов (последний: 2024-01-24)
Обработано offset 2900, собрано 3000 постов (последний: 2023-12-07)
Обработано offset 3000, собрано 3100 постов (последний: 2023-11-10)
Обработано offset 3100, собрано 3200 постов (последний: 2023-10-11)
Обработано offset 3200, собрано 3300 постов (последний: 2023-09-13)
Обработано offset 3300, собрано 3400 постов (последний: 2023-08-04)
Обработано offset 3400, собрано 3500 постов (последний: 2023-06-24)
Обработано offset 3500, собрано 3600 постов (последний: 2023-05-24)
Обработано offset 3600, собрано 3700 постов (последний: 2023-04-25)
Обработано offset 3700, собрано 3800 постов (последний: 2023-04-04)
Обработано offset 3800, собрано 3900 постов (последний: 2023-03-03)
Обработано offset 3900, собрано 4000 постов (последний: 2023-01-25)
Обработано offset 4000, собрано 4100 постов (последний: 2022-11-11)
Обработано offset 4100, собрано 4200 постов (последний: 2022-09-13)
Обработано offset 4200, собрано 4300 постов (последний: 2022-06-06)
Обработано offset 4300, собрано 4400 постов (последний: 2022-04-04)
Обработано offset 4400, собрано 4500 постов (последний: 2022-01-18)
Обработано offset 4500, собрано 4600 постов (последний: 2021-10-26)
Обработано offset 4600, собрано 4700 постов (последний: 2021-08-25)
Обработано offset 4700, собрано 4800 постов (последний: 2021-06-11)
Обработано offset 4800, собрано 4900 постов (последний: 2021-04-11)
Обработано offset 4900, собрано 5000 постов (последний: 2021-02-11)
Обработано offset 5000, собрано 5100 постов (последний: 2020-11-18)
Обработано offset 5100, собрано 5200 постов (последний: 2020-10-01)
Обработано offset 5200, собрано 5300 постов (последний: 2020-07-30)
Обработано offset 5300, собрано 5400 постов (последний: 2020-06-18)
Обработано offset 5400, собрано 5500 постов (последний: 2020-04-30)
Обработано offset 5500, собрано 5600 постов (последний: 2020-03-25)
Обработано offset 5600, собрано 5700 постов (последний: 2020-01-31)

- Достигли 2019 года -
Последний пост: 33105 от 2019-12-31
Всего собрано постов: 5731
Диапазон дат: 2020-01-02 - 2026-05-05

In [ ]:
# МИРЭА
group_id = '-1388'
name = 'mirea.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-20)
Обработано offset 100, собрано 200 постов (последний: 2026-04-05)
Обработано offset 200, собрано 300 постов (последний: 2026-03-16)
Обработано offset 300, собрано 400 постов (последний: 2026-02-26)
Обработано offset 400, собрано 500 постов (последний: 2026-02-09)
Обработано offset 500, собрано 600 постов (последний: 2026-01-20)
Обработано offset 600, собрано 700 постов (последний: 2025-12-27)
Обработано offset 700, собрано 800 постов (последний: 2025-12-06)
Обработано offset 800, собрано 900 постов (последний: 2025-11-17)
Обработано offset 900, собрано 1000 постов (последний: 2025-10-30)
Обработано offset 1000, собрано 1100 постов (последний: 2025-10-13)
Обработано offset 1100, собрано 1200 постов (последний: 2025-09-25)
Обработано offset 1200, собрано 1300 постов (последний: 2025-09-05)
Обработано offset 1300, собрано 1400 постов (последний: 2025-08-19)
Обработано offset 1400, собрано 1500 постов (последний: 2025-07-25)
Обработано offset 1500, собрано 1600 постов (последний: 2025-07-04)
Обработано offset 1600, собрано 1700 постов (последний: 2025-06-11)
Обработано offset 1700, собрано 1800 постов (последний: 2025-05-23)
Обработано offset 1800, собрано 1900 постов (последний: 2025-05-07)
Обработано offset 1900, собрано 2000 постов (последний: 2025-04-17)
Обработано offset 2000, собрано 2100 постов (последний: 2025-03-28)
Обработано offset 2100, собрано 2200 постов (последний: 2025-03-13)
Обработано offset 2200, собрано 2300 постов (последний: 2025-02-25)
Обработано offset 2300, собрано 2400 постов (последний: 2025-02-11)
Обработано offset 2400, собрано 2500 постов (последний: 2025-01-24)
Обработано offset 2500, собрано 2600 постов (последний: 2024-12-30)
Обработано offset 2600, собрано 2700 постов (последний: 2024-12-12)
Обработано offset 2700, собрано 2800 постов (последний: 2024-11-26)
Обработано offset 2800, собрано 2900 постов (последний: 2024-11-13)
Обработано offset 2900, собрано 3000 постов (последний: 2024-10-30)
Обработано offset 3000, собрано 3100 постов (последний: 2024-10-15)
Обработано offset 3100, собрано 3200 постов (последний: 2024-10-01)
Обработано offset 3200, собрано 3300 постов (последний: 2024-09-17)
Обработано offset 3300, собрано 3400 постов (последний: 2024-09-02)
Обработано offset 3400, собрано 3500 постов (последний: 2024-08-16)
Обработано offset 3500, собрано 3600 постов (последний: 2024-07-29)
Обработано offset 3600, собрано 3700 постов (последний: 2024-07-12)
Обработано offset 3700, собрано 3800 постов (последний: 2024-06-26)
Обработано offset 3800, собрано 3900 постов (последний: 2024-06-07)
Обработано offset 3900, собрано 4000 постов (последний: 2024-05-19)
Обработано offset 4000, собрано 4100 постов (последний: 2024-05-02)
Обработано offset 4100, собрано 4200 постов (последний: 2024-04-12)
Обработано offset 4200, собрано 4300 постов (последний: 2024-03-23)
Обработано offset 4300, собрано 4400 постов (последний: 2024-03-05)
Обработано offset 4400, собрано 4500 постов (последний: 2024-02-15)
Обработано offset 4500, собрано 4600 постов (последний: 2024-01-30)
Обработано offset 4600, собрано 4700 постов (последний: 2024-01-12)
Обработано offset 4700, собрано 4800 постов (последний: 2023-12-22)
Обработано offset 4800, собрано 4900 постов (последний: 2023-12-06)
Обработано offset 4900, собрано 5000 постов (последний: 2023-11-23)
Обработано offset 5000, собрано 5100 постов (последний: 2023-11-10)
Обработано offset 5100, собрано 5200 постов (последний: 2023-10-27)
Обработано offset 5200, собрано 5300 постов (последний: 2023-10-13)
Обработано offset 5300, собрано 5400 постов (последний: 2023-10-02)
Обработано offset 5400, собрано 5500 постов (последний: 2023-09-16)
Обработано offset 5500, собрано 5600 постов (последний: 2023-09-04)
Обработано offset 5600, собрано 5700 постов (последний: 2023-08-22)
Обработано offset 5700, собрано 5800 постов (последний: 2023-08-11)
Обработано offset 5800, собрано 5900 постов (последний: 2023-08-01)
Обработано offset 5900, собрано 6000 постов (последний: 2023-07-21)
Обработано offset 6000, собрано 6100 постов (последний: 2023-07-12)
Обработано offset 6100, собрано 6200 постов (последний: 2023-06-29)
Обработано offset 6200, собрано 6300 постов (последний: 2023-06-16)
Обработано offset 6300, собрано 6400 постов (последний: 2023-05-23)
Обработано offset 6400, собрано 6500 постов (последний: 2023-05-02)
Обработано offset 6500, собрано 6600 постов (последний: 2023-04-10)
Обработано offset 6600, собрано 6700 постов (последний: 2023-03-20)
Обработано offset 6700, собрано 6800 постов (последний: 2023-02-22)
Обработано offset 6800, собрано 6900 постов (последний: 2023-01-30)
Обработано offset 6900, собрано 7000 постов (последний: 2022-12-27)
Обработано offset 7000, собрано 7100 постов (последний: 2022-12-02)
Обработано offset 7100, собрано 7200 постов (последний: 2022-11-11)
Обработано offset 7200, собрано 7300 постов (последний: 2022-10-18)
Обработано offset 7300, собрано 7400 постов (последний: 2022-09-26)
Обработано offset 7400, собрано 7500 постов (последний: 2022-08-22)
Обработано offset 7500, собрано 7600 постов (последний: 2022-07-12)
Обработано offset 7600, собрано 7700 постов (последний: 2022-06-14)
Обработано offset 7700, собрано 7800 постов (последний: 2022-05-20)
Обработано offset 7800, собрано 7900 постов (последний: 2022-04-24)
Обработано offset 7900, собрано 8000 постов (последний: 2022-03-31)
Обработано offset 8000, собрано 8100 постов (последний: 2022-03-09)
Обработано offset 8100, собрано 8200 постов (последний: 2022-02-09)
Обработано offset 8200, собрано 8300 постов (последний: 2022-01-10)
Обработано offset 8300, собрано 8400 постов (последний: 2021-12-16)
Обработано offset 8400, собрано 8500 постов (последний: 2021-12-01)
Обработано offset 8500, собрано 8600 постов (последний: 2021-11-08)
Обработано offset 8600, собрано 8700 постов (последний: 2021-10-11)
Обработано offset 8700, собрано 8800 постов (последний: 2021-09-21)
Обработано offset 8800, собрано 8900 постов (последний: 2021-08-23)
Обработано offset 8900, собрано 9000 постов (последний: 2021-07-02)
Обработано offset 9000, собрано 9100 постов (последний: 2021-05-27)
Обработано offset 9100, собрано 9200 постов (последний: 2021-05-07)
Обработано offset 9200, собрано 9300 постов (последний: 2021-04-14)
Обработано offset 9300, собрано 9400 постов (последний: 2021-03-23)
Обработано offset 9400, собрано 9500 постов (последний: 2021-02-26)
Обработано offset 9500, собрано 9600 постов (последний: 2021-02-01)
Обработано offset 9600, собрано 9700 постов (последний: 2020-12-22)
Обработано offset 9700, собрано 9800 постов (последний: 2020-11-30)
Обработано offset 9800, собрано 9900 постов (последний: 2020-11-03)
Обработано offset 9900, собрано 10000 постов (последний: 2020-10-06)
Обработано offset 10000, собрано 10100 постов (последний: 2020-09-02)
Обработано offset 10100, собрано 10200 постов (последний: 2020-07-16)
Обработано offset 10200, собрано 10300 постов (последний: 2020-06-11)
Обработано offset 10300, собрано 10400 постов (последний: 2020-05-07)
Обработано offset 10400, собрано 10500 постов (последний: 2020-04-08)
Обработано offset 10500, собрано 10600 постов (последний: 2020-03-17)
Обработано offset 10600, собрано 10700 постов (последний: 2020-02-21)
Обработано offset 10700, собрано 10800 постов (последний: 2020-01-30)

- Достигли 2019 года -
Последний пост: 14636 от 2019-12-31
Всего собрано постов: 10851
Диапазон дат: 2020-01-09 - 2026-05-06

In [ ]:
# РАНХ
group_id = '-5398'
name = 'ranepa.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-19)
Обработано offset 100, собрано 200 постов (последний: 2026-03-31)
Обработано offset 200, собрано 300 постов (последний: 2026-03-13)
Обработано offset 300, собрано 400 постов (последний: 2026-02-20)
Обработано offset 400, собрано 500 постов (последний: 2026-02-09)
Обработано offset 500, собрано 600 постов (последний: 2026-01-22)
Обработано offset 600, собрано 700 постов (последний: 2025-12-25)
Обработано offset 700, собрано 800 постов (последний: 2025-12-08)
Обработано offset 800, собрано 900 постов (последний: 2025-11-20)
Обработано offset 900, собрано 1000 постов (последний: 2025-11-01)
Обработано offset 1000, собрано 1100 постов (последний: 2025-10-14)
Обработано offset 1100, собрано 1200 постов (последний: 2025-09-26)
Обработано offset 1200, собрано 1300 постов (последний: 2025-09-13)
Обработано offset 1300, собрано 1400 постов (последний: 2025-08-27)
Обработано offset 1400, собрано 1500 постов (последний: 2025-08-07)
Обработано offset 1500, собрано 1600 постов (последний: 2025-07-17)
Обработано offset 1600, собрано 1700 постов (последний: 2025-06-27)
Обработано offset 1700, собрано 1800 постов (последний: 2025-06-05)
Обработано offset 1800, собрано 1900 постов (последний: 2025-05-19)
Обработано offset 1900, собрано 2000 постов (последний: 2025-05-02)
Обработано offset 2000, собрано 2100 постов (последний: 2025-04-15)
Обработано offset 2100, собрано 2200 постов (последний: 2025-04-01)
Обработано offset 2200, собрано 2300 постов (последний: 2025-03-14)
Обработано offset 2300, собрано 2400 постов (последний: 2025-02-27)
Обработано offset 2400, собрано 2500 постов (последний: 2025-02-12)
Обработано offset 2500, собрано 2600 постов (последний: 2025-01-25)
Обработано offset 2600, собрано 2700 постов (последний: 2025-01-04)
Обработано offset 2700, собрано 2800 постов (последний: 2024-12-11)
Обработано offset 2800, собрано 2900 постов (последний: 2024-11-14)
Обработано offset 2900, собрано 3000 постов (последний: 2024-10-18)
Обработано offset 3000, собрано 3100 постов (последний: 2024-09-25)
Обработано offset 3100, собрано 3200 постов (последний: 2024-09-09)
Обработано offset 3200, собрано 3300 постов (последний: 2024-08-20)
Обработано offset 3300, собрано 3400 постов (последний: 2024-07-29)
Обработано offset 3400, собрано 3500 постов (последний: 2024-07-09)
Обработано offset 3500, собрано 3600 постов (последний: 2024-06-17)
Обработано offset 3600, собрано 3700 постов (последний: 2024-05-28)
Обработано offset 3700, собрано 3800 постов (последний: 2024-05-08)
Обработано offset 3800, собрано 3900 постов (последний: 2024-04-18)
Обработано offset 3900, собрано 4000 постов (последний: 2024-04-01)
Обработано offset 4000, собрано 4100 постов (последний: 2024-03-14)
Обработано offset 4100, собрано 4200 постов (последний: 2024-02-27)
Обработано offset 4200, собрано 4300 постов (последний: 2024-02-08)
Обработано offset 4300, собрано 4400 постов (последний: 2024-01-21)
Обработано offset 4400, собрано 4500 постов (последний: 2023-12-25)
Обработано offset 4500, собрано 4600 постов (последний: 2023-12-05)
Обработано offset 4600, собрано 4700 постов (последний: 2023-11-17)
Обработано offset 4700, собрано 4800 постов (последний: 2023-10-27)
Обработано offset 4800, собрано 4900 постов (последний: 2023-10-10)
Обработано offset 4900, собрано 5000 постов (последний: 2023-09-26)
Обработано offset 5000, собрано 5100 постов (последний: 2023-09-08)
Обработано offset 5100, собрано 5200 постов (последний: 2023-08-21)
Обработано offset 5200, собрано 5300 постов (последний: 2023-07-31)
Обработано offset 5300, собрано 5400 постов (последний: 2023-07-11)
Обработано offset 5400, собрано 5500 постов (последний: 2023-06-21)
Обработано offset 5500, собрано 5600 постов (последний: 2023-06-01)
Обработано offset 5600, собрано 5700 постов (последний: 2023-05-16)
Обработано offset 5700, собрано 5800 постов (последний: 2023-04-24)
Обработано offset 5800, собрано 5900 постов (последний: 2023-04-06)
Обработано offset 5900, собрано 6000 постов (последний: 2023-03-20)
Обработано offset 6000, собрано 6100 постов (последний: 2023-02-28)
Обработано offset 6100, собрано 6200 постов (последний: 2023-02-08)
Обработано offset 6200, собрано 6300 постов (последний: 2023-01-23)
Обработано offset 6300, собрано 6400 постов (последний: 2022-12-28)
Обработано offset 6400, собрано 6500 постов (последний: 2022-12-09)
Обработано offset 6500, собрано 6600 постов (последний: 2022-11-27)
Обработано offset 6600, собрано 6700 постов (последний: 2022-11-09)
Обработано offset 6700, собрано 6800 постов (последний: 2022-10-20)
Обработано offset 6800, собрано 6900 постов (последний: 2022-10-03)
Обработано offset 6900, собрано 7000 постов (последний: 2022-09-14)
Обработано offset 7000, собрано 7100 постов (последний: 2022-08-26)
Обработано offset 7100, собрано 7200 постов (последний: 2022-08-05)
Обработано offset 7200, собрано 7300 постов (последний: 2022-07-21)
Обработано offset 7300, собрано 7400 постов (последний: 2022-07-06)
Обработано offset 7400, собрано 7500 постов (последний: 2022-06-20)
Обработано offset 7500, собрано 7600 постов (последний: 2022-06-02)
Обработано offset 7600, собрано 7700 постов (последний: 2022-05-17)
Обработано offset 7700, собрано 7800 постов (последний: 2022-04-28)
Обработано offset 7800, собрано 7900 постов (последний: 2022-04-14)
Обработано offset 7900, собрано 8000 постов (последний: 2022-03-31)
Обработано offset 8000, собрано 8100 постов (последний: 2022-03-14)
Обработано offset 8100, собрано 8200 постов (последний: 2022-02-16)
Обработано offset 8200, собрано 8300 постов (последний: 2022-01-25)
Обработано offset 8300, собрано 8400 постов (последний: 2021-12-24)
Обработано offset 8400, собрано 8500 постов (последний: 2021-12-01)
Обработано offset 8500, собрано 8600 постов (последний: 2021-10-25)
Обработано offset 8600, собрано 8700 постов (последний: 2021-09-07)
Обработано offset 8700, собрано 8800 постов (последний: 2021-07-28)
Обработано offset 8800, собрано 8900 постов (последний: 2021-07-05)
Обработано offset 8900, собрано 9000 постов (последний: 2021-06-12)
Обработано offset 9000, собрано 9100 постов (последний: 2021-05-19)
Обработано offset 9100, собрано 9200 постов (последний: 2021-04-22)
Обработано offset 9200, собрано 9300 постов (последний: 2021-04-02)
Обработано offset 9300, собрано 9400 постов (последний: 2021-03-16)
Обработано offset 9400, собрано 9500 постов (последний: 2021-02-20)
Обработано offset 9500, собрано 9600 постов (последний: 2021-02-02)
Обработано offset 9600, собрано 9700 постов (последний: 2021-01-16)
Обработано offset 9700, собрано 9800 постов (последний: 2021-01-11)
Обработано offset 9800, собрано 9900 постов (последний: 2020-12-14)
Обработано offset 9900, собрано 10000 постов (последний: 2020-11-24)
Обработано offset 10000, собрано 10100 постов (последний: 2020-11-09)
Обработано offset 10100, собрано 10200 постов (последний: 2020-10-20)
Обработано offset 10200, собрано 10300 постов (последний: 2020-10-03)
Обработано offset 10300, собрано 10400 постов (последний: 2020-09-20)
Обработано offset 10400, собрано 10500 постов (последний: 2020-08-31)
Обработано offset 10500, собрано 10600 постов (последний: 2020-08-06)
Обработано offset 10600, собрано 10700 постов (последний: 2020-07-13)
Обработано offset 10700, собрано 10800 постов (последний: 2020-06-19)
Обработано offset 10800, собрано 10900 постов (последний: 2020-06-01)
Обработано offset 10900, собрано 11000 постов (последний: 2020-05-12)
Обработано offset 11000, собрано 11100 постов (последний: 2020-04-23)
Обработано offset 11100, собрано 11200 постов (последний: 2020-04-11)
Обработано offset 11200, собрано 11300 постов (последний: 2020-03-23)
Обработано offset 11300, собрано 11400 постов (последний: 2020-02-14)

- Достигли 2019 года -
Последний пост: 24329 от 2019-12-31
Всего собрано постов: 11480
Диапазон дат: 2020-01-05 - 2026-05-06

In [ ]:
# МИСИС
group_id = '-62258607'
name = 'misis.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-05)
Обработано offset 100, собрано 200 постов (последний: 2026-03-05)
Обработано offset 200, собрано 300 постов (последний: 2026-02-08)
Обработано offset 300, собрано 400 постов (последний: 2026-01-09)
Обработано offset 400, собрано 500 постов (последний: 2025-12-08)
Обработано offset 500, собрано 600 постов (последний: 2025-11-13)
Обработано offset 600, собрано 700 постов (последний: 2025-10-17)
Обработано offset 700, собрано 800 постов (последний: 2025-09-22)
Обработано offset 800, собрано 900 постов (последний: 2025-08-29)
Обработано offset 900, собрано 1000 постов (последний: 2025-07-30)
Обработано offset 1000, собрано 1100 постов (последний: 2025-06-26)
Обработано offset 1100, собрано 1200 постов (последний: 2025-05-27)
Обработано offset 1200, собрано 1300 постов (последний: 2025-04-25)
Обработано offset 1300, собрано 1400 постов (последний: 2025-03-28)
Обработано offset 1400, собрано 1500 постов (последний: 2025-02-25)
Обработано offset 1500, собрано 1600 постов (последний: 2025-01-18)
Обработано offset 1600, собрано 1700 постов (последний: 2024-12-11)
Обработано offset 1700, собрано 1800 постов (последний: 2024-11-15)
Обработано offset 1800, собрано 1900 постов (последний: 2024-10-19)
Обработано offset 1900, собрано 2000 постов (последний: 2024-09-21)
Обработано offset 2000, собрано 2100 постов (последний: 2024-08-26)
Обработано offset 2100, собрано 2200 постов (последний: 2024-07-30)
Обработано offset 2200, собрано 2300 постов (последний: 2024-07-02)
Обработано offset 2300, собрано 2400 постов (последний: 2024-06-02)
Обработано offset 2400, собрано 2500 постов (последний: 2024-05-06)
Обработано offset 2500, собрано 2600 постов (последний: 2024-04-06)
Обработано offset 2600, собрано 2700 постов (последний: 2024-03-16)
Обработано offset 2700, собрано 2800 постов (последний: 2024-02-26)
Обработано offset 2800, собрано 2900 постов (последний: 2024-02-04)
Обработано offset 2900, собрано 3000 постов (последний: 2024-01-14)
Обработано offset 3000, собрано 3100 постов (последний: 2023-12-20)
Обработано offset 3100, собрано 3200 постов (последний: 2023-12-04)
Обработано offset 3200, собрано 3300 постов (последний: 2023-11-17)
Обработано offset 3300, собрано 3400 постов (последний: 2023-11-02)
Обработано offset 3400, собрано 3500 постов (последний: 2023-10-17)
Обработано offset 3500, собрано 3600 постов (последний: 2023-09-27)
Обработано offset 3600, собрано 3700 постов (последний: 2023-09-08)
Обработано offset 3700, собрано 3800 постов (последний: 2023-08-23)
Обработано offset 3800, собрано 3900 постов (последний: 2023-07-31)
Обработано offset 3900, собрано 4000 постов (последний: 2023-07-10)
Обработано offset 4000, собрано 4100 постов (последний: 2023-06-19)
Обработано offset 4100, собрано 4200 постов (последний: 2023-05-30)
Обработано offset 4200, собрано 4300 постов (последний: 2023-05-12)
Обработано offset 4300, собрано 4400 постов (последний: 2023-04-24)
Обработано offset 4400, собрано 4500 постов (последний: 2023-04-09)
Обработано offset 4500, собрано 4600 постов (последний: 2023-03-19)
Обработано offset 4600, собрано 4700 постов (последний: 2023-02-27)
Обработано offset 4700, собрано 4800 постов (последний: 2023-02-06)
Обработано offset 4800, собрано 4900 постов (последний: 2023-01-18)
Обработано offset 4900, собрано 5000 постов (последний: 2022-12-27)
Обработано offset 5000, собрано 5100 постов (последний: 2022-12-08)
Обработано offset 5100, собрано 5200 постов (последний: 2022-11-22)
Обработано offset 5200, собрано 5300 постов (последний: 2022-11-05)
Обработано offset 5300, собрано 5400 постов (последний: 2022-10-17)
Обработано offset 5400, собрано 5500 постов (последний: 2022-09-27)
Обработано offset 5500, собрано 5600 постов (последний: 2022-09-06)
Обработано offset 5600, собрано 5700 постов (последний: 2022-08-19)
Обработано offset 5700, собрано 5800 постов (последний: 2022-07-30)
Обработано offset 5800, собрано 5900 постов (последний: 2022-07-13)
Обработано offset 5900, собрано 6000 постов (последний: 2022-06-28)
Обработано offset 6000, собрано 6100 постов (последний: 2022-06-09)
Обработано offset 6100, собрано 6200 постов (последний: 2022-05-23)
Обработано offset 6200, собрано 6300 постов (последний: 2022-05-08)
Обработано offset 6300, собрано 6400 постов (последний: 2022-04-22)
Обработано offset 6400, собрано 6500 постов (последний: 2022-04-07)
Обработано offset 6500, собрано 6600 постов (последний: 2022-03-21)
Обработано offset 6600, собрано 6700 постов (последний: 2022-03-01)
Обработано offset 6700, собрано 6800 постов (последний: 2022-02-08)
Обработано offset 6800, собрано 6900 постов (последний: 2022-01-16)
Обработано offset 6900, собрано 7000 постов (последний: 2021-12-20)
Обработано offset 7000, собрано 7100 постов (последний: 2021-12-02)
Обработано offset 7100, собрано 7200 постов (последний: 2021-11-08)
Обработано offset 7200, собрано 7300 постов (последний: 2021-10-15)
Обработано offset 7300, собрано 7400 постов (последний: 2021-09-25)
Обработано offset 7400, собрано 7500 постов (последний: 2021-09-06)
Обработано offset 7500, собрано 7600 постов (последний: 2021-08-17)
Обработано offset 7600, собрано 7700 постов (последний: 2021-07-26)
Обработано offset 7700, собрано 7800 постов (последний: 2021-07-10)
Обработано offset 7800, собрано 7900 постов (последний: 2021-06-25)
Обработано offset 7900, собрано 8000 постов (последний: 2021-06-10)
Обработано offset 8000, собрано 8100 постов (последний: 2021-05-26)
Обработано offset 8100, собрано 8200 постов (последний: 2021-05-09)
Обработано offset 8200, собрано 8300 постов (последний: 2021-04-22)
Обработано offset 8300, собрано 8400 постов (последний: 2021-04-08)
Обработано offset 8400, собрано 8500 постов (последний: 2021-03-20)
Обработано offset 8500, собрано 8600 постов (последний: 2021-02-27)
Обработано offset 8600, собрано 8700 постов (последний: 2021-02-04)
Обработано offset 8700, собрано 8800 постов (последний: 2021-01-19)
Обработано offset 8800, собрано 8900 постов (последний: 2020-12-29)
Обработано offset 8900, собрано 9000 постов (последний: 2020-12-15)
Обработано offset 9000, собрано 9100 постов (последний: 2020-12-01)
Обработано offset 9100, собрано 9200 постов (последний: 2020-11-16)
Обработано offset 9200, собрано 9300 постов (последний: 2020-10-29)
Обработано offset 9300, собрано 9400 постов (последний: 2020-10-09)
Обработано offset 9400, собрано 9500 постов (последний: 2020-09-17)
Обработано offset 9500, собрано 9600 постов (последний: 2020-09-04)
Обработано offset 9600, собрано 9700 постов (последний: 2020-08-22)
Обработано offset 9700, собрано 9800 постов (последний: 2020-08-05)
Обработано offset 9800, собрано 9900 постов (последний: 2020-07-20)
Обработано offset 9900, собрано 10000 постов (последний: 2020-07-06)
Обработано offset 10000, собрано 10100 постов (последний: 2020-06-25)
Обработано offset 10100, собрано 10200 постов (последний: 2020-06-12)
Обработано offset 10200, собрано 10300 постов (последний: 2020-05-29)
Обработано offset 10300, собрано 10400 постов (последний: 2020-05-19)
Обработано offset 10400, собрано 10500 постов (последний: 2020-05-07)
Обработано offset 10500, собрано 10600 постов (последний: 2020-04-27)
Обработано offset 10600, собрано 10700 постов (последний: 2020-04-16)
Обработано offset 10700, собрано 10800 постов (последний: 2020-04-04)
Обработано offset 10800, собрано 10900 постов (последний: 2020-03-23)
Обработано offset 10900, собрано 11000 постов (последний: 2020-03-08)
Обработано offset 11000, собрано 11100 постов (последний: 2020-02-20)
Обработано offset 11100, собрано 11200 постов (последний: 2020-02-01)
Обработано offset 11200, собрано 11300 постов (последний: 2020-01-09)

- Достигли 2019 года -
Последний пост: 20906 от 2019-12-31
Всего собрано постов: 11334
Диапазон дат: 2020-01-01 - 2026-05-06

In [ ]:
# бауманка
group_id = '-40427933'
name = 'bmstu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-11)
Обработано offset 100, собрано 200 постов (последний: 2026-03-10)
Обработано offset 200, собрано 300 постов (последний: 2026-02-05)
Обработано offset 300, собрано 400 постов (последний: 2025-12-28)
Обработано offset 400, собрано 500 постов (последний: 2025-11-28)
Обработано offset 500, собрано 600 постов (последний: 2025-10-29)
Обработано offset 600, собрано 700 постов (последний: 2025-09-30)
Обработано offset 700, собрано 800 постов (последний: 2025-08-26)
Обработано offset 800, собрано 900 постов (последний: 2025-07-21)
Обработано offset 900, собрано 1000 постов (последний: 2025-06-20)
Обработано offset 1000, собрано 1100 постов (последний: 2025-05-21)
Обработано offset 1100, собрано 1200 постов (последний: 2025-04-18)
Обработано offset 1200, собрано 1300 постов (последний: 2025-03-21)
Обработано offset 1300, собрано 1400 постов (последний: 2025-02-18)
Обработано offset 1400, собрано 1500 постов (последний: 2025-01-16)
Обработано offset 1500, собрано 1600 постов (последний: 2024-12-11)
Обработано offset 1600, собрано 1700 постов (последний: 2024-11-13)
Обработано offset 1700, собрано 1800 постов (последний: 2024-10-17)
Обработано offset 1800, собрано 1900 постов (последний: 2024-09-23)
Обработано offset 1900, собрано 2000 постов (последний: 2024-08-27)
Обработано offset 2000, собрано 2100 постов (последний: 2024-07-24)
Обработано offset 2100, собрано 2200 постов (последний: 2024-06-27)
Обработано offset 2200, собрано 2300 постов (последний: 2024-05-30)
Обработано offset 2300, собрано 2400 постов (последний: 2024-04-29)
Обработано offset 2400, собрано 2500 постов (последний: 2024-04-09)
Обработано offset 2500, собрано 2600 постов (последний: 2024-03-19)
Обработано offset 2600, собрано 2700 постов (последний: 2024-02-22)
Обработано offset 2700, собрано 2800 постов (последний: 2024-02-01)
Обработано offset 2800, собрано 2900 постов (последний: 2023-12-25)
Обработано offset 2900, собрано 3000 постов (последний: 2023-11-30)
Обработано offset 3000, собрано 3100 постов (последний: 2023-11-08)
Обработано offset 3100, собрано 3200 постов (последний: 2023-10-16)
Обработано offset 3200, собрано 3300 постов (последний: 2023-09-23)
Обработано offset 3300, собрано 3400 постов (последний: 2023-08-30)
Обработано offset 3400, собрано 3500 постов (последний: 2023-07-28)
Обработано offset 3500, собрано 3600 постов (последний: 2023-06-29)
Обработано offset 3600, собрано 3700 постов (последний: 2023-05-31)
Обработано offset 3700, собрано 3800 постов (последний: 2023-05-05)
Обработано offset 3800, собрано 3900 постов (последний: 2023-04-13)
Обработано offset 3900, собрано 4000 постов (последний: 2023-03-23)
Обработано offset 4000, собрано 4100 постов (последний: 2023-03-01)
Обработано offset 4100, собрано 4200 постов (последний: 2023-02-06)
Обработано offset 4200, собрано 4300 постов (последний: 2023-01-09)
Обработано offset 4300, собрано 4400 постов (последний: 2022-12-09)
Обработано offset 4400, собрано 4500 постов (последний: 2022-11-21)
Обработано offset 4500, собрано 4600 постов (последний: 2022-10-31)
Обработано offset 4600, собрано 4700 постов (последний: 2022-10-12)
Обработано offset 4700, собрано 4800 постов (последний: 2022-09-25)
Обработано offset 4800, собрано 4900 постов (последний: 2022-09-04)
Обработано offset 4900, собрано 5000 постов (последний: 2022-08-03)
Обработано offset 5000, собрано 5100 постов (последний: 2022-07-06)
Обработано offset 5100, собрано 5200 постов (последний: 2022-06-09)
Обработано offset 5200, собрано 5300 постов (последний: 2022-05-16)
Обработано offset 5300, собрано 5400 постов (последний: 2022-04-17)
Обработано offset 5400, собрано 5500 постов (последний: 2022-03-23)
Обработано offset 5500, собрано 5600 постов (последний: 2022-02-17)
Обработано offset 5600, собрано 5700 постов (последний: 2022-01-14)
Обработано offset 5700, собрано 5800 постов (последний: 2021-12-05)
Обработано offset 5800, собрано 5900 постов (последний: 2021-11-07)
Обработано offset 5900, собрано 6000 постов (последний: 2021-10-02)
Обработано offset 6000, собрано 6100 постов (последний: 2021-08-26)
Обработано offset 6100, собрано 6200 постов (последний: 2021-06-26)
Обработано offset 6200, собрано 6300 постов (последний: 2021-05-17)
Обработано offset 6300, собрано 6400 постов (последний: 2021-03-31)
Обработано offset 6400, собрано 6500 постов (последний: 2021-02-15)
Обработано offset 6500, собрано 6600 постов (последний: 2020-12-02)
Обработано offset 6600, собрано 6700 постов (последний: 2020-10-26)
Обработано offset 6700, собрано 6800 постов (последний: 2020-09-08)
Обработано offset 6800, собрано 6900 постов (последний: 2020-06-27)
Обработано offset 6900, собрано 7000 постов (последний: 2020-05-02)
Обработано offset 7000, собрано 7100 постов (последний: 2020-03-23)
Обработано offset 7100, собрано 7200 постов (последний: 2020-02-05)

- Достигли 2019 года -
Последний пост: 18087 от 2019-12-24
Всего собрано постов: 7222
Диапазон дат: 2020-01-09 - 2026-05-05

In [ ]:
# рудн
group_id = '-1711'
name = 'rudn.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-06)
Обработано offset 100, собрано 200 постов (последний: 2026-03-03)
Обработано offset 200, собрано 300 постов (последний: 2026-01-25)
Обработано offset 300, собрано 400 постов (последний: 2025-12-04)
Обработано offset 400, собрано 500 постов (последний: 2025-10-28)
Обработано offset 500, собрано 600 постов (последний: 2025-09-17)
Обработано offset 600, собрано 700 постов (последний: 2025-08-16)
Обработано offset 700, собрано 800 постов (последний: 2025-07-17)
Обработано offset 800, собрано 900 постов (последний: 2025-06-20)
Обработано offset 900, собрано 1000 постов (последний: 2025-05-19)
Обработано offset 1000, собрано 1100 постов (последний: 2025-04-16)
Обработано offset 1100, собрано 1200 постов (последний: 2025-03-17)
Обработано offset 1200, собрано 1300 постов (последний: 2025-02-08)
Обработано offset 1300, собрано 1400 постов (последний: 2025-01-14)
Обработано offset 1400, собрано 1500 постов (последний: 2024-12-13)
Обработано offset 1500, собрано 1600 постов (последний: 2024-11-25)
Обработано offset 1600, собрано 1700 постов (последний: 2024-11-08)
Обработано offset 1700, собрано 1800 постов (последний: 2024-10-26)
Обработано offset 1800, собрано 1900 постов (последний: 2024-09-30)
Обработано offset 1900, собрано 2000 постов (последний: 2024-08-31)
Обработано offset 2000, собрано 2100 постов (последний: 2024-07-28)
Обработано offset 2100, собрано 2200 постов (последний: 2024-06-24)
Обработано offset 2200, собрано 2300 постов (последний: 2024-04-30)
Обработано offset 2300, собрано 2400 постов (последний: 2024-03-06)
Обработано offset 2400, собрано 2500 постов (последний: 2024-01-26)
Обработано offset 2500, собрано 2600 постов (последний: 2023-12-10)
Обработано offset 2600, собрано 2700 постов (последний: 2023-11-15)
Обработано offset 2700, собрано 2800 постов (последний: 2023-10-05)
Обработано offset 2800, собрано 2900 постов (последний: 2023-08-24)
Обработано offset 2900, собрано 3000 постов (последний: 2023-07-07)
Обработано offset 3000, собрано 3100 постов (последний: 2023-06-01)
Обработано offset 3100, собрано 3200 постов (последний: 2023-04-25)
Обработано offset 3200, собрано 3300 постов (последний: 2023-03-20)
Обработано offset 3300, собрано 3400 постов (последний: 2023-02-03)
Обработано offset 3400, собрано 3500 постов (последний: 2022-12-29)
Обработано offset 3500, собрано 3600 постов (последний: 2022-11-22)
Обработано offset 3600, собрано 3700 постов (последний: 2022-10-28)
Обработано offset 3700, собрано 3800 постов (последний: 2022-09-28)
Обработано offset 3800, собрано 3900 постов (последний: 2022-08-31)
Обработано offset 3900, собрано 4000 постов (последний: 2022-07-27)
Обработано offset 4000, собрано 4100 постов (последний: 2022-06-28)
Обработано offset 4100, собрано 4200 постов (последний: 2022-05-27)
Обработано offset 4200, собрано 4300 постов (последний: 2022-04-26)
Обработано offset 4300, собрано 4400 постов (последний: 2022-03-22)
Обработано offset 4400, собрано 4500 постов (последний: 2022-02-03)
Обработано offset 4500, собрано 4600 постов (последний: 2021-12-29)
Обработано offset 4600, собрано 4700 постов (последний: 2021-11-16)
Обработано offset 4700, собрано 4800 постов (последний: 2021-10-05)
Обработано offset 4800, собрано 4900 постов (последний: 2021-08-18)
Обработано offset 4900, собрано 5000 постов (последний: 2021-06-26)
Обработано offset 5000, собрано 5100 постов (последний: 2021-04-29)
Обработано offset 5100, собрано 5200 постов (последний: 2021-03-17)
Обработано offset 5200, собрано 5300 постов (последний: 2021-02-01)
Обработано offset 5300, собрано 5400 постов (последний: 2020-12-21)
Обработано offset 5400, собрано 5500 постов (последний: 2020-10-27)
Обработано offset 5500, собрано 5600 постов (последний: 2020-08-26)
Обработано offset 5600, собрано 5700 постов (последний: 2020-07-03)
Обработано offset 5700, собрано 5800 постов (последний: 2020-05-15)
Обработано offset 5800, собрано 5900 постов (последний: 2020-03-17)
Обработано offset 5900, собрано 6000 постов (последний: 2020-01-27)

- Достигли 2019 года -
Последний пост: 51504 от 2019-12-31
Всего собрано постов: 6038
Диапазон дат: 2020-01-01 - 2026-05-06

In [ ]:
# сеченов
group_id = '-65464437'
name = 'sechenov.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-03)
Обработано offset 100, собрано 200 постов (последний: 2026-03-03)
Обработано offset 200, собрано 300 постов (последний: 2026-01-29)
Обработано offset 300, собрано 400 постов (последний: 2025-12-27)
Обработано offset 400, собрано 500 постов (последний: 2025-11-30)
Обработано offset 500, собрано 600 постов (последний: 2025-10-24)
Обработано offset 600, собрано 700 постов (последний: 2025-09-25)
Обработано offset 700, собрано 800 постов (последний: 2025-08-28)
Обработано offset 800, собрано 900 постов (последний: 2025-07-22)
Обработано offset 900, собрано 1000 постов (последний: 2025-06-19)
Обработано offset 1000, собрано 1100 постов (последний: 2025-05-22)
Обработано offset 1100, собрано 1200 постов (последний: 2025-04-16)
Обработано offset 1200, собрано 1300 постов (последний: 2025-03-11)
Обработано offset 1300, собрано 1400 постов (последний: 2025-02-05)
Обработано offset 1400, собрано 1500 постов (последний: 2025-01-02)
Обработано offset 1500, собрано 1600 постов (последний: 2024-12-05)
Обработано offset 1600, собрано 1700 постов (последний: 2024-11-04)
Обработано offset 1700, собрано 1800 постов (последний: 2024-09-30)
Обработано offset 1800, собрано 1900 постов (последний: 2024-08-29)
Обработано offset 1900, собрано 2000 постов (последний: 2024-07-28)
Обработано offset 2000, собрано 2100 постов (последний: 2024-06-28)
Обработано offset 2100, собрано 2200 постов (последний: 2024-05-31)
Обработано offset 2200, собрано 2300 постов (последний: 2024-04-29)
Обработано offset 2300, собрано 2400 постов (последний: 2024-03-29)
Обработано offset 2400, собрано 2500 постов (последний: 2024-02-29)
Обработано offset 2500, собрано 2600 постов (последний: 2024-01-29)
Обработано offset 2600, собрано 2700 постов (последний: 2023-12-26)
Обработано offset 2700, собрано 2800 постов (последний: 2023-11-28)
Обработано offset 2800, собрано 2900 постов (последний: 2023-11-04)
Обработано offset 2900, собрано 3000 постов (последний: 2023-10-12)
Обработано offset 3000, собрано 3100 постов (последний: 2023-09-18)
Обработано offset 3100, собрано 3200 постов (последний: 2023-08-15)
Обработано offset 3200, собрано 3300 постов (последний: 2023-07-14)
Обработано offset 3300, собрано 3400 постов (последний: 2023-06-19)
Обработано offset 3400, собрано 3500 постов (последний: 2023-05-19)
Обработано offset 3500, собрано 3600 постов (последний: 2023-04-11)
Обработано offset 3600, собрано 3700 постов (последний: 2023-02-22)
Обработано offset 3700, собрано 3800 постов (последний: 2023-01-12)
Обработано offset 3800, собрано 3900 постов (последний: 2022-12-01)
Обработано offset 3900, собрано 4000 постов (последний: 2022-09-02)
Обработано offset 4000, собрано 4100 постов (последний: 2022-05-27)
Обработано offset 4100, собрано 4200 постов (последний: 2022-01-23)
Обработано offset 4200, собрано 4300 постов (последний: 2021-07-01)
Обработано offset 4300, собрано 4400 постов (последний: 2021-02-19)
Обработано offset 4400, собрано 4500 постов (последний: 2020-06-22)
Обработано offset 4500, собрано 4600 постов (последний: 2020-04-03)
Обработано offset 4600, собрано 4700 постов (последний: 2020-02-11)

- Достигли 2019 года -
Последний пост: 8268 от 2019-12-30
Всего собрано постов: 4777
Диапазон дат: 2020-01-09 - 2026-05-06

In [ ]:
# мгимо
group_id = '-26555975'
name = 'mgimo.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-06)
Обработано offset 100, собрано 200 постов (последний: 2026-03-10)
Обработано offset 200, собрано 300 постов (последний: 2026-02-12)
Обработано offset 300, собрано 400 постов (последний: 2025-12-19)
Обработано offset 400, собрано 500 постов (последний: 2025-11-24)
Обработано offset 500, собрано 600 постов (последний: 2025-10-28)
Обработано offset 600, собрано 700 постов (последний: 2025-10-07)
Обработано offset 700, собрано 800 постов (последний: 2025-09-19)
Обработано offset 800, собрано 900 постов (последний: 2025-08-26)
Обработано offset 900, собрано 1000 постов (последний: 2025-07-18)
Обработано offset 1000, собрано 1100 постов (последний: 2025-07-02)
Обработано offset 1100, собрано 1200 постов (последний: 2025-06-15)
Обработано offset 1200, собрано 1300 постов (последний: 2025-05-24)
Обработано offset 1300, собрано 1400 постов (последний: 2025-04-30)
Обработано offset 1400, собрано 1500 постов (последний: 2025-04-12)
Обработано offset 1500, собрано 1600 постов (последний: 2025-03-27)
Обработано offset 1600, собрано 1700 постов (последний: 2025-03-12)
Обработано offset 1700, собрано 1800 постов (последний: 2025-02-23)
Обработано offset 1800, собрано 1900 постов (последний: 2025-01-27)
Обработано offset 1900, собрано 2000 постов (последний: 2024-12-16)
Обработано offset 2000, собрано 2100 постов (последний: 2024-11-26)
Обработано offset 2100, собрано 2200 постов (последний: 2024-10-31)
Обработано offset 2200, собрано 2300 постов (последний: 2024-10-09)
Обработано offset 2300, собрано 2400 постов (последний: 2024-09-14)
Обработано offset 2400, собрано 2500 постов (последний: 2024-07-31)
Обработано offset 2500, собрано 2600 постов (последний: 2024-06-26)
Обработано offset 2600, собрано 2700 постов (последний: 2024-06-03)
Обработано offset 2700, собрано 2800 постов (последний: 2024-05-17)
Обработано offset 2800, собрано 2900 постов (последний: 2024-04-23)
Обработано offset 2900, собрано 3000 постов (последний: 2024-04-05)
Обработано offset 3000, собрано 3100 постов (последний: 2024-03-13)
Обработано offset 3100, собрано 3200 постов (последний: 2024-02-20)
Обработано offset 3200, собрано 3300 постов (последний: 2024-01-10)
Обработано offset 3300, собрано 3400 постов (последний: 2023-12-09)
Обработано offset 3400, собрано 3500 постов (последний: 2023-11-22)
Обработано offset 3500, собрано 3600 постов (последний: 2023-11-02)
Обработано offset 3600, собрано 3700 постов (последний: 2023-10-10)
Обработано offset 3700, собрано 3800 постов (последний: 2023-09-13)
Обработано offset 3800, собрано 3900 постов (последний: 2023-07-27)
Обработано offset 3900, собрано 4000 постов (последний: 2023-07-03)
Обработано offset 4000, собрано 4100 постов (последний: 2023-06-07)
Обработано offset 4100, собрано 4200 постов (последний: 2023-05-17)
Обработано offset 4200, собрано 4300 постов (последний: 2023-04-18)
Обработано offset 4300, собрано 4400 постов (последний: 2023-03-28)
Обработано offset 4400, собрано 4500 постов (последний: 2023-03-01)
Обработано offset 4500, собрано 4600 постов (последний: 2023-01-22)
Обработано offset 4600, собрано 4700 постов (последний: 2022-12-10)
Обработано offset 4700, собрано 4800 постов (последний: 2022-11-11)
Обработано offset 4800, собрано 4900 постов (последний: 2022-10-13)
Обработано offset 4900, собрано 5000 постов (последний: 2022-09-20)
Обработано offset 5000, собрано 5100 постов (последний: 2022-07-27)
Обработано offset 5100, собрано 5200 постов (последний: 2022-06-23)
Обработано offset 5200, собрано 5300 постов (последний: 2022-05-11)
Обработано offset 5300, собрано 5400 постов (последний: 2022-04-14)
Обработано offset 5400, собрано 5500 постов (последний: 2022-03-23)
Обработано offset 5500, собрано 5600 постов (последний: 2022-02-10)
Обработано offset 5600, собрано 5700 постов (последний: 2021-12-17)
Обработано offset 5700, собрано 5800 постов (последний: 2021-11-17)
Обработано offset 5800, собрано 5900 постов (последний: 2021-10-07)
Обработано offset 5900, собрано 6000 постов (последний: 2021-09-03)
Обработано offset 6000, собрано 6100 постов (последний: 2021-07-07)
Обработано offset 6100, собрано 6200 постов (последний: 2021-05-29)
Обработано offset 6200, собрано 6300 постов (последний: 2021-04-30)
Обработано offset 6300, собрано 6400 постов (последний: 2021-04-09)
Обработано offset 6400, собрано 6500 постов (последний: 2021-03-19)
Обработано offset 6500, собрано 6600 постов (последний: 2021-02-15)
Обработано offset 6600, собрано 6700 постов (последний: 2021-01-04)
Обработано offset 6700, собрано 6800 постов (последний: 2020-12-10)
Обработано offset 6800, собрано 6900 постов (последний: 2020-11-16)
Обработано offset 6900, собрано 7000 постов (последний: 2020-10-06)
Обработано offset 7000, собрано 7100 постов (последний: 2020-08-26)
Обработано offset 7100, собрано 7200 постов (последний: 2020-07-01)
Обработано offset 7200, собрано 7300 постов (последний: 2020-05-27)
Обработано offset 7300, собрано 7400 постов (последний: 2020-04-29)
Обработано offset 7400, собрано 7500 постов (последний: 2020-04-08)
Обработано offset 7500, собрано 7600 постов (последний: 2020-03-19)
Обработано offset 7600, собрано 7700 постов (последний: 2020-02-20)
Обработано offset 7700, собрано 7800 постов (последний: 2020-01-08)

- Достигли 2019 года -
Последний пост: 20931 от 2019-12-31
Всего собрано постов: 7807
Диапазон дат: 2020-01-03 - 2026-05-05

In [ ]:
# финашка
group_id = '-6319'
name = 'fa.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-08)
Обработано offset 100, собрано 200 постов (последний: 2026-03-13)
Обработано offset 200, собрано 300 постов (последний: 2026-02-12)
Обработано offset 300, собрано 400 постов (последний: 2026-01-02)
Обработано offset 400, собрано 500 постов (последний: 2025-12-08)
Обработано offset 500, собрано 600 постов (последний: 2025-11-13)
Обработано offset 600, собрано 700 постов (последний: 2025-10-16)
Обработано offset 700, собрано 800 постов (последний: 2025-09-18)
Обработано offset 800, собрано 900 постов (последний: 2025-08-25)
Обработано offset 900, собрано 1000 постов (последний: 2025-07-14)
Обработано offset 1000, собрано 1100 постов (последний: 2025-06-04)
Обработано offset 1100, собрано 1200 постов (последний: 2025-04-28)
Обработано offset 1200, собрано 1300 постов (последний: 2025-03-29)
Обработано offset 1300, собрано 1400 постов (последний: 2025-02-23)
Обработано offset 1400, собрано 1500 постов (последний: 2025-01-24)
Обработано offset 1500, собрано 1600 постов (последний: 2024-11-19)
Обработано offset 1600, собрано 1700 постов (последний: 2024-10-15)
Обработано offset 1700, собрано 1800 постов (последний: 2024-09-11)
Обработано offset 1800, собрано 1900 постов (последний: 2024-07-31)
Обработано offset 1900, собрано 2000 постов (последний: 2024-06-25)
Обработано offset 2000, собрано 2100 постов (последний: 2024-05-22)
Обработано offset 2100, собрано 2200 постов (последний: 2024-04-15)
Обработано offset 2200, собрано 2300 постов (последний: 2024-03-13)
Обработано offset 2300, собрано 2400 постов (последний: 2024-02-07)
Обработано offset 2400, собрано 2500 постов (последний: 2023-12-26)
Обработано offset 2500, собрано 2600 постов (последний: 2023-11-24)
Обработано offset 2600, собрано 2700 постов (последний: 2023-10-23)
Обработано offset 2700, собрано 2800 постов (последний: 2023-09-21)
Обработано offset 2800, собрано 2900 постов (последний: 2023-08-21)
Обработано offset 2900, собрано 3000 постов (последний: 2023-07-17)
Обработано offset 3000, собрано 3100 постов (последний: 2023-06-14)
Обработано offset 3100, собрано 3200 постов (последний: 2023-05-10)
Обработано offset 3200, собрано 3300 постов (последний: 2023-04-11)
Обработано offset 3300, собрано 3400 постов (последний: 2023-03-14)
Обработано offset 3400, собрано 3500 постов (последний: 2023-02-09)
Обработано offset 3500, собрано 3600 постов (последний: 2023-01-06)
Обработано offset 3600, собрано 3700 постов (последний: 2022-12-05)
Обработано offset 3700, собрано 3800 постов (последний: 2022-11-08)
Обработано offset 3800, собрано 3900 постов (последний: 2022-10-10)
Обработано offset 3900, собрано 4000 постов (последний: 2022-09-08)
Обработано offset 4000, собрано 4100 постов (последний: 2022-08-08)
Обработано offset 4100, собрано 4200 постов (последний: 2022-07-06)
Обработано offset 4200, собрано 4300 постов (последний: 2022-06-09)
Обработано offset 4300, собрано 4400 постов (последний: 2022-05-16)
Обработано offset 4400, собрано 4500 постов (последний: 2022-04-18)
Обработано offset 4500, собрано 4600 постов (последний: 2022-03-21)
Обработано offset 4600, собрано 4700 постов (последний: 2022-02-12)
Обработано offset 4700, собрано 4800 постов (последний: 2022-01-02)
Обработано offset 4800, собрано 4900 постов (последний: 2021-11-26)
Обработано offset 4900, собрано 5000 постов (последний: 2021-10-13)
Обработано offset 5000, собрано 5100 постов (последний: 2021-09-02)
Обработано offset 5100, собрано 5200 постов (последний: 2021-07-21)
Обработано offset 5200, собрано 5300 постов (последний: 2021-06-15)
Обработано offset 5300, собрано 5400 постов (последний: 2021-05-11)
Обработано offset 5400, собрано 5500 постов (последний: 2021-04-06)
Обработано offset 5500, собрано 5600 постов (последний: 2021-03-02)
Обработано offset 5600, собрано 5700 постов (последний: 2021-02-02)
Обработано offset 5700, собрано 5800 постов (последний: 2020-12-16)
Обработано offset 5800, собрано 5900 постов (последний: 2020-11-05)
Обработано offset 5900, собрано 6000 постов (последний: 2020-09-22)
Обработано offset 6000, собрано 6100 постов (последний: 2020-07-29)
Обработано offset 6100, собрано 6200 постов (последний: 2020-06-08)
Обработано offset 6200, собрано 6300 постов (последний: 2020-04-27)
Обработано offset 6300, собрано 6400 постов (последний: 2020-03-19)
Обработано offset 6400, собрано 6500 постов (последний: 2020-01-29)

- Достигли 2019 года -
Последний пост: 25610 от 2019-12-31
Всего собрано постов: 6542
Диапазон дат: 2020-01-02 - 2026-05-06

In [ ]:
# мифи
group_id = '-69589815'
name = 'mephi.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-18)
Обработано offset 100, собрано 200 постов (последний: 2026-04-04)
Обработано offset 200, собрано 300 постов (последний: 2026-03-19)
Обработано offset 300, собрано 400 постов (последний: 2026-02-28)
Обработано offset 400, собрано 500 постов (последний: 2026-02-10)
Обработано offset 500, собрано 600 постов (последний: 2026-01-18)
Обработано offset 600, собрано 700 постов (последний: 2025-12-17)
Обработано offset 700, собрано 800 постов (последний: 2025-11-27)
Обработано offset 800, собрано 900 постов (последний: 2025-11-08)
Обработано offset 900, собрано 1000 постов (последний: 2025-10-15)
Обработано offset 1000, собрано 1100 постов (последний: 2025-09-26)
Обработано offset 1100, собрано 1200 постов (последний: 2025-09-08)
Обработано offset 1200, собрано 1300 постов (последний: 2025-08-20)
Обработано offset 1300, собрано 1400 постов (последний: 2025-07-24)
Обработано offset 1400, собрано 1500 постов (последний: 2025-07-08)
Обработано offset 1500, собрано 1600 постов (последний: 2025-06-18)
Обработано offset 1600, собрано 1700 постов (последний: 2025-05-23)
Обработано offset 1700, собрано 1800 постов (последний: 2025-04-30)
Обработано offset 1800, собрано 1900 постов (последний: 2025-04-13)
Обработано offset 1900, собрано 2000 постов (последний: 2025-03-26)
Обработано offset 2000, собрано 2100 постов (последний: 2025-03-06)
Обработано offset 2100, собрано 2200 постов (последний: 2025-02-17)
Обработано offset 2200, собрано 2300 постов (последний: 2025-02-03)
Обработано offset 2300, собрано 2400 постов (последний: 2025-01-16)
Обработано offset 2400, собрано 2500 постов (последний: 2024-12-20)
Обработано offset 2500, собрано 2600 постов (последний: 2024-11-30)
Обработано offset 2600, собрано 2700 постов (последний: 2024-11-16)
Обработано offset 2700, собрано 2800 постов (последний: 2024-10-22)
Обработано offset 2800, собрано 2900 постов (последний: 2024-10-03)
Обработано offset 2900, собрано 3000 постов (последний: 2024-09-17)
Обработано offset 3000, собрано 3100 постов (последний: 2024-08-30)
Обработано offset 3100, собрано 3200 постов (последний: 2024-08-06)
Обработано offset 3200, собрано 3300 постов (последний: 2024-07-15)
Обработано offset 3300, собрано 3400 постов (последний: 2024-07-01)
Обработано offset 3400, собрано 3500 постов (последний: 2024-06-18)
Обработано offset 3500, собрано 3600 постов (последний: 2024-05-28)
Обработано offset 3600, собрано 3700 постов (последний: 2024-05-08)
Обработано offset 3700, собрано 3800 постов (последний: 2024-04-18)
Обработано offset 3800, собрано 3900 постов (последний: 2024-03-30)
Обработано offset 3900, собрано 4000 постов (последний: 2024-03-09)
Обработано offset 4000, собрано 4100 постов (последний: 2024-02-12)
Обработано offset 4100, собрано 4200 постов (последний: 2024-01-20)
Обработано offset 4200, собрано 4300 постов (последний: 2023-12-14)
Обработано offset 4300, собрано 4400 постов (последний: 2023-11-21)
Обработано offset 4400, собрано 4500 постов (последний: 2023-10-26)
Обработано offset 4500, собрано 4600 постов (последний: 2023-10-06)
Обработано offset 4600, собрано 4700 постов (последний: 2023-09-19)
Обработано offset 4700, собрано 4800 постов (последний: 2023-08-30)
Обработано offset 4800, собрано 4900 постов (последний: 2023-08-08)
Обработано offset 4900, собрано 5000 постов (последний: 2023-07-13)
Обработано offset 5000, собрано 5100 постов (последний: 2023-06-17)
Обработано offset 5100, собрано 5200 постов (последний: 2023-05-26)
Обработано offset 5200, собрано 5300 постов (последний: 2023-05-03)
Обработано offset 5300, собрано 5400 постов (последний: 2023-04-13)
Обработано offset 5400, собрано 5500 постов (последний: 2023-03-26)
Обработано offset 5500, собрано 5600 постов (последний: 2023-03-06)
Обработано offset 5600, собрано 5700 постов (последний: 2023-02-09)
Обработано offset 5700, собрано 5800 постов (последний: 2023-01-15)
Обработано offset 5800, собрано 5900 постов (последний: 2022-12-14)
Обработано offset 5900, собрано 6000 постов (последний: 2022-11-21)
Обработано offset 6000, собрано 6100 постов (последний: 2022-10-26)
Обработано offset 6100, собрано 6200 постов (последний: 2022-09-29)
Обработано offset 6200, собрано 6300 постов (последний: 2022-09-02)
Обработано offset 6300, собрано 6400 постов (последний: 2022-08-05)
Обработано offset 6400, собрано 6500 постов (последний: 2022-07-18)
Обработано offset 6500, собрано 6600 постов (последний: 2022-07-01)
Обработано offset 6600, собрано 6700 постов (последний: 2022-06-09)
Обработано offset 6700, собрано 6800 постов (последний: 2022-05-19)
Обработано offset 6800, собрано 6900 постов (последний: 2022-04-22)
Обработано offset 6900, собрано 7000 постов (последний: 2022-03-20)
Обработано offset 7000, собрано 7100 постов (последний: 2022-02-12)
Обработано offset 7100, собрано 7200 постов (последний: 2021-12-30)
Обработано offset 7200, собрано 7300 постов (последний: 2021-11-29)
Обработано offset 7300, собрано 7400 постов (последний: 2021-11-01)
Обработано offset 7400, собрано 7500 постов (последний: 2021-10-05)
Обработано offset 7500, собрано 7600 постов (последний: 2021-09-06)
Обработано offset 7600, собрано 7700 постов (последний: 2021-08-01)
Обработано offset 7700, собрано 7800 постов (последний: 2021-07-05)
Обработано offset 7800, собрано 7900 постов (последний: 2021-06-04)
Обработано offset 7900, собрано 8000 постов (последний: 2021-04-22)
Обработано offset 8000, собрано 8100 постов (последний: 2021-03-11)
Обработано offset 8100, собрано 8200 постов (последний: 2021-01-20)
Обработано offset 8200, собрано 8300 постов (последний: 2020-12-01)
Обработано offset 8300, собрано 8400 постов (последний: 2020-10-30)
Обработано offset 8400, собрано 8500 постов (последний: 2020-09-21)
Обработано offset 8500, собрано 8600 постов (последний: 2020-08-09)
Обработано offset 8600, собрано 8700 постов (последний: 2020-07-03)
Обработано offset 8700, собрано 8800 постов (последний: 2020-06-10)
Обработано offset 8800, собрано 8900 постов (последний: 2020-05-25)
Обработано offset 8900, собрано 9000 постов (последний: 2020-05-06)
Обработано offset 9000, собрано 9100 постов (последний: 2020-04-15)
Обработано offset 9100, собрано 9200 постов (последний: 2020-03-15)
Обработано offset 9200, собрано 9300 постов (последний: 2020-02-05)

- Достигли 2019 года -
Последний пост: 13479 от 2019-12-31
Всего собрано постов: 9370
Диапазон дат: 2020-01-01 - 2026-05-06

In [ ]:
# кутафина
group_id = '-65417'
name = 'kutafina.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-17)
Обработано offset 100, собрано 200 постов (последний: 2026-03-30)
Обработано offset 200, собрано 300 постов (последний: 2026-03-12)
Обработано offset 300, собрано 400 постов (последний: 2026-02-24)
Обработано offset 400, собрано 500 постов (последний: 2026-02-08)
Обработано offset 500, собрано 600 постов (последний: 2026-01-19)
Обработано offset 600, собрано 700 постов (последний: 2025-12-26)
Обработано offset 700, собрано 800 постов (последний: 2025-12-07)
Обработано offset 800, собрано 900 постов (последний: 2025-11-19)
Обработано offset 900, собрано 1000 постов (последний: 2025-10-26)
Обработано offset 1000, собрано 1100 постов (последний: 2025-10-01)
Обработано offset 1100, собрано 1200 постов (последний: 2025-09-12)
Обработано offset 1200, собрано 1300 постов (последний: 2025-08-27)
Обработано offset 1300, собрано 1400 постов (последний: 2025-07-30)
Обработано offset 1400, собрано 1500 постов (последний: 2025-07-05)
Обработано offset 1500, собрано 1600 постов (последний: 2025-06-16)
Обработано offset 1600, собрано 1700 постов (последний: 2025-05-26)
Обработано offset 1700, собрано 1800 постов (последний: 2025-05-12)
Обработано offset 1800, собрано 1900 постов (последний: 2025-04-25)
Обработано offset 1900, собрано 2000 постов (последний: 2025-04-09)
Обработано offset 2000, собрано 2100 постов (последний: 2025-03-18)
Обработано offset 2100, собрано 2200 постов (последний: 2025-02-21)
Обработано offset 2200, собрано 2300 постов (последний: 2025-01-27)
Обработано offset 2300, собрано 2400 постов (последний: 2024-12-24)
Обработано offset 2400, собрано 2500 постов (последний: 2024-11-27)
Обработано offset 2500, собрано 2600 постов (последний: 2024-10-30)
Обработано offset 2600, собрано 2700 постов (последний: 2024-10-02)
Обработано offset 2700, собрано 2800 постов (последний: 2024-09-07)
Обработано offset 2800, собрано 2900 постов (последний: 2024-08-16)
Обработано offset 2900, собрано 3000 постов (последний: 2024-07-16)
Обработано offset 3000, собрано 3100 постов (последний: 2024-06-24)
Обработано offset 3100, собрано 3200 постов (последний: 2024-05-29)
Обработано offset 3200, собрано 3300 постов (последний: 2024-05-06)
Обработано offset 3300, собрано 3400 постов (последний: 2024-04-13)
Обработано offset 3400, собрано 3500 постов (последний: 2024-03-16)
Обработано offset 3500, собрано 3600 постов (последний: 2024-02-18)
Обработано offset 3600, собрано 3700 постов (последний: 2024-01-23)
Обработано offset 3700, собрано 3800 постов (последний: 2023-12-18)
Обработано offset 3800, собрано 3900 постов (последний: 2023-11-24)
Обработано offset 3900, собрано 4000 постов (последний: 2023-10-28)
Обработано offset 4000, собрано 4100 постов (последний: 2023-09-29)
Обработано offset 4100, собрано 4200 постов (последний: 2023-09-01)
Обработано offset 4200, собрано 4300 постов (последний: 2023-07-28)
Обработано offset 4300, собрано 4400 постов (последний: 2023-06-21)
Обработано offset 4400, собрано 4500 постов (последний: 2023-05-12)
Обработано offset 4500, собрано 4600 постов (последний: 2023-03-24)
Обработано offset 4600, собрано 4700 постов (последний: 2022-11-09)
Обработано offset 4700, собрано 4800 постов (последний: 2022-07-14)
Обработано offset 4800, собрано 4900 постов (последний: 2022-04-15)
Обработано offset 4900, собрано 5000 постов (последний: 2021-11-23)
Обработано offset 5000, собрано 5100 постов (последний: 2021-07-01)
Обработано offset 5100, собрано 5200 постов (последний: 2021-04-10)
Обработано offset 5200, собрано 5300 постов (последний: 2021-02-01)
Обработано offset 5300, собрано 5400 постов (последний: 2020-11-04)
Обработано offset 5400, собрано 5500 постов (последний: 2020-09-21)
Обработано offset 5500, собрано 5600 постов (последний: 2020-06-11)
Обработано offset 5600, собрано 5700 постов (последний: 2020-04-16)
Обработано offset 5700, собрано 5800 постов (последний: 2020-01-14)

- Достигли 2019 года -
Последний пост: 4341 от 2019-12-31
Всего собрано постов: 5804
Диапазон дат: 2020-01-02 - 2026-05-06

In [ ]:
# Гитис
group_id = '-145886776'
name = 'gitis.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-15)
Обработано offset 100, собрано 200 постов (последний: 2026-03-19)
Обработано offset 200, собрано 300 постов (последний: 2026-02-18)
Обработано offset 300, собрано 400 постов (последний: 2026-01-19)
Обработано offset 400, собрано 500 постов (последний: 2025-12-11)
Обработано offset 500, собрано 600 постов (последний: 2025-11-14)
Обработано offset 600, собрано 700 постов (последний: 2025-10-13)
Обработано offset 700, собрано 800 постов (последний: 2025-09-09)
Обработано offset 800, собрано 900 постов (последний: 2025-07-18)
Обработано offset 900, собрано 1000 постов (последний: 2025-06-16)
Обработано offset 1000, собрано 1100 постов (последний: 2025-05-13)
Обработано offset 1100, собрано 1200 постов (последний: 2025-03-31)
Обработано offset 1200, собрано 1300 постов (последний: 2025-02-12)
Обработано offset 1300, собрано 1400 постов (последний: 2024-12-18)
Обработано offset 1400, собрано 1500 постов (последний: 2024-11-05)
Обработано offset 1500, собрано 1600 постов (последний: 2024-09-12)
Обработано offset 1600, собрано 1700 постов (последний: 2024-07-09)
Обработано offset 1700, собрано 1800 постов (последний: 2024-06-13)
Обработано offset 1800, собрано 1900 постов (последний: 2024-05-20)
Обработано offset 1900, собрано 2000 постов (последний: 2024-04-20)
Обработано offset 2000, собрано 2100 постов (последний: 2024-03-25)
Обработано offset 2100, собрано 2200 постов (последний: 2024-02-16)
Обработано offset 2200, собрано 2300 постов (последний: 2024-01-10)
Обработано offset 2300, собрано 2400 постов (последний: 2023-11-16)
Обработано offset 2400, собрано 2500 постов (последний: 2023-10-16)
Обработано offset 2500, собрано 2600 постов (последний: 2023-08-23)
Обработано offset 2600, собрано 2700 постов (последний: 2023-05-15)
Обработано offset 2700, собрано 2800 постов (последний: 2022-12-07)
Обработано offset 2800, собрано 2900 постов (последний: 2022-05-20)
Обработано offset 2900, собрано 3000 постов (последний: 2022-01-25)
Обработано offset 3000, собрано 3100 постов (последний: 2021-08-10)
Обработано offset 3100, собрано 3200 постов (последний: 2021-05-02)
Обработано offset 3200, собрано 3300 постов (последний: 2021-02-26)
Обработано offset 3300, собрано 3400 постов (последний: 2020-11-10)
Обработано offset 3400, собрано 3500 постов (последний: 2020-08-21)
Обработано offset 3500, собрано 3600 постов (последний: 2020-05-24)
Обработано offset 3600, собрано 3700 постов (последний: 2020-02-04)

- Достигли 2019 года -
Последний пост: 1630 от 2019-12-24
Всего собрано постов: 3710
Диапазон дат: 2020-01-01 - 2026-05-06

In [ ]:
# губкин
group_id = '-71938736'
name = 'gubkin.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-14)
Обработано offset 100, собрано 200 постов (последний: 2026-03-24)
Обработано offset 200, собрано 300 постов (последний: 2026-03-06)
Обработано offset 300, собрано 400 постов (последний: 2026-02-17)
Обработано offset 400, собрано 500 постов (последний: 2026-01-26)
Обработано offset 500, собрано 600 постов (последний: 2025-12-22)
Обработано offset 600, собрано 700 постов (последний: 2025-11-29)
Обработано offset 700, собрано 800 постов (последний: 2025-11-15)
Обработано offset 800, собрано 900 постов (последний: 2025-10-31)
Обработано offset 900, собрано 1000 постов (последний: 2025-10-09)
Обработано offset 1000, собрано 1100 постов (последний: 2025-09-13)
Обработано offset 1100, собрано 1200 постов (последний: 2025-08-14)
Обработано offset 1200, собрано 1300 постов (последний: 2025-07-09)
Обработано offset 1300, собрано 1400 постов (последний: 2025-06-05)
Обработано offset 1400, собрано 1500 постов (последний: 2025-05-12)
Обработано offset 1500, собрано 1600 постов (последний: 2025-04-22)
Обработано offset 1600, собрано 1700 постов (последний: 2025-04-04)
Обработано offset 1700, собрано 1800 постов (последний: 2025-03-07)
Обработано offset 1800, собрано 1900 постов (последний: 2025-02-17)
Обработано offset 1900, собрано 2000 постов (последний: 2025-01-16)
Обработано offset 2000, собрано 2100 постов (последний: 2024-12-06)
Обработано offset 2100, собрано 2200 постов (последний: 2024-11-15)
Обработано offset 2200, собрано 2300 постов (последний: 2024-10-24)
Обработано offset 2300, собрано 2400 постов (последний: 2024-09-26)
Обработано offset 2400, собрано 2500 постов (последний: 2024-09-01)
Обработано offset 2500, собрано 2600 постов (последний: 2024-07-19)
Обработано offset 2600, собрано 2700 постов (последний: 2024-06-17)
Обработано offset 2700, собрано 2800 постов (последний: 2024-05-16)
Обработано offset 2800, собрано 2900 постов (последний: 2024-04-19)
Обработано offset 2900, собрано 3000 постов (последний: 2024-03-23)
Обработано offset 3000, собрано 3100 постов (последний: 2024-02-09)
Обработано offset 3100, собрано 3200 постов (последний: 2023-12-07)
Обработано offset 3200, собрано 3300 постов (последний: 2023-10-31)
Обработано offset 3300, собрано 3400 постов (последний: 2023-09-22)
Обработано offset 3400, собрано 3500 постов (последний: 2023-07-12)
Обработано offset 3500, собрано 3600 постов (последний: 2023-05-26)
Обработано offset 3600, собрано 3700 постов (последний: 2023-04-06)
Обработано offset 3700, собрано 3800 постов (последний: 2023-03-01)
Обработано offset 3800, собрано 3900 постов (последний: 2022-12-30)
Обработано offset 3900, собрано 4000 постов (последний: 2022-11-21)
Обработано offset 4000, собрано 4100 постов (последний: 2022-10-27)
Обработано offset 4100, собрано 4200 постов (последний: 2022-09-29)
Обработано offset 4200, собрано 4300 постов (последний: 2022-08-18)
Обработано offset 4300, собрано 4400 постов (последний: 2022-05-30)
Обработано offset 4400, собрано 4500 постов (последний: 2022-04-27)
Обработано offset 4500, собрано 4600 постов (последний: 2022-03-31)
Обработано offset 4600, собрано 4700 постов (последний: 2022-02-24)
Обработано offset 4700, собрано 4800 постов (последний: 2021-12-16)
Обработано offset 4800, собрано 4900 постов (последний: 2021-11-11)
Обработано offset 4900, собрано 5000 постов (последний: 2021-09-24)
Обработано offset 5000, собрано 5100 постов (последний: 2021-06-03)
Обработано offset 5100, собрано 5200 постов (последний: 2021-03-23)
Обработано offset 5200, собрано 5300 постов (последний: 2020-10-29)
Обработано offset 5300, собрано 5400 постов (последний: 2020-05-01)

- Достигли 2019 года -
Последний пост: 6326 от 2019-12-31
Всего собрано постов: 5472
Диапазон дат: 2020-01-08 - 2026-05-06

In [ ]:
# рниму
group_id = '-53765914'
name = 'rsmu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-03)
Обработано offset 100, собрано 200 постов (последний: 2026-03-08)
Обработано offset 200, собрано 300 постов (последний: 2026-02-03)
Обработано offset 300, собрано 400 постов (последний: 2025-12-18)
Обработано offset 400, собрано 500 постов (последний: 2025-11-25)
Обработано offset 500, собрано 600 постов (последний: 2025-11-05)
Обработано offset 600, собрано 700 постов (последний: 2025-10-13)
Обработано offset 700, собрано 800 постов (последний: 2025-09-17)
Обработано offset 800, собрано 900 постов (последний: 2025-08-14)
Обработано offset 900, собрано 1000 постов (последний: 2025-07-17)
Обработано offset 1000, собрано 1100 постов (последний: 2025-06-20)
Обработано offset 1100, собрано 1200 постов (последний: 2025-05-26)
Обработано offset 1200, собрано 1300 постов (последний: 2025-05-03)
Обработано offset 1300, собрано 1400 постов (последний: 2025-04-05)
Обработано offset 1400, собрано 1500 постов (последний: 2025-03-13)
Обработано offset 1500, собрано 1600 постов (последний: 2025-02-13)
Обработано offset 1600, собрано 1700 постов (последний: 2025-01-09)
Обработано offset 1700, собрано 1800 постов (последний: 2024-12-11)
Обработано offset 1800, собрано 1900 постов (последний: 2024-11-22)
Обработано offset 1900, собрано 2000 постов (последний: 2024-10-25)
Обработано offset 2000, собрано 2100 постов (последний: 2024-10-01)
Обработано offset 2100, собрано 2200 постов (последний: 2024-09-04)
Обработано offset 2200, собрано 2300 постов (последний: 2024-07-31)
Обработано offset 2300, собрано 2400 постов (последний: 2024-07-01)
Обработано offset 2400, собрано 2500 постов (последний: 2024-06-06)
Обработано offset 2500, собрано 2600 постов (последний: 2024-05-02)
Обработано offset 2600, собрано 2700 постов (последний: 2024-04-09)
Обработано offset 2700, собрано 2800 постов (последний: 2024-02-28)
Обработано offset 2800, собрано 2900 постов (последний: 2024-01-17)
Обработано offset 2900, собрано 3000 постов (последний: 2023-11-14)
Обработано offset 3000, собрано 3100 постов (последний: 2023-10-05)
Обработано offset 3100, собрано 3200 постов (последний: 2023-08-11)
Обработано offset 3200, собрано 3300 постов (последний: 2023-06-19)
Обработано offset 3300, собрано 3400 постов (последний: 2023-04-22)
Обработано offset 3400, собрано 3500 постов (последний: 2023-03-06)
Обработано offset 3500, собрано 3600 постов (последний: 2022-12-28)
Обработано offset 3600, собрано 3700 постов (последний: 2022-11-09)
Обработано offset 3700, собрано 3800 постов (последний: 2022-09-14)
Обработано offset 3800, собрано 3900 постов (последний: 2022-06-22)
Обработано offset 3900, собрано 4000 постов (последний: 2022-04-26)
Обработано offset 4000, собрано 4100 постов (последний: 2022-03-04)
Обработано offset 4100, собрано 4200 постов (последний: 2021-12-23)
Обработано offset 4200, собрано 4300 постов (последний: 2021-10-19)
Обработано offset 4300, собрано 4400 постов (последний: 2021-08-06)
Обработано offset 4400, собрано 4500 постов (последний: 2021-05-22)
Обработано offset 4500, собрано 4600 постов (последний: 2021-03-19)
Обработано offset 4600, собрано 4700 постов (последний: 2020-12-08)
Обработано offset 4700, собрано 4800 постов (последний: 2020-10-01)
Обработано offset 4800, собрано 4900 постов (последний: 2020-07-29)
Обработано offset 4900, собрано 5000 постов (последний: 2020-06-03)
Обработано offset 5000, собрано 5100 постов (последний: 2020-03-27)
Обработано offset 5100, собрано 5200 постов (последний: 2020-01-24)

- Достигли 2019 года -
Последний пост: 6492 от 2019-12-31
Всего собрано постов: 5209
Диапазон дат: 2020-01-05 - 2026-05-06

In [ ]:
# мэи
group_id = '-51345945'
name = 'mpei.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-14)
Обработано offset 100, собрано 200 постов (последний: 2026-03-18)
Обработано offset 200, собрано 300 постов (последний: 2026-02-17)
Обработано offset 300, собрано 400 постов (последний: 2026-01-12)
Обработано offset 400, собрано 500 постов (последний: 2025-12-01)
Обработано offset 500, собрано 600 постов (последний: 2025-11-03)
Обработано offset 600, собрано 700 постов (последний: 2025-10-09)
Обработано offset 700, собрано 800 постов (последний: 2025-09-16)
Обработано offset 800, собрано 900 постов (последний: 2025-08-25)
Обработано offset 900, собрано 1000 постов (последний: 2025-07-31)
Обработано offset 1000, собрано 1100 постов (последний: 2025-07-08)
Обработано offset 1100, собрано 1200 постов (последний: 2025-06-10)
Обработано offset 1200, собрано 1300 постов (последний: 2025-05-16)
Обработано offset 1300, собрано 1400 постов (последний: 2025-04-22)
Обработано offset 1400, собрано 1500 постов (последний: 2025-03-31)
Обработано offset 1500, собрано 1600 постов (последний: 2025-03-08)
Обработано offset 1600, собрано 1700 постов (последний: 2025-02-12)
Обработано offset 1700, собрано 1800 постов (последний: 2025-01-15)
Обработано offset 1800, собрано 1900 постов (последний: 2024-12-11)
Обработано offset 1900, собрано 2000 постов (последний: 2024-11-19)
Обработано offset 2000, собрано 2100 постов (последний: 2024-10-30)
Обработано offset 2100, собрано 2200 постов (последний: 2024-10-07)
Обработано offset 2200, собрано 2300 постов (последний: 2024-09-17)
Обработано offset 2300, собрано 2400 постов (последний: 2024-08-24)
Обработано offset 2400, собрано 2500 постов (последний: 2024-07-25)
Обработано offset 2500, собрано 2600 постов (последний: 2024-06-27)
Обработано offset 2600, собрано 2700 постов (последний: 2024-05-29)
Обработано offset 2700, собрано 2800 постов (последний: 2024-05-06)
Обработано offset 2800, собрано 2900 постов (последний: 2024-04-11)
Обработано offset 2900, собрано 3000 постов (последний: 2024-03-11)
Обработано offset 3000, собрано 3100 постов (последний: 2024-02-06)
Обработано offset 3100, собрано 3200 постов (последний: 2023-12-18)
Обработано offset 3200, собрано 3300 постов (последний: 2023-11-21)
Обработано offset 3300, собрано 3400 постов (последний: 2023-10-25)
Обработано offset 3400, собрано 3500 постов (последний: 2023-09-26)
Обработано offset 3500, собрано 3600 постов (последний: 2023-08-22)
Обработано offset 3600, собрано 3700 постов (последний: 2023-07-12)
Обработано offset 3700, собрано 3800 постов (последний: 2023-06-07)
Обработано offset 3800, собрано 3900 постов (последний: 2023-05-11)
Обработано offset 3900, собрано 4000 постов (последний: 2023-04-14)
Обработано offset 4000, собрано 4100 постов (последний: 2023-03-22)
Обработано offset 4100, собрано 4200 постов (последний: 2023-02-21)
Обработано offset 4200, собрано 4300 постов (последний: 2023-01-17)
Обработано offset 4300, собрано 4400 постов (последний: 2022-12-05)
Обработано offset 4400, собрано 4500 постов (последний: 2022-11-14)
Обработано offset 4500, собрано 4600 постов (последний: 2022-10-24)
Обработано offset 4600, собрано 4700 постов (последний: 2022-09-30)
Обработано offset 4700, собрано 4800 постов (последний: 2022-08-17)
Обработано offset 4800, собрано 4900 постов (последний: 2022-05-30)
Обработано offset 4900, собрано 5000 постов (последний: 2022-04-05)
Обработано offset 5000, собрано 5100 постов (последний: 2022-02-08)
Обработано offset 5100, собрано 5200 постов (последний: 2021-11-24)
Обработано offset 5200, собрано 5300 постов (последний: 2021-09-08)
Обработано offset 5300, собрано 5400 постов (последний: 2021-05-18)
Обработано offset 5400, собрано 5500 постов (последний: 2021-01-11)
Обработано offset 5500, собрано 5600 постов (последний: 2020-09-01)

- Достигли 2019 года -
Последний пост: 3766 от 2019-12-23
Всего собрано постов: 5671
Диапазон дат: 2020-01-09 - 2026-05-06

In [ ]:
# мпгу
group_id = '-30321356'
name = 'mpgu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-22)
Обработано offset 100, собрано 200 постов (последний: 2026-04-09)
Обработано offset 200, собрано 300 постов (последний: 2026-03-28)
Обработано offset 300, собрано 400 постов (последний: 2026-03-17)
Обработано offset 400, собрано 500 постов (последний: 2026-03-05)
Обработано offset 500, собрано 600 постов (последний: 2026-02-20)
Обработано offset 600, собрано 700 постов (последний: 2026-02-06)
Обработано offset 700, собрано 800 постов (последний: 2026-01-25)
Обработано offset 800, собрано 900 постов (последний: 2026-01-08)
Обработано offset 900, собрано 1000 постов (последний: 2025-12-22)
Обработано offset 1000, собрано 1100 постов (последний: 2025-12-11)
Обработано offset 1100, собрано 1200 постов (последний: 2025-11-28)
Обработано offset 1200, собрано 1300 постов (последний: 2025-11-16)
Обработано offset 1300, собрано 1400 постов (последний: 2025-11-02)
Обработано offset 1400, собрано 1500 постов (последний: 2025-10-21)
Обработано offset 1500, собрано 1600 постов (последний: 2025-10-08)
Обработано offset 1600, собрано 1700 постов (последний: 2025-09-26)
Обработано offset 1700, собрано 1800 постов (последний: 2025-09-10)
Обработано offset 1800, собрано 1900 постов (последний: 2025-08-26)
Обработано offset 1900, собрано 2000 постов (последний: 2025-08-07)
Обработано offset 2000, собрано 2100 постов (последний: 2025-07-20)
Обработано offset 2100, собрано 2200 постов (последний: 2025-07-02)
Обработано offset 2200, собрано 2300 постов (последний: 2025-06-17)
Обработано offset 2300, собрано 2400 постов (последний: 2025-06-03)
Обработано offset 2400, собрано 2500 постов (последний: 2025-05-17)
Обработано offset 2500, собрано 2600 постов (последний: 2025-05-02)
Обработано offset 2600, собрано 2700 постов (последний: 2025-04-16)
Обработано offset 2700, собрано 2800 постов (последний: 2025-03-28)
Обработано offset 2800, собрано 2900 постов (последний: 2025-03-08)
Обработано offset 2900, собрано 3000 постов (последний: 2025-02-19)
Обработано offset 3000, собрано 3100 постов (последний: 2025-02-03)
Обработано offset 3100, собрано 3200 постов (последний: 2025-01-09)
Обработано offset 3200, собрано 3300 постов (последний: 2024-12-19)
Обработано offset 3300, собрано 3400 постов (последний: 2024-12-06)
Обработано offset 3400, собрано 3500 постов (последний: 2024-11-20)
Обработано offset 3500, собрано 3600 постов (последний: 2024-10-31)
Обработано offset 3600, собрано 3700 постов (последний: 2024-10-14)
Обработано offset 3700, собрано 3800 постов (последний: 2024-09-25)
Обработано offset 3800, собрано 3900 постов (последний: 2024-09-06)
Обработано offset 3900, собрано 4000 постов (последний: 2024-08-16)
Обработано offset 4000, собрано 4100 постов (последний: 2024-07-08)
Обработано offset 4100, собрано 4200 постов (последний: 2024-05-21)
Обработано offset 4200, собрано 4300 постов (последний: 2024-03-21)
Обработано offset 4300, собрано 4400 постов (последний: 2024-02-05)
Обработано offset 4400, собрано 4500 постов (последний: 2023-12-16)
Обработано offset 4500, собрано 4600 постов (последний: 2023-10-30)
Обработано offset 4600, собрано 4700 постов (последний: 2023-09-23)
Обработано offset 4700, собрано 4800 постов (последний: 2023-06-23)
Обработано offset 4800, собрано 4900 постов (последний: 2023-03-07)
Обработано offset 4900, собрано 5000 постов (последний: 2022-11-22)
Обработано offset 5000, собрано 5100 постов (последний: 2022-09-25)
Обработано offset 5100, собрано 5200 постов (последний: 2022-07-29)
Обработано offset 5200, собрано 5300 постов (последний: 2022-06-09)
Обработано offset 5300, собрано 5400 постов (последний: 2022-01-26)
Обработано offset 5400, собрано 5500 постов (последний: 2021-08-31)
Обработано offset 5500, собрано 5600 постов (последний: 2021-05-17)
Обработано offset 5600, собрано 5700 постов (последний: 2021-04-07)
Обработано offset 5700, собрано 5800 постов (последний: 2021-03-01)
Обработано offset 5800, собрано 5900 постов (последний: 2021-01-26)
Обработано offset 5900, собрано 6000 постов (последний: 2020-12-07)
Обработано offset 6000, собрано 6100 постов (последний: 2020-11-05)
Обработано offset 6100, собрано 6200 постов (последний: 2020-10-02)
Обработано offset 6200, собрано 6300 постов (последний: 2020-08-24)
Обработано offset 6300, собрано 6400 постов (последний: 2020-06-23)
Обработано offset 6400, собрано 6500 постов (последний: 2020-05-18)
Обработано offset 6500, собрано 6600 постов (последний: 2020-04-24)
Обработано offset 6600, собрано 6700 постов (последний: 2020-03-26)
Обработано offset 6700, собрано 6800 постов (последний: 2020-02-06)

- Достигли 2019 года -
Последний пост: 70710 от 2019-12-31
Всего собрано постов: 6891
Диапазон дат: 2020-01-09 - 2026-05-06

In [ ]:
# вгик
group_id = '-199859404'
name = 'vgik.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-22)
Обработано offset 100, собрано 200 постов (последний: 2026-04-10)
Обработано offset 200, собрано 300 постов (последний: 2026-03-27)
Обработано offset 300, собрано 400 постов (последний: 2026-03-15)
Обработано offset 400, собрано 500 постов (последний: 2026-02-26)
Обработано offset 500, собрано 600 постов (последний: 2026-02-10)
Обработано offset 600, собрано 700 постов (последний: 2026-01-26)
Обработано offset 700, собрано 800 постов (последний: 2025-12-29)
Обработано offset 800, собрано 900 постов (последний: 2025-12-05)
Обработано offset 900, собрано 1000 постов (последний: 2025-11-10)
Обработано offset 1000, собрано 1100 постов (последний: 2025-10-10)
Обработано offset 1100, собрано 1200 постов (последний: 2025-08-26)
Обработано offset 1200, собрано 1300 постов (последний: 2025-07-07)
Обработано offset 1300, собрано 1400 постов (последний: 2025-05-16)
Обработано offset 1400, собрано 1500 постов (последний: 2025-03-25)
Обработано offset 1500, собрано 1600 постов (последний: 2025-02-10)
Обработано offset 1600, собрано 1700 постов (последний: 2024-12-25)
Обработано offset 1700, собрано 1800 постов (последний: 2024-10-26)
Обработано offset 1800, собрано 1900 постов (последний: 2024-07-31)
Обработано offset 1900, собрано 2000 постов (последний: 2024-04-23)
Обработано offset 2000, собрано 2100 постов (последний: 2024-03-20)
Обработано offset 2100, собрано 2200 постов (последний: 2024-02-26)
Обработано offset 2200, собрано 2300 постов (последний: 2023-12-25)
Обработано offset 2300, собрано 2400 постов (последний: 2022-11-21)
Обработано offset 2400, собрано 2500 постов (последний: 2021-12-06)
Обработано offset 2500, собрано 2600 постов (последний: 2021-01-02)
Обработано offset 2600, собрано 2622 постов (последний: 2020-10-30)
Постов больше нет
Всего собрано постов: 2622
Диапазон дат: 2020-10-30 - 2026-05-06

In [ ]:
# мгпу
group_id = '-3983'
name = 'mgpu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-17)
Обработано offset 100, собрано 200 постов (последний: 2026-01-14)
Обработано offset 200, собрано 300 постов (последний: 2025-11-12)
Обработано offset 300, собрано 400 постов (последний: 2025-10-02)
Обработано offset 400, собрано 500 постов (последний: 2025-08-22)
Обработано offset 500, собрано 600 постов (последний: 2025-07-16)
Обработано offset 600, собрано 700 постов (последний: 2025-06-04)
Обработано offset 700, собрано 800 постов (последний: 2025-05-05)
Обработано offset 800, собрано 900 постов (последний: 2025-04-01)
Обработано offset 900, собрано 1000 постов (последний: 2025-02-21)
Обработано offset 1000, собрано 1100 постов (последний: 2025-01-16)
Обработано offset 1100, собрано 1200 постов (последний: 2024-12-04)
Обработано offset 1200, собрано 1300 постов (последний: 2024-10-28)
Обработано offset 1300, собрано 1400 постов (последний: 2024-09-18)
Обработано offset 1400, собрано 1500 постов (последний: 2024-08-08)
Обработано offset 1500, собрано 1600 постов (последний: 2024-06-28)
Обработано offset 1600, собрано 1700 постов (последний: 2024-05-15)
Обработано offset 1700, собрано 1800 постов (последний: 2024-03-28)
Обработано offset 1800, собрано 1900 постов (последний: 2024-02-13)
Обработано offset 1900, собрано 2000 постов (последний: 2023-12-14)
Обработано offset 2000, собрано 2100 постов (последний: 2023-11-02)
Обработано offset 2100, собрано 2200 постов (последний: 2023-09-21)
Обработано offset 2200, собрано 2300 постов (последний: 2023-07-12)
Обработано offset 2300, собрано 2400 постов (последний: 2023-05-01)
Обработано offset 2400, собрано 2500 постов (последний: 2023-02-06)
Обработано offset 2500, собрано 2600 постов (последний: 2022-11-18)
Обработано offset 2600, собрано 2700 постов (последний: 2022-09-09)
Обработано offset 2700, собрано 2800 постов (последний: 2022-07-13)
Обработано offset 2800, собрано 2900 постов (последний: 2022-05-24)
Обработано offset 2900, собрано 3000 постов (последний: 2022-03-31)
Обработано offset 3000, собрано 3100 постов (последний: 2021-12-22)
Обработано offset 3100, собрано 3200 постов (последний: 2021-09-23)
Обработано offset 3200, собрано 3300 постов (последний: 2021-05-20)
Обработано offset 3300, собрано 3400 постов (последний: 2021-01-28)
Обработано offset 3400, собрано 3500 постов (последний: 2020-11-10)
Обработано offset 3500, собрано 3600 постов (последний: 2020-08-23)
Обработано offset 3600, собрано 3700 постов (последний: 2020-06-28)
Обработано offset 3700, собрано 3800 постов (последний: 2020-04-24)
Обработано offset 3800, собрано 3900 постов (последний: 2020-03-12)
Обработано offset 3900, собрано 4000 постов (последний: 2020-01-04)

- Достигли 2019 года -
Последний пост: 28289 от 2019-12-31
Всего собрано постов: 4002
Диапазон дат: 2020-01-02 - 2026-05-06

In [ ]:
# рггу
group_id = '-16479782'
name = 'rggu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-04)
Обработано offset 100, собрано 200 постов (последний: 2026-03-03)
Обработано offset 200, собрано 300 постов (последний: 2025-12-12)
Обработано offset 300, собрано 400 постов (последний: 2025-11-20)
Обработано offset 400, собрано 500 постов (последний: 2025-10-21)
Обработано offset 500, собрано 600 постов (последний: 2025-09-22)
Обработано offset 600, собрано 700 постов (последний: 2025-08-21)
Обработано offset 700, собрано 800 постов (последний: 2025-07-20)
Обработано offset 800, собрано 900 постов (последний: 2025-06-26)
Обработано offset 900, собрано 1000 постов (последний: 2025-05-27)
Обработано offset 1000, собрано 1100 постов (последний: 2025-05-05)
Обработано offset 1100, собрано 1200 постов (последний: 2025-04-20)
Обработано offset 1200, собрано 1300 постов (последний: 2025-04-05)
Обработано offset 1300, собрано 1400 постов (последний: 2025-03-19)
Обработано offset 1400, собрано 1500 постов (последний: 2025-02-28)
Обработано offset 1500, собрано 1600 постов (последний: 2025-02-10)
Обработано offset 1600, собрано 1700 постов (последний: 2025-01-23)
Обработано offset 1700, собрано 1800 постов (последний: 2024-12-20)
Обработано offset 1800, собрано 1900 постов (последний: 2024-12-03)
Обработано offset 1900, собрано 2000 постов (последний: 2024-11-11)
Обработано offset 2000, собрано 2100 постов (последний: 2024-10-17)
Обработано offset 2100, собрано 2200 постов (последний: 2024-09-20)
Обработано offset 2200, собрано 2300 постов (последний: 2024-08-23)
Обработано offset 2300, собрано 2400 постов (последний: 2024-07-31)
Обработано offset 2400, собрано 2500 постов (последний: 2024-06-30)
Обработано offset 2500, собрано 2600 постов (последний: 2024-06-06)
Обработано offset 2600, собрано 2700 постов (последний: 2024-05-10)
Обработано offset 2700, собрано 2800 постов (последний: 2024-04-18)
Обработано offset 2800, собрано 2900 постов (последний: 2024-03-28)
Обработано offset 2900, собрано 3000 постов (последний: 2024-03-02)
Обработано offset 3000, собрано 3100 постов (последний: 2024-02-01)
Обработано offset 3100, собрано 3200 постов (последний: 2023-12-27)
Обработано offset 3200, собрано 3300 постов (последний: 2023-12-01)
Обработано offset 3300, собрано 3400 постов (последний: 2023-11-10)
Обработано offset 3400, собрано 3500 постов (последний: 2023-10-17)
Обработано offset 3500, собрано 3600 постов (последний: 2023-09-21)
Обработано offset 3600, собрано 3700 постов (последний: 2023-09-01)
Обработано offset 3700, собрано 3800 постов (последний: 2023-08-07)
Обработано offset 3800, собрано 3900 постов (последний: 2023-07-11)
Обработано offset 3900, собрано 4000 постов (последний: 2023-06-19)
Обработано offset 4000, собрано 4100 постов (последний: 2023-05-22)
Обработано offset 4100, собрано 4200 постов (последний: 2023-04-22)
Обработано offset 4200, собрано 4300 постов (последний: 2023-03-28)
Обработано offset 4300, собрано 4400 постов (последний: 2023-02-17)
Обработано offset 4400, собрано 4500 постов (последний: 2022-12-12)
Обработано offset 4500, собрано 4600 постов (последний: 2022-10-14)
Обработано offset 4600, собрано 4700 постов (последний: 2022-09-07)
Обработано offset 4700, собрано 4800 постов (последний: 2022-07-27)
Обработано offset 4800, собрано 4900 постов (последний: 2022-06-21)
Обработано offset 4900, собрано 5000 постов (последний: 2022-05-19)
Обработано offset 5000, собрано 5100 постов (последний: 2022-04-13)
Обработано offset 5100, собрано 5200 постов (последний: 2022-03-15)
Обработано offset 5200, собрано 5300 постов (последний: 2022-02-10)
Обработано offset 5300, собрано 5400 постов (последний: 2021-12-30)
Обработано offset 5400, собрано 5500 постов (последний: 2021-11-26)
Обработано offset 5500, собрано 5600 постов (последний: 2021-10-14)
Обработано offset 5600, собрано 5700 постов (последний: 2021-09-03)
Обработано offset 5700, собрано 5800 постов (последний: 2021-07-27)
Обработано offset 5800, собрано 5900 постов (последний: 2021-06-24)
Обработано offset 5900, собрано 6000 постов (последний: 2021-05-23)
Обработано offset 6000, собрано 6100 постов (последний: 2021-04-16)
Обработано offset 6100, собрано 6200 постов (последний: 2021-03-24)
Обработано offset 6200, собрано 6300 постов (последний: 2021-03-04)
Обработано offset 6300, собрано 6400 постов (последний: 2021-02-10)
Обработано offset 6400, собрано 6500 постов (последний: 2021-01-13)
Обработано offset 6500, собрано 6600 постов (последний: 2020-12-08)
Обработано offset 6600, собрано 6700 постов (последний: 2020-11-13)
Обработано offset 6700, собрано 6800 постов (последний: 2020-10-16)
Обработано offset 6800, собрано 6900 постов (последний: 2020-09-21)
Обработано offset 6900, собрано 7000 постов (последний: 2020-08-13)
Обработано offset 7000, собрано 7100 постов (последний: 2020-06-28)
Обработано offset 7100, собрано 7200 постов (последний: 2020-05-28)
Обработано offset 7200, собрано 7300 постов (последний: 2020-04-30)
Обработано offset 7300, собрано 7400 постов (последний: 2020-03-25)
Обработано offset 7400, собрано 7500 постов (последний: 2020-02-17)

- Достигли 2019 года -
Последний пост: 25830 от 2019-12-31
Всего собрано постов: 7583
Диапазон дат: 2020-01-03 - 2026-05-06

In [ ]:
# миэт
group_id = '-33509'
name = 'miet.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-09)
Обработано offset 100, собрано 200 постов (последний: 2026-03-17)
Обработано offset 200, собрано 300 постов (последний: 2026-02-13)
Обработано offset 300, собрано 400 постов (последний: 2026-01-15)
Обработано offset 400, собрано 500 постов (последний: 2025-12-13)
Обработано offset 500, собрано 600 постов (последний: 2025-11-27)
Обработано offset 600, собрано 700 постов (последний: 2025-11-04)
Обработано offset 700, собрано 800 постов (последний: 2025-10-14)
Обработано offset 800, собрано 900 постов (последний: 2025-09-22)
Обработано offset 900, собрано 1000 постов (последний: 2025-08-31)
Обработано offset 1000, собрано 1100 постов (последний: 2025-08-05)
Обработано offset 1100, собрано 1200 постов (последний: 2025-07-12)
Обработано offset 1200, собрано 1300 постов (последний: 2025-06-21)
Обработано offset 1300, собрано 1400 постов (последний: 2025-05-29)
Обработано offset 1400, собрано 1500 постов (последний: 2025-05-11)
Обработано offset 1500, собрано 1600 постов (последний: 2025-04-19)
Обработано offset 1600, собрано 1700 постов (последний: 2025-04-04)
Обработано offset 1700, собрано 1800 постов (последний: 2025-03-14)
Обработано offset 1800, собрано 1900 постов (последний: 2025-02-17)
Обработано offset 1900, собрано 2000 постов (последний: 2025-01-22)
Обработано offset 2000, собрано 2100 постов (последний: 2024-12-25)
Обработано offset 2100, собрано 2200 постов (последний: 2024-11-30)
Обработано offset 2200, собрано 2300 постов (последний: 2024-11-02)
Обработано offset 2300, собрано 2400 постов (последний: 2024-10-08)
Обработано offset 2400, собрано 2500 постов (последний: 2024-09-13)
Обработано offset 2500, собрано 2600 постов (последний: 2024-08-21)
Обработано offset 2600, собрано 2700 постов (последний: 2024-07-18)
Обработано offset 2700, собрано 2800 постов (последний: 2024-06-23)
Обработано offset 2800, собрано 2900 постов (последний: 2024-05-27)
Обработано offset 2900, собрано 3000 постов (последний: 2024-05-06)
Обработано offset 3000, собрано 3100 постов (последний: 2024-04-10)
Обработано offset 3100, собрано 3200 постов (последний: 2024-03-17)
Обработано offset 3200, собрано 3300 постов (последний: 2024-02-19)
Обработано offset 3300, собрано 3400 постов (последний: 2024-01-23)
Обработано offset 3400, собрано 3500 постов (последний: 2023-12-22)
Обработано offset 3500, собрано 3600 постов (последний: 2023-11-29)
Обработано offset 3600, собрано 3700 постов (последний: 2023-11-08)
Обработано offset 3700, собрано 3800 постов (последний: 2023-10-16)
Обработано offset 3800, собрано 3900 постов (последний: 2023-09-19)
Обработано offset 3900, собрано 4000 постов (последний: 2023-08-24)
Обработано offset 4000, собрано 4100 постов (последний: 2023-07-26)
Обработано offset 4100, собрано 4200 постов (последний: 2023-06-29)
Обработано offset 4200, собрано 4300 постов (последний: 2023-06-05)
Обработано offset 4300, собрано 4400 постов (последний: 2023-05-07)
Обработано offset 4400, собрано 4500 постов (последний: 2023-04-09)
Обработано offset 4500, собрано 4600 постов (последний: 2023-03-13)
Обработано offset 4600, собрано 4700 постов (последний: 2023-02-10)
Обработано offset 4700, собрано 4800 постов (последний: 2023-01-16)
Обработано offset 4800, собрано 4900 постов (последний: 2022-12-08)
Обработано offset 4900, собрано 5000 постов (последний: 2022-10-28)
Обработано offset 5000, собрано 5100 постов (последний: 2022-09-15)
Обработано offset 5100, собрано 5200 постов (последний: 2022-07-11)
Обработано offset 5200, собрано 5300 постов (последний: 2022-05-11)
Обработано offset 5300, собрано 5400 постов (последний: 2022-03-01)
Обработано offset 5400, собрано 5500 постов (последний: 2021-12-02)
Обработано offset 5500, собрано 5600 постов (последний: 2021-10-06)
Обработано offset 5600, собрано 5700 постов (последний: 2021-08-10)
Обработано offset 5700, собрано 5800 постов (последний: 2021-05-26)
Обработано offset 5800, собрано 5900 постов (последний: 2021-03-29)
Обработано offset 5900, собрано 6000 постов (последний: 2021-01-26)
Обработано offset 6000, собрано 6100 постов (последний: 2020-11-30)
Обработано offset 6100, собрано 6200 постов (последний: 2020-10-19)
Обработано offset 6200, собрано 6300 постов (последний: 2020-07-14)
Обработано offset 6300, собрано 6400 постов (последний: 2020-04-01)

- Достигли 2019 года -
Последний пост: 20094 от 2019-12-30
Всего собрано постов: 6489
Диапазон дат: 2020-01-01 - 2026-05-06

In [ ]:
# МСХА имени К.А. Тимирязева, академика РАН
group_id = '-146300938'
name = 'timacad.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-10)
Обработано offset 100, собрано 200 постов (последний: 2026-03-14)
Обработано offset 200, собрано 300 постов (последний: 2026-02-14)
Обработано offset 300, собрано 400 постов (последний: 2026-01-18)
Обработано offset 400, собрано 500 постов (последний: 2025-12-13)
Обработано offset 500, собрано 600 постов (последний: 2025-11-18)
Обработано offset 600, собрано 700 постов (последний: 2025-10-24)
Обработано offset 700, собрано 800 постов (последний: 2025-09-27)
Обработано offset 800, собрано 900 постов (последний: 2025-09-02)
Обработано offset 900, собрано 1000 постов (последний: 2025-08-01)
Обработано offset 1000, собрано 1100 постов (последний: 2025-06-26)
Обработано offset 1100, собрано 1200 постов (последний: 2025-05-24)
Обработано offset 1200, собрано 1300 постов (последний: 2025-04-18)
Обработано offset 1300, собрано 1400 постов (последний: 2025-02-11)
Обработано offset 1400, собрано 1500 постов (последний: 2024-12-17)
Обработано offset 1500, собрано 1600 постов (последний: 2024-11-11)
Обработано offset 1600, собрано 1700 постов (последний: 2024-10-08)
Обработано offset 1700, собрано 1800 постов (последний: 2024-09-01)
Обработано offset 1800, собрано 1900 постов (последний: 2024-07-23)
Обработано offset 1900, собрано 2000 постов (последний: 2024-06-22)
Обработано offset 2000, собрано 2100 постов (последний: 2024-05-17)
Обработано offset 2100, собрано 2200 постов (последний: 2024-04-12)
Обработано offset 2200, собрано 2300 постов (последний: 2024-03-09)
Обработано offset 2300, собрано 2400 постов (последний: 2024-02-01)
Обработано offset 2400, собрано 2500 постов (последний: 2023-12-18)
Обработано offset 2500, собрано 2600 постов (последний: 2023-11-11)
Обработано offset 2600, собрано 2700 постов (последний: 2023-10-11)
Обработано offset 2700, собрано 2800 постов (последний: 2023-09-06)
Обработано offset 2800, собрано 2900 постов (последний: 2023-07-27)
Обработано offset 2900, собрано 3000 постов (последний: 2023-06-24)
Обработано offset 3000, собрано 3100 постов (последний: 2023-05-24)
Обработано offset 3100, собрано 3200 постов (последний: 2023-04-18)
Обработано offset 3200, собрано 3300 постов (последний: 2023-03-02)
Обработано offset 3300, собрано 3400 постов (последний: 2023-01-16)
Обработано offset 3400, собрано 3500 постов (последний: 2022-11-21)
Обработано offset 3500, собрано 3600 постов (последний: 2022-09-23)
Обработано offset 3600, собрано 3700 постов (последний: 2022-08-04)
Обработано offset 3700, собрано 3800 постов (последний: 2022-06-09)
Обработано offset 3800, собрано 3900 постов (последний: 2022-04-16)
Обработано offset 3900, собрано 4000 постов (последний: 2022-03-02)
Обработано offset 4000, собрано 4100 постов (последний: 2022-01-11)
Обработано offset 4100, собрано 4200 постов (последний: 2021-11-17)
Обработано offset 4200, собрано 4300 постов (последний: 2021-10-05)
Обработано offset 4300, собрано 4400 постов (последний: 2021-08-20)
Обработано offset 4400, собрано 4500 постов (последний: 2021-07-06)
Обработано offset 4500, собрано 4600 постов (последний: 2021-05-27)
Обработано offset 4600, собрано 4700 постов (последний: 2021-04-13)
Обработано offset 4700, собрано 4800 постов (последний: 2021-03-02)
Обработано offset 4800, собрано 4900 постов (последний: 2021-01-15)
Обработано offset 4900, собрано 5000 постов (последний: 2020-11-25)
Обработано offset 5000, собрано 5100 постов (последний: 2020-10-14)
Обработано offset 5100, собрано 5200 постов (последний: 2020-08-27)
Обработано offset 5200, собрано 5300 постов (последний: 2020-06-25)
Обработано offset 5300, собрано 5400 постов (последний: 2020-04-27)
Обработано offset 5400, собрано 5500 постов (последний: 2020-03-05)
Обработано offset 5500, собрано 5600 постов (последний: 2020-01-15)

- Достигли 2019 года -
Последний пост: 7364 от 2019-12-31
Всего собрано постов: 5608
Диапазон дат: 2020-01-09 - 2026-05-06

In [ ]:
# гуу
group_id = '-23628595'
name = 'guu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-17)
Обработано offset 100, собрано 200 постов (последний: 2026-04-01)
Обработано offset 200, собрано 300 постов (последний: 2026-03-16)
Обработано offset 300, собрано 400 постов (последний: 2026-02-21)
Обработано offset 400, собрано 500 постов (последний: 2026-01-30)
Обработано offset 500, собрано 600 постов (последний: 2026-01-02)
Обработано offset 600, собрано 700 постов (последний: 2025-12-03)
Обработано offset 700, собрано 800 постов (последний: 2025-11-11)
Обработано offset 800, собрано 900 постов (последний: 2025-10-13)
Обработано offset 900, собрано 1000 постов (последний: 2025-08-22)
Обработано offset 1000, собрано 1100 постов (последний: 2025-07-02)
Обработано offset 1100, собрано 1200 постов (последний: 2025-05-14)
Обработано offset 1200, собрано 1300 постов (последний: 2025-03-22)
Обработано offset 1300, собрано 1400 постов (последний: 2025-02-03)
Обработано offset 1400, собрано 1500 постов (последний: 2024-12-05)
Обработано offset 1500, собрано 1600 постов (последний: 2024-10-23)
Обработано offset 1600, собрано 1700 постов (последний: 2024-09-09)
Обработано offset 1700, собрано 1800 постов (последний: 2024-07-20)
Обработано offset 1800, собрано 1900 постов (последний: 2024-06-10)
Обработано offset 1900, собрано 2000 постов (последний: 2024-04-27)
Обработано offset 2000, собрано 2100 постов (последний: 2024-03-14)
Обработано offset 2100, собрано 2200 постов (последний: 2024-01-26)
Обработано offset 2200, собрано 2300 постов (последний: 2023-12-16)
Обработано offset 2300, собрано 2400 постов (последний: 2023-10-19)
Обработано offset 2400, собрано 2500 постов (последний: 2023-08-18)
Обработано offset 2500, собрано 2600 постов (последний: 2023-06-24)
Обработано offset 2600, собрано 2700 постов (последний: 2023-04-17)
Обработано offset 2700, собрано 2800 постов (последний: 2023-02-20)
Обработано offset 2800, собрано 2900 постов (последний: 2022-12-08)
Обработано offset 2900, собрано 3000 постов (последний: 2022-09-27)
Обработано offset 3000, собрано 3100 постов (последний: 2022-07-06)
Обработано offset 3100, собрано 3200 постов (последний: 2022-04-16)
Обработано offset 3200, собрано 3300 постов (последний: 2021-12-18)
Обработано offset 3300, собрано 3400 постов (последний: 2021-09-30)
Обработано offset 3400, собрано 3500 постов (последний: 2021-07-20)
Обработано offset 3500, собрано 3600 постов (последний: 2021-06-02)
Обработано offset 3600, собрано 3700 постов (последний: 2021-04-07)
Обработано offset 3700, собрано 3800 постов (последний: 2021-02-12)
Обработано offset 3800, собрано 3900 постов (последний: 2020-12-14)
Обработано offset 3900, собрано 4000 постов (последний: 2020-11-09)
Обработано offset 4000, собрано 4100 постов (последний: 2020-10-01)
Обработано offset 4100, собрано 4200 постов (последний: 2020-08-11)
Обработано offset 4200, собрано 4300 постов (последний: 2020-07-06)
Обработано offset 4300, собрано 4400 постов (последний: 2020-06-04)
Обработано offset 4400, собрано 4500 постов (последний: 2020-04-28)
Обработано offset 4500, собрано 4600 постов (последний: 2020-03-12)
Обработано offset 4600, собрано 4700 постов (последний: 2020-01-10)

- Достигли 2019 года -
Последний пост: 13139 от 2019-12-31
Всего собрано постов: 4702
Диапазон дат: 2020-01-09 - 2026-05-06

In [ ]:
# мгсу
group_id = '-97639426'
name = 'mgsu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-17)
Обработано offset 100, собрано 200 постов (последний: 2026-04-02)
Обработано offset 200, собрано 300 постов (последний: 2026-03-18)
Обработано offset 300, собрано 400 постов (последний: 2026-02-28)
Обработано offset 400, собрано 500 постов (последний: 2026-02-09)
Обработано offset 500, собрано 600 постов (последний: 2026-01-21)
Обработано offset 600, собрано 700 постов (последний: 2025-12-25)
Обработано offset 700, собрано 800 постов (последний: 2025-12-05)
Обработано offset 800, собрано 900 постов (последний: 2025-11-21)
Обработано offset 900, собрано 1000 постов (последний: 2025-11-03)
Обработано offset 1000, собрано 1100 постов (последний: 2025-10-17)
Обработано offset 1100, собрано 1200 постов (последний: 2025-09-30)
Обработано offset 1200, собрано 1300 постов (последний: 2025-09-17)
Обработано offset 1300, собрано 1400 постов (последний: 2025-08-30)
Обработано offset 1400, собрано 1500 постов (последний: 2025-08-15)
Обработано offset 1500, собрано 1600 постов (последний: 2025-07-30)
Обработано offset 1600, собрано 1700 постов (последний: 2025-07-16)
Обработано offset 1700, собрано 1800 постов (последний: 2025-06-28)
Обработано offset 1800, собрано 1900 постов (последний: 2025-06-16)
Обработано offset 1900, собрано 2000 постов (последний: 2025-05-29)
Обработано offset 2000, собрано 2100 постов (последний: 2025-05-14)
Обработано offset 2100, собрано 2200 постов (последний: 2025-04-23)
Обработано offset 2200, собрано 2300 постов (последний: 2025-04-05)
Обработано offset 2300, собрано 2400 постов (последний: 2025-03-18)
Обработано offset 2400, собрано 2500 постов (последний: 2025-02-26)
Обработано offset 2500, собрано 2600 постов (последний: 2025-02-04)
Обработано offset 2600, собрано 2700 постов (последний: 2025-01-15)
Обработано offset 2700, собрано 2800 постов (последний: 2024-12-03)
Обработано offset 2800, собрано 2900 постов (последний: 2024-11-01)
Обработано offset 2900, собрано 3000 постов (последний: 2024-10-04)
Обработано offset 3000, собрано 3100 постов (последний: 2024-09-06)
Обработано offset 3100, собрано 3200 постов (последний: 2024-08-12)
Обработано offset 3200, собрано 3300 постов (последний: 2024-07-22)
Обработано offset 3300, собрано 3400 постов (последний: 2024-06-28)
Обработано offset 3400, собрано 3500 постов (последний: 2024-06-10)
Обработано offset 3500, собрано 3600 постов (последний: 2024-05-25)
Обработано offset 3600, собрано 3700 постов (последний: 2024-05-06)
Обработано offset 3700, собрано 3800 постов (последний: 2024-04-12)
Обработано offset 3800, собрано 3900 постов (последний: 2024-03-22)
Обработано offset 3900, собрано 4000 постов (последний: 2024-03-07)
Обработано offset 4000, собрано 4100 постов (последний: 2024-02-17)
Обработано offset 4100, собрано 4200 постов (последний: 2024-02-01)
Обработано offset 4200, собрано 4300 постов (последний: 2024-01-12)
Обработано offset 4300, собрано 4400 постов (последний: 2023-12-13)
Обработано offset 4400, собрано 4500 постов (последний: 2023-11-23)
Обработано offset 4500, собрано 4600 постов (последний: 2023-10-29)
Обработано offset 4600, собрано 4700 постов (последний: 2023-10-05)
Обработано offset 4700, собрано 4800 постов (последний: 2023-09-12)
Обработано offset 4800, собрано 4900 постов (последний: 2023-08-13)
Обработано offset 4900, собрано 5000 постов (последний: 2023-07-18)
Обработано offset 5000, собрано 5100 постов (последний: 2023-06-16)
Обработано offset 5100, собрано 5200 постов (последний: 2023-05-18)
Обработано offset 5200, собрано 5300 постов (последний: 2023-04-18)
Обработано offset 5300, собрано 5400 постов (последний: 2023-03-10)
Обработано offset 5400, собрано 5500 постов (последний: 2023-01-30)
Обработано offset 5500, собрано 5600 постов (последний: 2022-12-26)
Обработано offset 5600, собрано 5700 постов (последний: 2022-11-30)
Обработано offset 5700, собрано 5800 постов (последний: 2022-11-04)
Обработано offset 5800, собрано 5900 постов (последний: 2022-10-14)
Обработано offset 5900, собрано 6000 постов (последний: 2022-09-28)
Обработано offset 6000, собрано 6100 постов (последний: 2022-09-13)
Обработано offset 6100, собрано 6200 постов (последний: 2022-08-24)
Обработано offset 6200, собрано 6300 постов (последний: 2022-08-05)
Обработано offset 6300, собрано 6400 постов (последний: 2022-07-12)
Обработано offset 6400, собрано 6500 постов (последний: 2022-06-24)
Обработано offset 6500, собрано 6600 постов (последний: 2022-06-09)
Обработано offset 6600, собрано 6700 постов (последний: 2022-05-23)
Обработано offset 6700, собрано 6800 постов (последний: 2022-04-27)
Обработано offset 6800, собрано 6900 постов (последний: 2022-04-11)
Обработано offset 6900, собрано 7000 постов (последний: 2022-03-25)
Обработано offset 7000, собрано 7100 постов (последний: 2022-02-08)
Обработано offset 7100, собрано 7200 постов (последний: 2021-09-13)
Обработано offset 7200, собрано 7300 постов (последний: 2021-07-28)
Обработано offset 7300, собрано 7400 постов (последний: 2021-06-04)
Обработано offset 7400, собрано 7500 постов (последний: 2020-09-19)
Обработано offset 7500, собрано 7600 постов (последний: 2020-02-25)

- Достигли 2019 года -
Последний пост: 40074 от 2019-12-27
Всего собрано постов: 7605
Диапазон дат: 2020-01-22 - 2026-05-06

In [ ]:
# косыгина
group_id = '-38924'
name = 'rguk.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-12)
Обработано offset 100, собрано 200 постов (последний: 2026-03-16)
Обработано offset 200, собрано 300 постов (последний: 2026-02-20)
Обработано offset 300, собрано 400 постов (последний: 2026-01-28)
Обработано offset 400, собрано 500 постов (последний: 2025-12-22)
Обработано offset 500, собрано 600 постов (последний: 2025-11-27)
Обработано offset 600, собрано 700 постов (последний: 2025-11-05)
Обработано offset 700, собрано 800 постов (последний: 2025-10-14)
Обработано offset 800, собрано 900 постов (последний: 2025-09-22)
Обработано offset 900, собрано 1000 постов (последний: 2025-08-22)
Обработано offset 1000, собрано 1100 постов (последний: 2025-07-19)
Обработано offset 1100, собрано 1200 постов (последний: 2025-06-27)
Обработано offset 1200, собрано 1300 постов (последний: 2025-06-06)
Обработано offset 1300, собрано 1400 постов (последний: 2025-05-16)
Обработано offset 1400, собрано 1500 постов (последний: 2025-04-29)
Обработано offset 1500, собрано 1600 постов (последний: 2025-04-12)
Обработано offset 1600, собрано 1700 постов (последний: 2025-03-24)
Обработано offset 1700, собрано 1800 постов (последний: 2025-03-12)
Обработано offset 1800, собрано 1900 постов (последний: 2025-02-27)
Обработано offset 1900, собрано 2000 постов (последний: 2025-02-10)
Обработано offset 2000, собрано 2100 постов (последний: 2025-01-27)
Обработано offset 2100, собрано 2200 постов (последний: 2024-12-26)
Обработано offset 2200, собрано 2300 постов (последний: 2024-12-08)
Обработано offset 2300, собрано 2400 постов (последний: 2024-11-13)
Обработано offset 2400, собрано 2500 постов (последний: 2024-10-18)
Обработано offset 2500, собрано 2600 постов (последний: 2024-09-12)
Обработано offset 2600, собрано 2700 постов (последний: 2024-07-22)
Обработано offset 2700, собрано 2800 постов (последний: 2024-06-13)
Обработано offset 2800, собрано 2900 постов (последний: 2024-05-18)
Обработано offset 2900, собрано 3000 постов (последний: 2024-04-19)
Обработано offset 3000, собрано 3100 постов (последний: 2024-03-25)
Обработано offset 3100, собрано 3200 постов (последний: 2024-03-02)
Обработано offset 3200, собрано 3300 постов (последний: 2024-02-15)
Обработано offset 3300, собрано 3400 постов (последний: 2024-01-23)
Обработано offset 3400, собрано 3500 постов (последний: 2023-12-16)
Обработано offset 3500, собрано 3600 постов (последний: 2023-11-24)
Обработано offset 3600, собрано 3700 постов (последний: 2023-11-08)
Обработано offset 3700, собрано 3800 постов (последний: 2023-10-17)
Обработано offset 3800, собрано 3900 постов (последний: 2023-09-23)
Обработано offset 3900, собрано 4000 постов (последний: 2023-08-30)
Обработано offset 4000, собрано 4100 постов (последний: 2023-07-22)
Обработано offset 4100, собрано 4200 постов (последний: 2023-06-29)
Обработано offset 4200, собрано 4300 постов (последний: 2023-06-06)
Обработано offset 4300, собрано 4400 постов (последний: 2023-05-17)
Обработано offset 4400, собрано 4500 постов (последний: 2023-04-24)
Обработано offset 4500, собрано 4600 постов (последний: 2023-03-31)
Обработано offset 4600, собрано 4700 постов (последний: 2023-03-08)
Обработано offset 4700, собрано 4800 постов (последний: 2023-02-10)
Обработано offset 4800, собрано 4900 постов (последний: 2023-01-13)
Обработано offset 4900, собрано 5000 постов (последний: 2022-12-10)
Обработано offset 5000, собрано 5100 постов (последний: 2022-11-17)
Обработано offset 5100, собрано 5200 постов (последний: 2022-10-24)
Обработано offset 5200, собрано 5300 постов (последний: 2022-09-27)
Обработано offset 5300, собрано 5400 постов (последний: 2022-09-01)
Обработано offset 5400, собрано 5500 постов (последний: 2022-07-28)
Обработано offset 5500, собрано 5600 постов (последний: 2022-07-02)
Обработано offset 5600, собрано 5700 постов (последний: 2022-06-10)
Обработано offset 5700, собрано 5800 постов (последний: 2022-05-10)
Обработано offset 5800, собрано 5900 постов (последний: 2022-04-04)
Обработано offset 5900, собрано 6000 постов (последний: 2022-03-02)
Обработано offset 6000, собрано 6100 постов (последний: 2021-12-26)
Обработано offset 6100, собрано 6200 постов (последний: 2021-11-23)
Обработано offset 6200, собрано 6300 постов (последний: 2021-09-26)
Обработано offset 6300, собрано 6400 постов (последний: 2021-07-10)
Обработано offset 6400, собрано 6500 постов (последний: 2021-04-20)
Обработано offset 6500, собрано 6600 постов (последний: 2021-02-25)
Обработано offset 6600, собрано 6700 постов (последний: 2020-12-18)
Обработано offset 6700, собрано 6800 постов (последний: 2020-11-11)
Обработано offset 6800, собрано 6900 постов (последний: 2020-09-30)
Обработано offset 6900, собрано 7000 постов (последний: 2020-07-28)
Обработано offset 7000, собрано 7100 постов (последний: 2020-06-15)
Обработано offset 7100, собрано 7200 постов (последний: 2020-05-05)
Обработано offset 7200, собрано 7300 постов (последний: 2020-04-03)
Обработано offset 7300, собрано 7400 постов (последний: 2020-02-10)

- Достигли 2019 года -
Последний пост: 38479 от 2019-12-31
Всего собрано постов: 7466
Диапазон дат: 2020-01-04 - 2026-05-06

In [ ]:
# щукина
group_id = '-23778827'
name = 'shcukina.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-11)
Обработано offset 100, собрано 200 постов (последний: 2026-03-18)
Обработано offset 200, собрано 300 постов (последний: 2026-02-20)
Обработано offset 300, собрано 400 постов (последний: 2026-01-30)
Обработано offset 400, собрано 500 постов (последний: 2025-12-23)
Обработано offset 500, собрано 600 постов (последний: 2025-11-28)
Обработано offset 600, собрано 700 постов (последний: 2025-11-14)
Обработано offset 700, собрано 800 постов (последний: 2025-10-24)
Обработано offset 800, собрано 900 постов (последний: 2025-09-27)
Обработано offset 900, собрано 1000 постов (последний: 2025-09-05)
Обработано offset 1000, собрано 1100 постов (последний: 2025-08-08)
Обработано offset 1100, собрано 1200 постов (последний: 2025-07-08)
Обработано offset 1200, собрано 1300 постов (последний: 2025-06-15)
Обработано offset 1300, собрано 1400 постов (последний: 2025-05-30)
Обработано offset 1400, собрано 1500 постов (последний: 2025-05-13)
Обработано offset 1500, собрано 1600 постов (последний: 2025-04-30)
Обработано offset 1600, собрано 1700 постов (последний: 2025-04-20)
Обработано offset 1700, собрано 1800 постов (последний: 2025-04-07)
Обработано offset 1800, собрано 1900 постов (последний: 2025-03-22)
Обработано offset 1900, собрано 2000 постов (последний: 2025-03-08)
Обработано offset 2000, собрано 2100 постов (последний: 2025-02-15)
Обработано offset 2100, собрано 2200 постов (последний: 2025-01-28)
Обработано offset 2200, собрано 2300 постов (последний: 2024-12-31)
Обработано offset 2300, собрано 2400 постов (последний: 2024-12-09)
Обработано offset 2400, собрано 2500 постов (последний: 2024-11-20)
Обработано offset 2500, собрано 2600 постов (последний: 2024-11-05)
Обработано offset 2600, собрано 2700 постов (последний: 2024-10-24)
Обработано offset 2700, собрано 2800 постов (последний: 2024-10-12)
Обработано offset 2800, собрано 2900 постов (последний: 2024-09-20)
Обработано offset 2900, собрано 3000 постов (последний: 2024-08-31)
Обработано offset 3000, собрано 3100 постов (последний: 2024-07-11)
Обработано offset 3100, собрано 3200 постов (последний: 2024-06-23)
Обработано offset 3200, собрано 3300 постов (последний: 2024-06-07)
Обработано offset 3300, собрано 3400 постов (последний: 2024-05-21)
Обработано offset 3400, собрано 3500 постов (последний: 2024-05-08)
Обработано offset 3500, собрано 3600 постов (последний: 2024-04-26)
Обработано offset 3600, собрано 3700 постов (последний: 2024-04-14)
Обработано offset 3700, собрано 3800 постов (последний: 2024-03-29)
Обработано offset 3800, собрано 3900 постов (последний: 2024-03-07)
Обработано offset 3900, собрано 4000 постов (последний: 2024-02-06)
Обработано offset 4000, собрано 4100 постов (последний: 2023-12-29)
Обработано offset 4100, собрано 4200 постов (последний: 2023-11-25)
Обработано offset 4200, собрано 4300 постов (последний: 2023-10-30)
Обработано offset 4300, собрано 4400 постов (последний: 2023-10-03)
Обработано offset 4400, собрано 4500 постов (последний: 2023-09-11)
Обработано offset 4500, собрано 4600 постов (последний: 2023-07-25)
Обработано offset 4600, собрано 4700 постов (последний: 2023-06-09)
Обработано offset 4700, собрано 4800 постов (последний: 2023-05-18)
Обработано offset 4800, собрано 4900 постов (последний: 2023-05-02)
Обработано offset 4900, собрано 5000 постов (последний: 2023-04-13)
Обработано offset 5000, собрано 5100 постов (последний: 2023-03-29)
Обработано offset 5100, собрано 5200 постов (последний: 2023-03-07)
Обработано offset 5200, собрано 5300 постов (последний: 2023-02-09)
Обработано offset 5300, собрано 5400 постов (последний: 2022-12-31)
Обработано offset 5400, собрано 5500 постов (последний: 2022-12-04)
Обработано offset 5500, собрано 5600 постов (последний: 2022-11-13)
Обработано offset 5600, собрано 5700 постов (последний: 2022-10-18)
Обработано offset 5700, собрано 5800 постов (последний: 2022-09-06)
Обработано offset 5800, собрано 5900 постов (последний: 2022-06-22)
Обработано offset 5900, собрано 6000 постов (последний: 2022-05-14)
Обработано offset 6000, собрано 6100 постов (последний: 2022-03-13)
Обработано offset 6100, собрано 6200 постов (последний: 2021-08-31)
Обработано offset 6200, собрано 6300 постов (последний: 2021-05-11)
Обработано offset 6300, собрано 6400 постов (последний: 2021-01-22)
Обработано offset 6400, собрано 6500 постов (последний: 2020-09-21)
Обработано offset 6500, собрано 6600 постов (последний: 2020-04-02)

- Достигли 2019 года -
Последний пост: 3614 от 2019-12-31
Всего собрано постов: 6670
Диапазон дат: 2020-01-02 - 2026-05-06

In [ ]:
# менделевыа
group_id = '-31037181'
name = 'muctr.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-01)
Обработано offset 100, собрано 200 постов (последний: 2026-02-25)
Обработано offset 200, собрано 300 постов (последний: 2026-01-23)
Обработано offset 300, собрано 400 постов (последний: 2025-12-11)
Обработано offset 400, собрано 500 постов (последний: 2025-11-11)
Обработано offset 500, собрано 600 постов (последний: 2025-10-05)
Обработано offset 600, собрано 700 постов (последний: 2025-08-28)
Обработано offset 700, собрано 800 постов (последний: 2025-07-21)
Обработано offset 800, собрано 900 постов (последний: 2025-05-31)
Обработано offset 900, собрано 1000 постов (последний: 2025-05-07)
Обработано offset 1000, собрано 1100 постов (последний: 2025-04-07)
Обработано offset 1100, собрано 1200 постов (последний: 2025-03-03)
Обработано offset 1200, собрано 1300 постов (последний: 2025-01-15)
Обработано offset 1300, собрано 1400 постов (последний: 2024-11-19)
Обработано offset 1400, собрано 1500 постов (последний: 2024-09-30)
Обработано offset 1500, собрано 1600 постов (последний: 2024-08-12)
Обработано offset 1600, собрано 1700 постов (последний: 2024-07-02)
Обработано offset 1700, собрано 1800 постов (последний: 2024-05-15)
Обработано offset 1800, собрано 1900 постов (последний: 2024-04-04)
Обработано offset 1900, собрано 2000 постов (последний: 2024-02-29)
Обработано offset 2000, собрано 2100 постов (последний: 2024-01-23)
Обработано offset 2100, собрано 2200 постов (последний: 2023-12-04)
Обработано offset 2200, собрано 2300 постов (последний: 2023-10-30)
Обработано offset 2300, собрано 2400 постов (последний: 2023-09-27)
Обработано offset 2400, собрано 2500 постов (последний: 2023-08-18)
Обработано offset 2500, собрано 2600 постов (последний: 2023-07-04)
Обработано offset 2600, собрано 2700 постов (последний: 2023-05-24)
Обработано offset 2700, собрано 2800 постов (последний: 2023-04-25)
Обработано offset 2800, собрано 2900 постов (последний: 2023-03-24)
Обработано offset 2900, собрано 3000 постов (последний: 2023-02-22)
Обработано offset 3000, собрано 3100 постов (последний: 2023-01-25)
Обработано offset 3100, собрано 3200 постов (последний: 2022-12-13)
Обработано offset 3200, собрано 3300 постов (последний: 2022-11-23)
Обработано offset 3300, собрано 3400 постов (последний: 2022-10-30)
Обработано offset 3400, собрано 3500 постов (последний: 2022-10-05)
Обработано offset 3500, собрано 3600 постов (последний: 2022-09-07)
Обработано offset 3600, собрано 3700 постов (последний: 2022-08-04)
Обработано offset 3700, собрано 3800 постов (последний: 2022-06-29)
Обработано offset 3800, собрано 3900 постов (последний: 2022-05-26)
Обработано offset 3900, собрано 4000 постов (последний: 2022-04-21)
Обработано offset 4000, собрано 4100 постов (последний: 2022-03-16)
Обработано offset 4100, собрано 4200 постов (последний: 2021-12-21)
Обработано offset 4200, собрано 4300 постов (последний: 2021-10-18)
Обработано offset 4300, собрано 4400 постов (последний: 2021-08-18)
Обработано offset 4400, собрано 4500 постов (последний: 2021-06-09)
Обработано offset 4500, собрано 4600 постов (последний: 2021-04-14)
Обработано offset 4600, собрано 4700 постов (последний: 2021-02-08)
Обработано offset 4700, собрано 4800 постов (последний: 2020-12-07)
Обработано offset 4800, собрано 4900 постов (последний: 2020-10-19)
Обработано offset 4900, собрано 5000 постов (последний: 2020-08-19)
Обработано offset 5000, собрано 5100 постов (последний: 2020-06-08)
Обработано offset 5100, собрано 5200 постов (последний: 2020-04-10)

- Достигли 2019 года -
Последний пост: 43390 от 2019-12-30
Всего собрано постов: 5286
Диапазон дат: 2020-01-21 - 2026-05-05

In [ ]:
# гнесин
group_id = '-30431394'
name = 'gnesin.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-02-17)
Обработано offset 100, собрано 200 постов (последний: 2025-11-24)
Обработано offset 200, собрано 300 постов (последний: 2025-09-25)
Обработано offset 300, собрано 400 постов (последний: 2025-06-24)
Обработано offset 400, собрано 500 постов (последний: 2025-04-23)
Обработано offset 500, собрано 600 постов (последний: 2025-03-11)
Обработано offset 600, собрано 700 постов (последний: 2024-12-24)
Обработано offset 700, собрано 800 постов (последний: 2024-10-28)
Обработано offset 800, собрано 900 постов (последний: 2024-09-04)
Обработано offset 900, собрано 1000 постов (последний: 2024-05-19)
Обработано offset 1000, собрано 1100 постов (последний: 2024-03-20)
Обработано offset 1100, собрано 1200 постов (последний: 2024-01-25)
Обработано offset 1200, собрано 1300 постов (последний: 2023-11-06)
Обработано offset 1300, собрано 1400 постов (последний: 2023-09-11)
Обработано offset 1400, собрано 1500 постов (последний: 2023-06-19)
Обработано offset 1500, собрано 1600 постов (последний: 2023-04-14)
Обработано offset 1600, собрано 1700 постов (последний: 2023-02-18)
Обработано offset 1700, собрано 1800 постов (последний: 2022-12-12)
Обработано offset 1800, собрано 1900 постов (последний: 2022-10-25)
Обработано offset 1900, собрано 2000 постов (последний: 2022-09-09)
Обработано offset 2000, собрано 2100 постов (последний: 2022-06-24)
Обработано offset 2100, собрано 2200 постов (последний: 2022-05-06)

- Достигли 2012 года -
Последний пост: 50 от 2012-02-24
Всего собрано постов: 2214
Диапазон дат: 2022-04-29 - 2026-05-05

In [ ]:
# синергия
group_id = '-38029'
name = 'synergy.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-16)
Обработано offset 100, собрано 200 постов (последний: 2026-01-05)
Обработано offset 200, собрано 300 постов (последний: 2025-11-10)
Обработано offset 300, собрано 400 постов (последний: 2025-08-02)
Обработано offset 400, собрано 500 постов (последний: 2025-05-06)
Обработано offset 500, собрано 600 постов (последний: 2025-04-08)
Обработано offset 600, собрано 700 постов (последний: 2025-03-08)
Обработано offset 700, собрано 800 постов (последний: 2025-02-07)
Обработано offset 800, собрано 900 постов (последний: 2025-01-09)
Обработано offset 900, собрано 1000 постов (последний: 2024-12-05)
Обработано offset 1000, собрано 1100 постов (последний: 2024-11-13)
Обработано offset 1100, собрано 1200 постов (последний: 2024-10-19)
Обработано offset 1200, собрано 1300 постов (последний: 2024-09-28)
Обработано offset 1300, собрано 1400 постов (последний: 2024-09-11)
Обработано offset 1400, собрано 1500 постов (последний: 2024-08-26)
Обработано offset 1500, собрано 1600 постов (последний: 2024-08-04)
Обработано offset 1600, собрано 1700 постов (последний: 2024-07-14)
Обработано offset 1700, собрано 1800 постов (последний: 2024-06-25)
Обработано offset 1800, собрано 1900 постов (последний: 2024-06-07)
Обработано offset 1900, собрано 2000 постов (последний: 2024-05-21)
Обработано offset 2000, собрано 2100 постов (последний: 2024-05-02)
Обработано offset 2100, собрано 2200 постов (последний: 2024-04-14)
Обработано offset 2200, собрано 2300 постов (последний: 2024-03-28)
Обработано offset 2300, собрано 2400 постов (последний: 2024-03-12)
Обработано offset 2400, собрано 2500 постов (последний: 2024-02-25)
Обработано offset 2500, собрано 2600 постов (последний: 2024-02-08)
Обработано offset 2600, собрано 2700 постов (последний: 2024-01-22)
Обработано offset 2700, собрано 2800 постов (последний: 2023-12-29)
Обработано offset 2800, собрано 2900 постов (последний: 2023-12-12)
Обработано offset 2900, собрано 3000 постов (последний: 2023-11-24)
Обработано offset 3000, собрано 3100 постов (последний: 2023-11-07)
Обработано offset 3100, собрано 3200 постов (последний: 2023-10-21)
Обработано offset 3200, собрано 3300 постов (последний: 2023-09-28)
Обработано offset 3300, собрано 3400 постов (последний: 2023-09-07)
Обработано offset 3400, собрано 3500 постов (последний: 2023-08-19)
Обработано offset 3500, собрано 3600 постов (последний: 2023-08-02)
Обработано offset 3600, собрано 3700 постов (последний: 2023-07-14)
Обработано offset 3700, собрано 3800 постов (последний: 2023-06-28)
Обработано offset 3800, собрано 3900 постов (последний: 2023-06-10)
Обработано offset 3900, собрано 4000 постов (последний: 2023-05-24)
Обработано offset 4000, собрано 4100 постов (последний: 2023-05-08)
Обработано offset 4100, собрано 4200 постов (последний: 2023-04-22)
Обработано offset 4200, собрано 4300 постов (последний: 2023-04-05)
Обработано offset 4300, собрано 4400 постов (последний: 2023-03-17)
Обработано offset 4400, собрано 4500 постов (последний: 2023-02-27)
Обработано offset 4500, собрано 4600 постов (последний: 2023-02-09)
Обработано offset 4600, собрано 4700 постов (последний: 2023-01-22)
Обработано offset 4700, собрано 4800 постов (последний: 2022-12-29)
Обработано offset 4800, собрано 4900 постов (последний: 2022-12-09)
Обработано offset 4900, собрано 5000 постов (последний: 2022-11-23)
Обработано offset 5000, собрано 5100 постов (последний: 2022-11-01)
Обработано offset 5100, собрано 5200 постов (последний: 2022-10-12)
Обработано offset 5200, собрано 5300 постов (последний: 2022-09-21)
Обработано offset 5300, собрано 5400 постов (последний: 2022-09-02)
Обработано offset 5400, собрано 5500 постов (последний: 2022-08-16)
Обработано offset 5500, собрано 5600 постов (последний: 2022-08-03)
Обработано offset 5600, собрано 5700 постов (последний: 2022-07-20)
Обработано offset 5700, собрано 5800 постов (последний: 2022-06-30)
Обработано offset 5800, собрано 5900 постов (последний: 2022-06-17)
Обработано offset 5900, собрано 6000 постов (последний: 2022-06-03)
Обработано offset 6000, собрано 6100 постов (последний: 2022-05-23)
Обработано offset 6100, собрано 6200 постов (последний: 2022-05-05)
Обработано offset 6200, собрано 6300 постов (последний: 2022-04-16)
Обработано offset 6300, собрано 6400 постов (последний: 2022-03-21)
Обработано offset 6400, собрано 6500 постов (последний: 2022-01-09)
Обработано offset 6500, собрано 6600 постов (последний: 2021-09-12)
Обработано offset 6600, собрано 6700 постов (последний: 2021-05-11)
Обработано offset 6700, собрано 6800 постов (последний: 2021-01-22)
Обработано offset 6800, собрано 6900 постов (последний: 2020-10-27)
Обработано offset 6900, собрано 7000 постов (последний: 2020-08-04)
Обработано offset 7000, собрано 7100 постов (последний: 2020-05-18)
Обработано offset 7100, собрано 7200 постов (последний: 2020-03-11)
Обработано offset 7200, собрано 7300 постов (последний: 2020-01-10)

- Достигли 2019 года -
Последний пост: 49858 от 2019-12-31
Всего собрано постов: 7306
Диапазон дат: 2020-01-03 - 2026-05-06

In [ ]:
# политех
group_id = '-33991085'
name = 'polytech.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-03)
Обработано offset 100, собрано 200 постов (последний: 2026-03-04)
Обработано offset 200, собрано 300 постов (последний: 2026-01-26)
Обработано offset 300, собрано 400 постов (последний: 2025-11-14)
Обработано offset 400, собрано 500 постов (последний: 2025-09-23)
Обработано offset 500, собрано 600 постов (последний: 2025-08-12)
Обработано offset 600, собрано 700 постов (последний: 2025-06-27)
Обработано offset 700, собрано 800 постов (последний: 2025-05-06)
Обработано offset 800, собрано 900 постов (последний: 2025-03-22)
Обработано offset 900, собрано 1000 постов (последний: 2025-02-05)
Обработано offset 1000, собрано 1100 постов (последний: 2024-12-06)
Обработано offset 1100, собрано 1200 постов (последний: 2024-10-23)
Обработано offset 1200, собрано 1300 постов (последний: 2024-09-09)
Обработано offset 1300, собрано 1400 постов (последний: 2024-07-30)
Обработано offset 1400, собрано 1500 постов (последний: 2024-06-05)
Обработано offset 1500, собрано 1600 постов (последний: 2024-04-21)
Обработано offset 1600, собрано 1700 постов (последний: 2024-03-13)
Обработано offset 1700, собрано 1800 постов (последний: 2024-01-30)
Обработано offset 1800, собрано 1900 постов (последний: 2023-12-07)
Обработано offset 1900, собрано 2000 постов (последний: 2023-10-19)
Обработано offset 2000, собрано 2100 постов (последний: 2023-09-07)
Обработано offset 2100, собрано 2200 постов (последний: 2023-07-23)
Обработано offset 2200, собрано 2300 постов (последний: 2023-06-07)
Обработано offset 2300, собрано 2400 постов (последний: 2023-04-20)
Обработано offset 2400, собрано 2500 постов (последний: 2023-03-12)
Обработано offset 2500, собрано 2600 постов (последний: 2023-01-29)
Обработано offset 2600, собрано 2700 постов (последний: 2022-12-19)
Обработано offset 2700, собрано 2800 постов (последний: 2022-11-21)
Обработано offset 2800, собрано 2900 постов (последний: 2022-10-19)
Обработано offset 2900, собрано 3000 постов (последний: 2022-09-13)
Обработано offset 3000, собрано 3100 постов (последний: 2022-07-22)
Обработано offset 3100, собрано 3200 постов (последний: 2022-06-13)
Обработано offset 3200, собрано 3300 постов (последний: 2022-05-04)
Обработано offset 3300, собрано 3400 постов (последний: 2022-03-17)
Обработано offset 3400, собрано 3500 постов (последний: 2022-02-09)
Обработано offset 3500, собрано 3600 постов (последний: 2021-12-23)
Обработано offset 3600, собрано 3700 постов (последний: 2021-11-25)
Обработано offset 3700, собрано 3800 постов (последний: 2021-10-25)
Обработано offset 3800, собрано 3900 постов (последний: 2021-10-03)
Обработано offset 3900, собрано 4000 постов (последний: 2021-09-08)
Обработано offset 4000, собрано 4100 постов (последний: 2021-08-03)
Обработано offset 4100, собрано 4200 постов (последний: 2021-06-28)
Обработано offset 4200, собрано 4300 постов (последний: 2021-05-27)
Обработано offset 4300, собрано 4400 постов (последний: 2021-04-26)
Обработано offset 4400, собрано 4500 постов (последний: 2021-03-30)
Обработано offset 4500, собрано 4600 постов (последний: 2021-03-03)
Обработано offset 4600, собрано 4700 постов (последний: 2021-01-31)
Обработано offset 4700, собрано 4800 постов (последний: 2020-11-13)
Обработано offset 4800, собрано 4900 постов (последний: 2020-09-12)
Обработано offset 4900, собрано 5000 постов (последний: 2020-08-07)
Обработано offset 5000, собрано 5100 постов (последний: 2020-06-21)
Обработано offset 5100, собрано 5200 постов (последний: 2020-05-11)
Обработано offset 5200, собрано 5300 постов (последний: 2020-04-07)
Обработано offset 5300, собрано 5400 постов (последний: 2020-03-08)
Обработано offset 5400, собрано 5500 постов (последний: 2020-02-11)

- Достигли 2019 года -
Последний пост: 8227 от 2019-12-31
Всего собрано постов: 5553
Диапазон дат: 2020-01-09 - 2026-05-06

In [ ]:
# мгппу
group_id = '-38093474'
name = 'mgppu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-10)
Обработано offset 100, собрано 200 постов (последний: 2026-03-20)
Обработано offset 200, собрано 300 постов (последний: 2026-02-27)
Обработано offset 300, собрано 400 постов (последний: 2026-02-09)
Обработано offset 400, собрано 500 постов (последний: 2026-01-19)
Обработано offset 500, собрано 600 постов (последний: 2025-12-12)
Обработано offset 600, собрано 700 постов (последний: 2025-11-14)
Обработано offset 700, собрано 800 постов (последний: 2025-10-22)
Обработано offset 800, собрано 900 постов (последний: 2025-10-01)
Обработано offset 900, собрано 1000 постов (последний: 2025-09-01)
Обработано offset 1000, собрано 1100 постов (последний: 2025-08-04)
Обработано offset 1100, собрано 1200 постов (последний: 2025-07-09)
Обработано offset 1200, собрано 1300 постов (последний: 2025-06-18)
Обработано offset 1300, собрано 1400 постов (последний: 2025-05-26)
Обработано offset 1400, собрано 1500 постов (последний: 2025-04-25)
Обработано offset 1500, собрано 1600 постов (последний: 2025-04-04)
Обработано offset 1600, собрано 1700 постов (последний: 2025-03-14)
Обработано offset 1700, собрано 1800 постов (последний: 2025-02-17)
Обработано offset 1800, собрано 1900 постов (последний: 2025-01-23)
Обработано offset 1900, собрано 2000 постов (последний: 2024-12-17)
Обработано offset 2000, собрано 2100 постов (последний: 2024-11-20)
Обработано offset 2100, собрано 2200 постов (последний: 2024-10-23)
Обработано offset 2200, собрано 2300 постов (последний: 2024-09-23)
Обработано offset 2300, собрано 2400 постов (последний: 2024-08-22)
Обработано offset 2400, собрано 2500 постов (последний: 2024-07-08)
Обработано offset 2500, собрано 2600 постов (последний: 2024-06-03)
Обработано offset 2600, собрано 2700 постов (последний: 2024-04-22)
Обработано offset 2700, собрано 2800 постов (последний: 2024-03-20)
Обработано offset 2800, собрано 2900 постов (последний: 2024-01-19)
Обработано offset 2900, собрано 3000 постов (последний: 2023-11-08)
Обработано offset 3000, собрано 3100 постов (последний: 2023-09-28)
Обработано offset 3100, собрано 3200 постов (последний: 2023-07-27)
Обработано offset 3200, собрано 3300 постов (последний: 2023-06-16)
Обработано offset 3300, собрано 3400 постов (последний: 2023-05-15)
Обработано offset 3400, собрано 3500 постов (последний: 2023-04-11)
Обработано offset 3500, собрано 3600 постов (последний: 2023-03-17)
Обработано offset 3600, собрано 3700 постов (последний: 2023-02-21)
Обработано offset 3700, собрано 3800 постов (последний: 2023-01-20)
Обработано offset 3800, собрано 3900 постов (последний: 2022-12-15)
Обработано offset 3900, собрано 4000 постов (последний: 2022-11-22)
Обработано offset 4000, собрано 4100 постов (последний: 2022-10-28)
Обработано offset 4100, собрано 4200 постов (последний: 2022-10-07)
Обработано offset 4200, собрано 4300 постов (последний: 2022-09-15)
Обработано offset 4300, собрано 4400 постов (последний: 2022-08-13)
Обработано offset 4400, собрано 4500 постов (последний: 2022-07-11)
Обработано offset 4500, собрано 4600 постов (последний: 2022-06-08)
Обработано offset 4600, собрано 4700 постов (последний: 2022-05-23)
Обработано offset 4700, собрано 4800 постов (последний: 2022-05-07)
Обработано offset 4800, собрано 4900 постов (последний: 2022-04-18)
Обработано offset 4900, собрано 5000 постов (последний: 2022-04-01)
Обработано offset 5000, собрано 5100 постов (последний: 2022-03-10)
Обработано offset 5100, собрано 5200 постов (последний: 2022-02-11)
Обработано offset 5200, собрано 5300 постов (последний: 2022-01-19)
Обработано offset 5300, собрано 5400 постов (последний: 2021-12-21)
Обработано offset 5400, собрано 5500 постов (последний: 2021-12-06)
Обработано offset 5500, собрано 5600 постов (последний: 2021-11-16)
Обработано offset 5600, собрано 5700 постов (последний: 2021-10-22)
Обработано offset 5700, собрано 5800 постов (последний: 2021-10-06)
Обработано offset 5800, собрано 5900 постов (последний: 2021-09-15)
Обработано offset 5900, собрано 6000 постов (последний: 2021-08-10)
Обработано offset 6000, собрано 6100 постов (последний: 2021-07-12)
Обработано offset 6100, собрано 6200 постов (последний: 2021-06-22)
Обработано offset 6200, собрано 6300 постов (последний: 2021-05-25)
Обработано offset 6300, собрано 6400 постов (последний: 2021-04-27)
Обработано offset 6400, собрано 6500 постов (последний: 2021-04-09)
Обработано offset 6500, собрано 6600 постов (последний: 2021-03-19)
Обработано offset 6600, собрано 6700 постов (последний: 2021-02-26)
Обработано offset 6700, собрано 6800 постов (последний: 2021-01-28)
Обработано offset 6800, собрано 6900 постов (последний: 2020-12-29)
Обработано offset 6900, собрано 7000 постов (последний: 2020-12-04)
Обработано offset 7000, собрано 7100 постов (последний: 2020-11-09)
Обработано offset 7100, собрано 7200 постов (последний: 2020-09-29)
Обработано offset 7200, собрано 7300 постов (последний: 2020-08-31)
Обработано offset 7300, собрано 7400 постов (последний: 2020-07-14)
Обработано offset 7400, собрано 7500 постов (последний: 2020-06-05)
Обработано offset 7500, собрано 7600 постов (последний: 2020-05-12)
Обработано offset 7600, собрано 7700 постов (последний: 2020-04-21)
Обработано offset 7700, собрано 7800 постов (последний: 2020-03-30)
Обработано offset 7800, собрано 7900 постов (последний: 2020-02-28)
Обработано offset 7900, собрано 8000 постов (последний: 2020-01-28)

- Достигли 2019 года -
Последний пост: 5147 от 2019-12-31
Всего собрано постов: 8045
Диапазон дат: 2020-01-07 - 2026-05-06

In [ ]:
# станкин
group_id = '-1332509'
name = 'stankin.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-16)
Обработано offset 100, собрано 200 постов (последний: 2026-03-28)
Обработано offset 200, собрано 300 постов (последний: 2026-03-09)
Обработано offset 300, собрано 400 постов (последний: 2026-02-18)
Обработано offset 400, собрано 500 постов (последний: 2026-01-30)
Обработано offset 500, собрано 600 постов (последний: 2026-01-09)
Обработано offset 600, собрано 700 постов (последний: 2025-12-19)
Обработано offset 700, собрано 800 постов (последний: 2025-12-01)
Обработано offset 800, собрано 900 постов (последний: 2025-11-12)
Обработано offset 900, собрано 1000 постов (последний: 2025-10-23)
Обработано offset 1000, собрано 1100 постов (последний: 2025-10-04)
Обработано offset 1100, собрано 1200 постов (последний: 2025-09-14)
Обработано offset 1200, собрано 1300 постов (последний: 2025-08-21)
Обработано offset 1300, собрано 1400 постов (последний: 2025-07-21)
Обработано offset 1400, собрано 1500 постов (последний: 2025-06-21)
Обработано offset 1500, собрано 1600 постов (последний: 2025-05-24)
Обработано offset 1600, собрано 1700 постов (последний: 2025-05-02)
Обработано offset 1700, собрано 1800 постов (последний: 2025-04-09)
Обработано offset 1800, собрано 1900 постов (последний: 2025-03-17)
Обработано offset 1900, собрано 2000 постов (последний: 2025-02-27)
Обработано offset 2000, собрано 2100 постов (последний: 2025-02-08)
Обработано offset 2100, собрано 2200 постов (последний: 2025-01-19)
Обработано offset 2200, собрано 2300 постов (последний: 2024-12-28)
Обработано offset 2300, собрано 2400 постов (последний: 2024-12-11)
Обработано offset 2400, собрано 2500 постов (последний: 2024-11-25)
Обработано offset 2500, собрано 2600 постов (последний: 2024-11-07)
Обработано offset 2600, собрано 2700 постов (последний: 2024-10-19)
Обработано offset 2700, собрано 2800 постов (последний: 2024-09-30)
Обработано offset 2800, собрано 2900 постов (последний: 2024-09-12)
Обработано offset 2900, собрано 3000 постов (последний: 2024-08-21)
Обработано offset 3000, собрано 3100 постов (последний: 2024-07-28)
Обработано offset 3100, собрано 3200 постов (последний: 2024-07-10)
Обработано offset 3200, собрано 3300 постов (последний: 2024-06-21)
Обработано offset 3300, собрано 3400 постов (последний: 2024-06-03)
Обработано offset 3400, собрано 3500 постов (последний: 2024-05-16)
Обработано offset 3500, собрано 3600 постов (последний: 2024-04-28)
Обработано offset 3600, собрано 3700 постов (последний: 2024-04-09)
Обработано offset 3700, собрано 3800 постов (последний: 2024-03-21)
Обработано offset 3800, собрано 3900 постов (последний: 2024-03-02)
Обработано offset 3900, собрано 4000 постов (последний: 2024-02-12)
Обработано offset 4000, собрано 4100 постов (последний: 2024-01-24)
Обработано offset 4100, собрано 4200 постов (последний: 2023-12-30)
Обработано offset 4200, собрано 4300 постов (последний: 2023-12-12)
Обработано offset 4300, собрано 4400 постов (последний: 2023-11-23)
Обработано offset 4400, собрано 4500 постов (последний: 2023-11-04)
Обработано offset 4500, собрано 4600 постов (последний: 2023-10-17)
Обработано offset 4600, собрано 4700 постов (последний: 2023-09-28)
Обработано offset 4700, собрано 4800 постов (последний: 2023-09-08)
Обработано offset 4800, собрано 4900 постов (последний: 2023-08-20)
Обработано offset 4900, собрано 5000 постов (последний: 2023-07-28)
Обработано offset 5000, собрано 5100 постов (последний: 2023-07-07)
Обработано offset 5100, собрано 5200 постов (последний: 2023-06-18)
Обработано offset 5200, собрано 5300 постов (последний: 2023-05-27)
Обработано offset 5300, собрано 5400 постов (последний: 2023-05-02)
Обработано offset 5400, собрано 5500 постов (последний: 2023-04-10)
Обработано offset 5500, собрано 5600 постов (последний: 2023-03-16)
Обработано offset 5600, собрано 5700 постов (последний: 2023-02-15)
Обработано offset 5700, собрано 5800 постов (последний: 2023-01-15)
Обработано offset 5800, собрано 5900 постов (последний: 2022-12-13)
Обработано offset 5900, собрано 6000 постов (последний: 2022-11-14)
Обработано offset 6000, собрано 6100 постов (последний: 2022-10-19)
Обработано offset 6100, собрано 6200 постов (последний: 2022-09-14)
Обработано offset 6200, собрано 6300 постов (последний: 2022-08-05)
Обработано offset 6300, собрано 6400 постов (последний: 2022-07-01)
Обработано offset 6400, собрано 6500 постов (последний: 2022-06-06)
Обработано offset 6500, собрано 6600 постов (последний: 2022-05-14)
Обработано offset 6600, собрано 6700 постов (последний: 2022-04-18)
Обработано offset 6700, собрано 6800 постов (последний: 2022-03-25)
Обработано offset 6800, собрано 6900 постов (последний: 2022-02-24)
Обработано offset 6900, собрано 7000 постов (последний: 2022-01-24)
Обработано offset 7000, собрано 7100 постов (последний: 2021-12-16)
Обработано offset 7100, собрано 7200 постов (последний: 2021-11-16)
Обработано offset 7200, собрано 7300 постов (последний: 2021-10-19)
Обработано offset 7300, собрано 7400 постов (последний: 2021-09-12)
Обработано offset 7400, собрано 7500 постов (последний: 2021-08-10)
Обработано offset 7500, собрано 7600 постов (последний: 2021-06-24)
Обработано offset 7600, собрано 7700 постов (последний: 2021-05-13)
Обработано offset 7700, собрано 7800 постов (последний: 2021-04-08)
Обработано offset 7800, собрано 7900 постов (последний: 2021-03-03)
Обработано offset 7900, собрано 8000 постов (последний: 2021-01-24)
Обработано offset 8000, собрано 8100 постов (последний: 2020-12-13)
Обработано offset 8100, собрано 8200 постов (последний: 2020-11-19)
Обработано offset 8200, собрано 8300 постов (последний: 2020-10-29)
Обработано offset 8300, собрано 8400 постов (последний: 2020-09-28)
Обработано offset 8400, собрано 8500 постов (последний: 2020-08-19)
Обработано offset 8500, собрано 8600 постов (последний: 2020-07-13)
Обработано offset 8600, собрано 8700 постов (последний: 2020-05-09)
Обработано offset 8700, собрано 8800 постов (последний: 2020-02-26)

- Достигли 2019 года -
Последний пост: 11277 от 2019-12-31
Всего собрано постов: 8830
Диапазон дат: 2020-01-13 - 2026-05-06

In [ ]:
# мгусит
group_id = '-30016632'
name = 'mgusit.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-23)
Обработано offset 100, собрано 200 постов (последний: 2026-04-14)
Обработано offset 200, собрано 300 постов (последний: 2026-04-03)
Обработано offset 300, собрано 400 постов (последний: 2026-03-24)
Обработано offset 400, собрано 500 постов (последний: 2026-03-10)
Обработано offset 500, собрано 600 постов (последний: 2026-02-24)
Обработано offset 600, собрано 700 постов (последний: 2026-02-10)
Обработано offset 700, собрано 800 постов (последний: 2026-01-29)
Обработано offset 800, собрано 900 постов (последний: 2026-01-12)
Обработано offset 900, собрано 1000 постов (последний: 2025-12-23)
Обработано offset 1000, собрано 1100 постов (последний: 2025-12-09)
Обработано offset 1100, собрано 1200 постов (последний: 2025-11-28)
Обработано offset 1200, собрано 1300 постов (последний: 2025-11-17)
Обработано offset 1300, собрано 1400 постов (последний: 2025-11-04)
Обработано offset 1400, собрано 1500 постов (последний: 2025-10-24)
Обработано offset 1500, собрано 1600 постов (последний: 2025-10-13)
Обработано offset 1600, собрано 1700 постов (последний: 2025-09-30)
Обработано offset 1700, собрано 1800 постов (последний: 2025-09-19)
Обработано offset 1800, собрано 1900 постов (последний: 2025-09-04)
Обработано offset 1900, собрано 2000 постов (последний: 2025-08-14)
Обработано offset 2000, собрано 2100 постов (последний: 2025-07-29)
Обработано offset 2100, собрано 2200 постов (последний: 2025-07-14)
Обработано offset 2200, собрано 2300 постов (последний: 2025-07-02)
Обработано offset 2300, собрано 2400 постов (последний: 2025-06-19)
Обработано offset 2400, собрано 2500 постов (последний: 2025-06-05)
Обработано offset 2500, собрано 2600 постов (последний: 2025-05-24)
Обработано offset 2600, собрано 2700 постов (последний: 2025-05-13)
Обработано offset 2700, собрано 2800 постов (последний: 2025-04-26)
Обработано offset 2800, собрано 2900 постов (последний: 2025-04-18)
Обработано offset 2900, собрано 3000 постов (последний: 2025-04-08)
Обработано offset 3000, собрано 3100 постов (последний: 2025-03-28)
Обработано offset 3100, собрано 3200 постов (последний: 2025-03-18)
Обработано offset 3200, собрано 3300 постов (последний: 2025-03-07)
Обработано offset 3300, собрано 3400 постов (последний: 2025-02-26)
Обработано offset 3400, собрано 3500 постов (последний: 2025-02-16)
Обработано offset 3500, собрано 3600 постов (последний: 2025-02-03)
Обработано offset 3600, собрано 3700 постов (последний: 2025-01-23)
Обработано offset 3700, собрано 3800 постов (последний: 2025-01-04)
Обработано offset 3800, собрано 3900 постов (последний: 2024-12-20)
Обработано offset 3900, собрано 4000 постов (последний: 2024-12-09)
Обработано offset 4000, собрано 4100 постов (последний: 2024-11-28)
Обработано offset 4100, собрано 4200 постов (последний: 2024-11-18)
Обработано offset 4200, собрано 4300 постов (последний: 2024-11-05)
Обработано offset 4300, собрано 4400 постов (последний: 2024-10-25)
Обработано offset 4400, собрано 4500 постов (последний: 2024-10-16)
Обработано offset 4500, собрано 4600 постов (последний: 2024-10-05)
Обработано offset 4600, собрано 4700 постов (последний: 2024-09-23)
Обработано offset 4700, собрано 4800 постов (последний: 2024-09-11)
Обработано offset 4800, собрано 4900 постов (последний: 2024-08-29)
Обработано offset 4900, собрано 5000 постов (последний: 2024-08-12)
Обработано offset 5000, собрано 5100 постов (последний: 2024-07-30)
Обработано offset 5100, собрано 5200 постов (последний: 2024-07-12)
Обработано offset 5200, собрано 5300 постов (последний: 2024-07-02)
Обработано offset 5300, собрано 5400 постов (последний: 2024-06-20)
Обработано offset 5400, собрано 5500 постов (последний: 2024-06-11)
Обработано offset 5500, собрано 5600 постов (последний: 2024-06-03)
Обработано offset 5600, собрано 5700 постов (последний: 2024-05-23)
Обработано offset 5700, собрано 5800 постов (последний: 2024-05-14)
Обработано offset 5800, собрано 5900 постов (последний: 2024-04-27)
Обработано offset 5900, собрано 6000 постов (последний: 2024-04-17)
Обработано offset 6000, собрано 6100 постов (последний: 2024-04-09)
Обработано offset 6100, собрано 6200 постов (последний: 2024-03-29)
Обработано offset 6200, собрано 6300 постов (последний: 2024-03-18)
Обработано offset 6300, собрано 6400 постов (последний: 2024-03-07)
Обработано offset 6400, собрано 6500 постов (последний: 2024-02-26)
Обработано offset 6500, собрано 6600 постов (последний: 2024-02-14)
Обработано offset 6600, собрано 6700 постов (последний: 2024-02-03)
Обработано offset 6700, собрано 6800 постов (последний: 2024-01-24)
Обработано offset 6800, собрано 6900 постов (последний: 2024-01-11)
Обработано offset 6900, собрано 7000 постов (последний: 2023-12-25)
Обработано offset 7000, собрано 7100 постов (последний: 2023-12-13)
Обработано offset 7100, собрано 7200 постов (последний: 2023-12-05)
Обработано offset 7200, собрано 7300 постов (последний: 2023-11-26)
Обработано offset 7300, собрано 7400 постов (последний: 2023-11-16)
Обработано offset 7400, собрано 7500 постов (последний: 2023-11-05)
Обработано offset 7500, собрано 7600 постов (последний: 2023-10-26)
Обработано offset 7600, собрано 7700 постов (последний: 2023-10-14)
Обработано offset 7700, собрано 7800 постов (последний: 2023-10-05)
Обработано offset 7800, собрано 7900 постов (последний: 2023-09-25)
Обработано offset 7900, собрано 8000 постов (последний: 2023-09-14)
Обработано offset 8000, собрано 8100 постов (последний: 2023-09-02)
Обработано offset 8100, собрано 8200 постов (последний: 2023-08-19)
Обработано offset 8200, собрано 8300 постов (последний: 2023-07-29)
Обработано offset 8300, собрано 8400 постов (последний: 2023-07-12)
Обработано offset 8400, собрано 8500 постов (последний: 2023-06-28)
Обработано offset 8500, собрано 8600 постов (последний: 2023-06-15)
Обработано offset 8600, собрано 8700 постов (последний: 2023-06-01)
Обработано offset 8700, собрано 8800 постов (последний: 2023-05-23)
Обработано offset 8800, собрано 8900 постов (последний: 2023-05-05)
Обработано offset 8900, собрано 9000 постов (последний: 2023-04-21)
Обработано offset 9000, собрано 9100 постов (последний: 2023-04-10)
Обработано offset 9100, собрано 9200 постов (последний: 2023-03-24)
Обработано offset 9200, собрано 9300 постов (последний: 2023-03-09)
Обработано offset 9300, собрано 9400 постов (последний: 2023-02-18)
Обработано offset 9400, собрано 9500 постов (последний: 2023-01-31)
Обработано offset 9500, собрано 9600 постов (последний: 2023-01-12)
Обработано offset 9600, собрано 9700 постов (последний: 2022-12-21)
Обработано offset 9700, собрано 9800 постов (последний: 2022-12-05)
Обработано offset 9800, собрано 9900 постов (последний: 2022-11-12)
Обработано offset 9900, собрано 10000 постов (последний: 2022-10-22)
Обработано offset 10000, собрано 10100 постов (последний: 2022-09-29)
Обработано offset 10100, собрано 10200 постов (последний: 2022-09-10)
Обработано offset 10200, собрано 10300 постов (последний: 2022-08-12)
Обработано offset 10300, собрано 10400 постов (последний: 2022-07-04)
Обработано offset 10400, собрано 10500 постов (последний: 2022-06-07)
Обработано offset 10500, собрано 10600 постов (последний: 2022-05-16)
Обработано offset 10600, собрано 10700 постов (последний: 2022-04-12)
Обработано offset 10700, собрано 10800 постов (последний: 2022-03-04)
Обработано offset 10800, собрано 10900 постов (последний: 2022-01-21)
Обработано offset 10900, собрано 11000 постов (последний: 2021-11-26)

- Достигли 2019 года -
Последний пост: 2786 от 2019-12-27
Всего собрано постов: 11099
Диапазон дат: 2020-01-24 - 2026-05-06

In [ ]:
# ргсу
group_id = '-39683739'
name = 'rgsu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-09)
Обработано offset 100, собрано 200 постов (последний: 2026-03-09)
Обработано offset 200, собрано 300 постов (последний: 2026-02-08)
Обработано offset 300, собрано 400 постов (последний: 2026-01-03)
Обработано offset 400, собрано 500 постов (последний: 2025-12-07)
Обработано offset 500, собрано 600 постов (последний: 2025-11-14)
Обработано offset 600, собрано 700 постов (последний: 2025-10-14)
Обработано offset 700, собрано 800 постов (последний: 2025-09-15)
Обработано offset 800, собрано 900 постов (последний: 2025-08-17)
Обработано offset 900, собрано 1000 постов (последний: 2025-07-10)
Обработано offset 1000, собрано 1100 постов (последний: 2025-06-19)
Обработано offset 1100, собрано 1200 постов (последний: 2025-06-04)
Обработано offset 1200, собрано 1300 постов (последний: 2025-05-13)
Обработано offset 1300, собрано 1400 постов (последний: 2025-04-16)
Обработано offset 1400, собрано 1500 постов (последний: 2025-03-20)
Обработано offset 1500, собрано 1600 постов (последний: 2025-02-24)
Обработано offset 1600, собрано 1700 постов (последний: 2025-02-03)
Обработано offset 1700, собрано 1800 постов (последний: 2025-01-10)
Обработано offset 1800, собрано 1900 постов (последний: 2024-12-13)
Обработано offset 1900, собрано 2000 постов (последний: 2024-11-21)
Обработано offset 2000, собрано 2100 постов (последний: 2024-10-29)
Обработано offset 2100, собрано 2200 постов (последний: 2024-09-29)
Обработано offset 2200, собрано 2300 постов (последний: 2024-09-04)
Обработано offset 2300, собрано 2400 постов (последний: 2024-08-12)
Обработано offset 2400, собрано 2500 постов (последний: 2024-07-14)
Обработано offset 2500, собрано 2600 постов (последний: 2024-06-20)
Обработано offset 2600, собрано 2700 постов (последний: 2024-05-25)
Обработано offset 2700, собрано 2800 постов (последний: 2024-04-25)
Обработано offset 2800, собрано 2900 постов (последний: 2024-03-23)
Обработано offset 2900, собрано 3000 постов (последний: 2024-02-15)
Обработано offset 3000, собрано 3100 постов (последний: 2024-01-06)
Обработано offset 3100, собрано 3200 постов (последний: 2023-12-01)
Обработано offset 3200, собрано 3300 постов (последний: 2023-11-01)
Обработано offset 3300, собрано 3400 постов (последний: 2023-09-27)
Обработано offset 3400, собрано 3500 постов (последний: 2023-08-25)
Обработано offset 3500, собрано 3600 постов (последний: 2023-07-17)
Обработано offset 3600, собрано 3700 постов (последний: 2023-06-06)
Обработано offset 3700, собрано 3800 постов (последний: 2023-04-13)
Обработано offset 3800, собрано 3900 постов (последний: 2023-03-07)
Обработано offset 3900, собрано 4000 постов (последний: 2023-01-31)
Обработано offset 4000, собрано 4100 постов (последний: 2022-12-29)
Обработано offset 4100, собрано 4200 постов (последний: 2022-11-23)
Обработано offset 4200, собрано 4300 постов (последний: 2022-10-20)
Обработано offset 4300, собрано 4400 постов (последний: 2022-09-15)
Обработано offset 4400, собрано 4500 постов (последний: 2022-07-11)
Обработано offset 4500, собрано 4600 постов (последний: 2022-05-19)
Обработано offset 4600, собрано 4700 постов (последний: 2022-03-18)
Обработано offset 4700, собрано 4800 постов (последний: 2021-11-12)
Обработано offset 4800, собрано 4900 постов (последний: 2021-03-29)
Обработано offset 4900, собрано 5000 постов (последний: 2020-11-09)
Обработано offset 5000, собрано 5100 постов (последний: 2020-02-03)

- Достигли 2019 года -
Последний пост: 12091 от 2019-12-31
Всего собрано постов: 5115
Диапазон дат: 2020-01-23 - 2026-05-06

In [ ]:
# росбиотех
group_id = '-168484484'
name = 'rosbiotech.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-20)
Обработано offset 100, собрано 200 постов (последний: 2026-01-27)
Обработано offset 200, собрано 300 постов (последний: 2025-12-05)
Обработано offset 300, собрано 400 постов (последний: 2025-10-24)
Обработано offset 400, собрано 500 постов (последний: 2025-09-15)
Обработано offset 500, собрано 600 постов (последний: 2025-08-02)
Обработано offset 600, собрано 700 постов (последний: 2025-06-16)
Обработано offset 700, собрано 800 постов (последний: 2025-05-05)
Обработано offset 800, собрано 900 постов (последний: 2025-03-24)
Обработано offset 900, собрано 1000 постов (последний: 2025-01-29)
Обработано offset 1000, собрано 1100 постов (последний: 2024-12-09)
Обработано offset 1100, собрано 1200 постов (последний: 2024-11-02)
Обработано offset 1200, собрано 1300 постов (последний: 2024-10-08)
Обработано offset 1300, собрано 1400 постов (последний: 2024-09-03)
Обработано offset 1400, собрано 1500 постов (последний: 2024-07-20)
Обработано offset 1500, собрано 1600 постов (последний: 2024-06-09)
Обработано offset 1600, собрано 1700 постов (последний: 2024-05-15)
Обработано offset 1700, собрано 1800 постов (последний: 2024-04-13)
Обработано offset 1800, собрано 1900 постов (последний: 2024-03-18)
Обработано offset 1900, собрано 2000 постов (последний: 2024-02-15)
Обработано offset 2000, собрано 2100 постов (последний: 2024-01-19)
Обработано offset 2100, собрано 2200 постов (последний: 2023-12-16)
Обработано offset 2200, собрано 2300 постов (последний: 2023-11-22)
Обработано offset 2300, собрано 2400 постов (последний: 2023-10-20)
Обработано offset 2400, собрано 2500 постов (последний: 2023-09-03)
Обработано offset 2500, собрано 2600 постов (последний: 2023-07-12)
Обработано offset 2600, собрано 2700 постов (последний: 2023-06-08)
Обработано offset 2700, собрано 2800 постов (последний: 2023-05-18)
Обработано offset 2800, собрано 2900 постов (последний: 2023-04-24)
Обработано offset 2900, собрано 3000 постов (последний: 2023-04-03)
Обработано offset 3000, собрано 3100 постов (последний: 2023-03-03)
Обработано offset 3100, собрано 3200 постов (последний: 2023-02-08)
Обработано offset 3200, собрано 3300 постов (последний: 2023-01-11)
Обработано offset 3300, собрано 3400 постов (последний: 2022-12-06)
Обработано offset 3400, собрано 3500 постов (последний: 2022-11-18)
Обработано offset 3500, собрано 3600 постов (последний: 2022-10-30)
Обработано offset 3600, собрано 3700 постов (последний: 2022-10-12)
Обработано offset 3700, собрано 3800 постов (последний: 2022-09-19)
Обработано offset 3800, собрано 3900 постов (последний: 2022-09-01)
Обработано offset 3900, собрано 4000 постов (последний: 2022-08-01)
Обработано offset 4000, собрано 4100 постов (последний: 2022-07-10)
Обработано offset 4100, собрано 4200 постов (последний: 2022-06-08)
Обработано offset 4200, собрано 4300 постов (последний: 2022-05-20)
Обработано offset 4300, собрано 4400 постов (последний: 2022-05-05)
Обработано offset 4400, собрано 4500 постов (последний: 2022-04-18)
Обработано offset 4500, собрано 4600 постов (последний: 2022-04-01)
Обработано offset 4600, собрано 4700 постов (последний: 2022-03-11)
Обработано offset 4700, собрано 4800 постов (последний: 2022-02-11)
Обработано offset 4800, собрано 4900 постов (последний: 2021-12-31)
Обработано offset 4900, собрано 5000 постов (последний: 2021-12-01)
Обработано offset 5000, собрано 5100 постов (последний: 2021-11-09)
Обработано offset 5100, собрано 5200 постов (последний: 2021-10-11)
Обработано offset 5200, собрано 5300 постов (последний: 2021-09-08)
Обработано offset 5300, собрано 5400 постов (последний: 2021-08-03)
Обработано offset 5400, собрано 5500 постов (последний: 2021-07-06)
Обработано offset 5500, собрано 5600 постов (последний: 2021-06-08)
Обработано offset 5600, собрано 5700 постов (последний: 2021-05-09)
Обработано offset 5700, собрано 5800 постов (последний: 2021-04-16)
Обработано offset 5800, собрано 5900 постов (последний: 2021-03-25)
Обработано offset 5900, собрано 6000 постов (последний: 2021-02-26)
Обработано offset 6000, собрано 6100 постов (последний: 2021-02-02)
Обработано offset 6100, собрано 6200 постов (последний: 2020-12-17)
Обработано offset 6200, собрано 6300 постов (последний: 2020-11-13)
Обработано offset 6300, собрано 6400 постов (последний: 2020-10-08)
Обработано offset 6400, собрано 6500 постов (последний: 2020-08-28)
Обработано offset 6500, собрано 6600 постов (последний: 2020-07-14)
Обработано offset 6600, собрано 6700 постов (последний: 2020-05-26)
Обработано offset 6700, собрано 6800 постов (последний: 2020-04-22)
Обработано offset 6800, собрано 6900 постов (последний: 2020-03-25)
Обработано offset 6900, собрано 7000 постов (последний: 2020-01-17)

- Достигли 2019 года -
Последний пост: 796 от 2019-12-31
Всего собрано постов: 7003
Диапазон дат: 2020-01-14 - 2026-05-06

In [ ]:
# миит
group_id = '-159'
name = 'miit.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2025-12-25)
Обработано offset 100, собрано 200 постов (последний: 2025-10-15)
Обработано offset 200, собрано 300 постов (последний: 2025-07-07)
Обработано offset 300, собрано 400 постов (последний: 2025-04-17)
Обработано offset 400, собрано 500 постов (последний: 2025-02-03)
Обработано offset 500, собрано 600 постов (последний: 2024-11-20)
Обработано offset 600, собрано 700 постов (последний: 2024-09-20)
Обработано offset 700, собрано 800 постов (последний: 2024-06-20)
Обработано offset 800, собрано 900 постов (последний: 2024-03-15)
Обработано offset 900, собрано 1000 постов (последний: 2023-11-20)
Обработано offset 1000, собрано 1100 постов (последний: 2023-09-07)
Обработано offset 1100, собрано 1200 постов (последний: 2023-05-05)
Обработано offset 1200, собрано 1300 постов (последний: 2023-02-15)
Обработано offset 1300, собрано 1400 постов (последний: 2022-11-16)
Обработано offset 1400, собрано 1500 постов (последний: 2022-09-09)
Обработано offset 1500, собрано 1600 постов (последний: 2022-06-30)
Обработано offset 1600, собрано 1700 постов (последний: 2022-05-13)
Обработано offset 1700, собрано 1800 постов (последний: 2022-03-14)
Обработано offset 1800, собрано 1900 постов (последний: 2021-12-13)
Обработано offset 1900, собрано 2000 постов (последний: 2021-10-15)
Обработано offset 2000, собрано 2100 постов (последний: 2021-07-30)
Обработано offset 2100, собрано 2200 постов (последний: 2021-05-08)
Обработано offset 2200, собрано 2300 постов (последний: 2021-02-23)
Обработано offset 2300, собрано 2400 постов (последний: 2020-12-03)
Обработано offset 2400, собрано 2500 постов (последний: 2020-10-14)
Обработано offset 2500, собрано 2600 постов (последний: 2020-08-26)
Обработано offset 2600, собрано 2700 постов (последний: 2020-06-23)
Обработано offset 2700, собрано 2800 постов (последний: 2020-04-29)
Обработано offset 2800, собрано 2900 постов (последний: 2020-03-02)

- Достигли 2019 года -
Последний пост: 78209 от 2019-12-30
Всего собрано постов: 2995
Диапазон дат: 2020-01-09 - 2026-05-06

In [ ]:
# дип академия
group_id = '-181211182'
name = 'dipacademy.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-02)
Обработано offset 100, собрано 200 постов (последний: 2026-02-13)
Обработано offset 200, собрано 300 постов (последний: 2026-01-12)
Обработано offset 300, собрано 400 постов (последний: 2025-12-10)
Обработано offset 400, собрано 500 постов (последний: 2025-11-17)
Обработано offset 500, собрано 600 постов (последний: 2025-10-23)
Обработано offset 600, собрано 700 постов (последний: 2025-10-02)
Обработано offset 700, собрано 800 постов (последний: 2025-09-05)
Обработано offset 800, собрано 900 постов (последний: 2025-07-09)
Обработано offset 900, собрано 1000 постов (последний: 2025-06-10)
Обработано offset 1000, собрано 1100 постов (последний: 2025-05-19)
Обработано offset 1100, собрано 1200 постов (последний: 2025-04-24)
Обработано offset 1200, собрано 1300 постов (последний: 2025-04-02)
Обработано offset 1300, собрано 1400 постов (последний: 2025-03-14)
Обработано offset 1400, собрано 1500 постов (последний: 2025-02-20)
Обработано offset 1500, собрано 1600 постов (последний: 2025-01-31)
Обработано offset 1600, собрано 1700 постов (последний: 2024-12-24)
Обработано offset 1700, собрано 1800 постов (последний: 2024-12-06)
Обработано offset 1800, собрано 1900 постов (последний: 2024-11-18)
Обработано offset 1900, собрано 2000 постов (последний: 2024-10-29)
Обработано offset 2000, собрано 2100 постов (последний: 2024-10-14)
Обработано offset 2100, собрано 2200 постов (последний: 2024-09-27)
Обработано offset 2200, собрано 2300 постов (последний: 2024-09-04)
Обработано offset 2300, собрано 2400 постов (последний: 2024-07-19)
Обработано offset 2400, собрано 2500 постов (последний: 2024-06-19)
Обработано offset 2500, собрано 2600 постов (последний: 2024-05-28)
Обработано offset 2600, собрано 2700 постов (последний: 2024-05-08)
Обработано offset 2700, собрано 2800 постов (последний: 2024-04-16)
Обработано offset 2800, собрано 2900 постов (последний: 2024-03-27)
Обработано offset 2900, собрано 3000 постов (последний: 2024-03-05)
Обработано offset 3000, собрано 3100 постов (последний: 2024-02-15)
Обработано offset 3100, собрано 3200 постов (последний: 2024-02-01)
Обработано offset 3200, собрано 3300 постов (последний: 2023-12-22)
Обработано offset 3300, собрано 3400 постов (последний: 2023-12-06)
Обработано offset 3400, собрано 3500 постов (последний: 2023-11-18)
Обработано offset 3500, собрано 3600 постов (последний: 2023-10-27)
Обработано offset 3600, собрано 3700 постов (последний: 2023-10-13)
Обработано offset 3700, собрано 3800 постов (последний: 2023-09-23)
Обработано offset 3800, собрано 3900 постов (последний: 2023-08-31)
Обработано offset 3900, собрано 4000 постов (последний: 2023-07-19)
Обработано offset 4000, собрано 4100 постов (последний: 2023-06-24)
Обработано offset 4100, собрано 4200 постов (последний: 2023-06-06)
Обработано offset 4200, собрано 4300 постов (последний: 2023-05-19)
Обработано offset 4300, собрано 4400 постов (последний: 2023-04-28)
Обработано offset 4400, собрано 4500 постов (последний: 2023-04-06)
Обработано offset 4500, собрано 4600 постов (последний: 2023-03-17)
Обработано offset 4600, собрано 4700 постов (последний: 2023-02-20)
Обработано offset 4700, собрано 4800 постов (последний: 2023-01-27)
Обработано offset 4800, собрано 4900 постов (последний: 2022-12-23)
Обработано offset 4900, собрано 5000 постов (последний: 2022-12-02)
Обработано offset 5000, собрано 5100 постов (последний: 2022-11-11)
Обработано offset 5100, собрано 5200 постов (последний: 2022-10-23)
Обработано offset 5200, собрано 5300 постов (последний: 2022-10-05)
Обработано offset 5300, собрано 5400 постов (последний: 2022-09-18)
Обработано offset 5400, собрано 5500 постов (последний: 2022-08-18)
Обработано offset 5500, собрано 5600 постов (последний: 2022-07-17)
Обработано offset 5600, собрано 5700 постов (последний: 2022-06-22)
Обработано offset 5700, собрано 5800 постов (последний: 2022-06-02)
Обработано offset 5800, собрано 5900 постов (последний: 2022-05-16)
Обработано offset 5900, собрано 6000 постов (последний: 2022-04-25)
Обработано offset 6000, собрано 6100 постов (последний: 2022-04-08)
Обработано offset 6100, собрано 6200 постов (последний: 2022-03-21)
Обработано offset 6200, собрано 6300 постов (последний: 2022-02-12)
Обработано offset 6300, собрано 6400 постов (последний: 2022-01-20)
Обработано offset 6400, собрано 6500 постов (последний: 2021-12-20)
Обработано offset 6500, собрано 6600 постов (последний: 2021-11-28)
Обработано offset 6600, собрано 6700 постов (последний: 2021-11-07)
Обработано offset 6700, собрано 6800 постов (последний: 2021-10-13)
Обработано offset 6800, собрано 6900 постов (последний: 2021-09-25)
Обработано offset 6900, собрано 7000 постов (последний: 2021-09-02)
Обработано offset 7000, собрано 7100 постов (последний: 2021-08-14)
Обработано offset 7100, собрано 7200 постов (последний: 2021-07-08)
Обработано offset 7200, собрано 7300 постов (последний: 2021-06-07)
Обработано offset 7300, собрано 7400 постов (последний: 2021-05-14)
Обработано offset 7400, собрано 7500 постов (последний: 2021-04-23)
Обработано offset 7500, собрано 7600 постов (последний: 2021-03-31)
Обработано offset 7600, собрано 7700 постов (последний: 2021-03-08)
Обработано offset 7700, собрано 7800 постов (последний: 2021-02-10)
Обработано offset 7800, собрано 7900 постов (последний: 2021-01-12)
Обработано offset 7900, собрано 8000 постов (последний: 2020-12-16)
Обработано offset 8000, собрано 8100 постов (последний: 2020-11-24)
Обработано offset 8100, собрано 8200 постов (последний: 2020-11-02)
Обработано offset 8200, собрано 8300 постов (последний: 2020-10-14)
Обработано offset 8300, собрано 8400 постов (последний: 2020-09-21)
Обработано offset 8400, собрано 8500 постов (последний: 2020-08-30)
Обработано offset 8500, собрано 8600 постов (последний: 2020-07-31)
Обработано offset 8600, собрано 8700 постов (последний: 2020-07-03)
Обработано offset 8700, собрано 8800 постов (последний: 2020-06-09)
Обработано offset 8800, собрано 8900 постов (последний: 2020-05-21)
Обработано offset 8900, собрано 9000 постов (последний: 2020-05-02)
Обработано offset 9000, собрано 9100 постов (последний: 2020-04-10)
Обработано offset 9100, собрано 9200 постов (последний: 2020-02-29)
Обработано offset 9200, собрано 9300 постов (последний: 2020-01-24)

- Достигли 2019 года -
Последний пост: 726 от 2019-12-31
Всего собрано постов: 9334
Диапазон дат: 2020-01-01 - 2026-05-05

In [ ]:
# пстгу
group_id = '-97729'
name = 'pstgu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-14)
Обработано offset 100, собрано 200 постов (последний: 2026-01-13)
Обработано offset 200, собрано 300 постов (последний: 2025-11-15)
Обработано offset 300, собрано 400 постов (последний: 2025-09-23)
Обработано offset 400, собрано 500 постов (последний: 2025-07-19)
Обработано offset 500, собрано 600 постов (последний: 2025-05-28)
Обработано offset 600, собрано 700 постов (последний: 2025-04-08)
Обработано offset 700, собрано 800 постов (последний: 2025-02-16)
Обработано offset 800, собрано 900 постов (последний: 2024-12-30)
Обработано offset 900, собрано 1000 постов (последний: 2024-11-20)
Обработано offset 1000, собрано 1100 постов (последний: 2024-10-11)
Обработано offset 1100, собрано 1200 постов (последний: 2024-08-26)
Обработано offset 1200, собрано 1300 постов (последний: 2024-06-19)
Обработано offset 1300, собрано 1400 постов (последний: 2024-04-23)
Обработано offset 1400, собрано 1500 постов (последний: 2024-03-03)
Обработано offset 1500, собрано 1600 постов (последний: 2024-01-14)
Обработано offset 1600, собрано 1700 постов (последний: 2023-11-19)
Обработано offset 1700, собрано 1800 постов (последний: 2023-09-29)
Обработано offset 1800, собрано 1900 постов (последний: 2023-07-21)
Обработано offset 1900, собрано 2000 постов (последний: 2023-05-21)
Обработано offset 2000, собрано 2100 постов (последний: 2023-03-27)
Обработано offset 2100, собрано 2200 постов (последний: 2023-02-12)
Обработано offset 2200, собрано 2300 постов (последний: 2022-12-30)
Обработано offset 2300, собрано 2400 постов (последний: 2022-11-17)
Обработано offset 2400, собрано 2500 постов (последний: 2022-10-03)
Обработано offset 2500, собрано 2600 постов (последний: 2022-07-31)
Обработано offset 2600, собрано 2700 постов (последний: 2022-05-30)
Обработано offset 2700, собрано 2800 постов (последний: 2022-04-12)
Обработано offset 2800, собрано 2900 постов (последний: 2022-02-21)
Обработано offset 2900, собрано 3000 постов (последний: 2021-12-16)
Обработано offset 3000, собрано 3100 постов (последний: 2021-10-06)
Обработано offset 3100, собрано 3200 постов (последний: 2021-06-17)
Обработано offset 3200, собрано 3300 постов (последний: 2021-04-02)
Обработано offset 3300, собрано 3400 постов (последний: 2021-01-03)
Обработано offset 3400, собрано 3500 постов (последний: 2020-09-20)
Обработано offset 3500, собрано 3600 постов (последний: 2020-05-25)
Обработано offset 3600, собрано 3700 постов (последний: 2020-03-11)

- Достигли 2019 года -
Последний пост: 21495 от 2019-12-31
Всего собрано постов: 3795
Диапазон дат: 2020-01-01 - 2026-05-06

In [ ]:
# мгри
group_id = '-163624433'
name = 'mgri.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-05)
Обработано offset 100, собрано 200 постов (последний: 2026-03-03)
Обработано offset 200, собрано 300 постов (последний: 2026-01-31)
Обработано offset 300, собрано 400 постов (последний: 2025-12-20)
Обработано offset 400, собрано 500 постов (последний: 2025-11-25)
Обработано offset 500, собрано 600 постов (последний: 2025-10-26)
Обработано offset 600, собрано 700 постов (последний: 2025-09-27)
Обработано offset 700, собрано 800 постов (последний: 2025-08-29)
Обработано offset 800, собрано 900 постов (последний: 2025-07-22)
Обработано offset 900, собрано 1000 постов (последний: 2025-06-19)
Обработано offset 1000, собрано 1100 постов (последний: 2025-05-12)
Обработано offset 1100, собрано 1200 постов (последний: 2025-04-11)
Обработано offset 1200, собрано 1300 постов (последний: 2025-03-15)
Обработано offset 1300, собрано 1400 постов (последний: 2025-02-12)
Обработано offset 1400, собрано 1500 постов (последний: 2025-01-14)
Обработано offset 1500, собрано 1600 постов (последний: 2024-12-05)
Обработано offset 1600, собрано 1700 постов (последний: 2024-11-04)
Обработано offset 1700, собрано 1800 постов (последний: 2024-10-10)
Обработано offset 1800, собрано 1900 постов (последний: 2024-09-13)
Обработано offset 1900, собрано 2000 постов (последний: 2024-08-22)
Обработано offset 2000, собрано 2100 постов (последний: 2024-07-21)
Обработано offset 2100, собрано 2200 постов (последний: 2024-06-23)
Обработано offset 2200, собрано 2300 постов (последний: 2024-05-25)
Обработано offset 2300, собрано 2400 постов (последний: 2024-04-26)
Обработано offset 2400, собрано 2500 постов (последний: 2024-04-06)
Обработано offset 2500, собрано 2600 постов (последний: 2024-03-17)
Обработано offset 2600, собрано 2700 постов (последний: 2024-02-21)
Обработано offset 2700, собрано 2800 постов (последний: 2024-01-26)
Обработано offset 2800, собрано 2900 постов (последний: 2023-12-15)
Обработано offset 2900, собрано 3000 постов (последний: 2023-11-03)
Обработано offset 3000, собрано 3100 постов (последний: 2023-09-25)
Обработано offset 3100, собрано 3200 постов (последний: 2023-08-08)
Обработано offset 3200, собрано 3300 постов (последний: 2023-05-20)
Обработано offset 3300, собрано 3400 постов (последний: 2023-03-31)
Обработано offset 3400, собрано 3500 постов (последний: 2023-02-21)
Обработано offset 3500, собрано 3600 постов (последний: 2022-12-19)
Обработано offset 3600, собрано 3700 постов (последний: 2022-11-02)
Обработано offset 3700, собрано 3800 постов (последний: 2022-09-08)
Обработано offset 3800, собрано 3900 постов (последний: 2022-06-29)
Обработано offset 3900, собрано 4000 постов (последний: 2022-04-22)
Обработано offset 4000, собрано 4100 постов (последний: 2022-02-23)
Обработано offset 4100, собрано 4200 постов (последний: 2021-12-24)
Обработано offset 4200, собрано 4300 постов (последний: 2021-11-09)
Обработано offset 4300, собрано 4400 постов (последний: 2021-09-24)
Обработано offset 4400, собрано 4500 постов (последний: 2021-08-18)
Обработано offset 4500, собрано 4600 постов (последний: 2021-06-25)
Обработано offset 4600, собрано 4700 постов (последний: 2021-04-21)
Обработано offset 4700, собрано 4800 постов (последний: 2021-03-16)
Обработано offset 4800, собрано 4900 постов (последний: 2021-02-12)
Обработано offset 4900, собрано 5000 постов (последний: 2020-12-19)
Обработано offset 5000, собрано 5100 постов (последний: 2020-11-18)
Обработано offset 5100, собрано 5200 постов (последний: 2020-10-29)
Обработано offset 5200, собрано 5300 постов (последний: 2020-09-28)
Обработано offset 5300, собрано 5400 постов (последний: 2020-08-25)
Обработано offset 5400, собрано 5500 постов (последний: 2020-06-23)
Обработано offset 5500, собрано 5600 постов (последний: 2020-05-21)
Обработано offset 5600, собрано 5700 постов (последний: 2020-04-16)
Обработано offset 5700, собрано 5800 постов (последний: 2020-03-17)
Обработано offset 5800, собрано 5900 постов (последний: 2020-02-05)

- Достигли 2019 года -
Последний пост: 1637 от 2019-12-31
Всего собрано постов: 5935
Диапазон дат: 2020-01-01 - 2026-05-06

In [ ]:
# балетная академия
group_id = '-211891378'
name = 'balletacademy.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-01-20)
Обработано offset 100, собрано 200 постов (последний: 2025-09-25)
Обработано offset 200, собрано 300 постов (последний: 2025-04-28)
Обработано offset 300, собрано 400 постов (последний: 2025-01-27)
Обработано offset 400, собрано 500 постов (последний: 2024-11-12)
Обработано offset 500, собрано 600 постов (последний: 2023-05-10)
Обработано offset 600, собрано 684 постов (последний: 2022-03-19)
Постов больше нет
Всего собрано постов: 684
Диапазон дат: 2022-03-19 - 2026-05-05

In [ ]:
# гтсолифк
group_id = '-41423'
name = 'gtsolifk.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-01)
Обработано offset 100, собрано 200 постов (последний: 2026-02-26)
Обработано offset 200, собрано 300 постов (последний: 2026-01-27)
Обработано offset 300, собрано 400 постов (последний: 2025-12-15)
Обработано offset 400, собрано 500 постов (последний: 2025-11-19)
Обработано offset 500, собрано 600 постов (последний: 2025-10-25)
Обработано offset 600, собрано 700 постов (последний: 2025-09-29)
Обработано offset 700, собрано 800 постов (последний: 2025-08-28)
Обработано offset 800, собрано 900 постов (последний: 2025-07-04)
Обработано offset 900, собрано 1000 постов (последний: 2025-05-28)
Обработано offset 1000, собрано 1100 постов (последний: 2025-04-29)
Обработано offset 1100, собрано 1200 постов (последний: 2025-04-02)
Обработано offset 1200, собрано 1300 постов (последний: 2025-03-07)
Обработано offset 1300, собрано 1400 постов (последний: 2025-02-11)
Обработано offset 1400, собрано 1500 постов (последний: 2024-12-23)
Обработано offset 1500, собрано 1600 постов (последний: 2024-11-20)
Обработано offset 1600, собрано 1700 постов (последний: 2024-10-14)
Обработано offset 1700, собрано 1800 постов (последний: 2024-08-27)
Обработано offset 1800, собрано 1900 постов (последний: 2024-06-21)
Обработано offset 1900, собрано 2000 постов (последний: 2024-05-22)
Обработано offset 2000, собрано 2100 постов (последний: 2024-04-18)
Обработано offset 2100, собрано 2200 постов (последний: 2024-03-17)
Обработано offset 2200, собрано 2300 постов (последний: 2024-02-12)
Обработано offset 2300, собрано 2400 постов (последний: 2023-12-25)
Обработано offset 2400, собрано 2500 постов (последний: 2023-11-28)
Обработано offset 2500, собрано 2600 постов (последний: 2023-10-27)
Обработано offset 2600, собрано 2700 постов (последний: 2023-09-22)
Обработано offset 2700, собрано 2800 постов (последний: 2023-08-20)
Обработано offset 2800, собрано 2900 постов (последний: 2023-07-03)
Обработано offset 2900, собрано 3000 постов (последний: 2023-05-25)
Обработано offset 3000, собрано 3100 постов (последний: 2023-04-19)
Обработано offset 3100, собрано 3200 постов (последний: 2023-03-20)
Обработано offset 3200, собрано 3300 постов (последний: 2023-02-10)
Обработано offset 3300, собрано 3400 постов (последний: 2022-12-29)
Обработано offset 3400, собрано 3500 постов (последний: 2022-11-29)
Обработано offset 3500, собрано 3600 постов (последний: 2022-10-31)
Обработано offset 3600, собрано 3700 постов (последний: 2022-10-04)
Обработано offset 3700, собрано 3800 постов (последний: 2022-09-05)
Обработано offset 3800, собрано 3900 постов (последний: 2022-08-05)
Обработано offset 3900, собрано 4000 постов (последний: 2022-02-05)
Обработано offset 4000, собрано 4100 постов (последний: 2021-12-27)
Обработано offset 4100, собрано 4200 постов (последний: 2021-11-26)
Обработано offset 4200, собрано 4300 постов (последний: 2021-10-24)
Обработано offset 4300, собрано 4400 постов (последний: 2021-09-28)
Обработано offset 4400, собрано 4500 постов (последний: 2021-08-30)
Обработано offset 4500, собрано 4600 постов (последний: 2021-08-02)
Обработано offset 4600, собрано 4700 постов (последний: 2021-07-10)
Обработано offset 4700, собрано 4800 постов (последний: 2021-06-10)
Обработано offset 4800, собрано 4900 постов (последний: 2021-05-09)
Обработано offset 4900, собрано 5000 постов (последний: 2021-04-09)
Обработано offset 5000, собрано 5100 постов (последний: 2021-03-09)
Обработано offset 5100, собрано 5200 постов (последний: 2021-02-08)
Обработано offset 5200, собрано 5300 постов (последний: 2021-01-07)
Обработано offset 5300, собрано 5400 постов (последний: 2020-12-19)
Обработано offset 5400, собрано 5500 постов (последний: 2020-11-17)
Обработано offset 5500, собрано 5600 постов (последний: 2020-10-16)
Обработано offset 5600, собрано 5700 постов (последний: 2020-09-14)
Обработано offset 5700, собрано 5800 постов (последний: 2020-08-20)
Обработано offset 5800, собрано 5900 постов (последний: 2020-07-26)
Обработано offset 5900, собрано 6000 постов (последний: 2020-06-27)
Обработано offset 6000, собрано 6100 постов (последний: 2020-06-03)
Обработано offset 6100, собрано 6200 постов (последний: 2020-05-13)
Обработано offset 6200, собрано 6300 постов (последний: 2020-04-22)
Обработано offset 6300, собрано 6400 постов (последний: 2020-03-31)
Обработано offset 6400, собрано 6500 постов (последний: 2020-03-12)
Обработано offset 6500, собрано 6600 постов (последний: 2020-02-22)
Обработано offset 6600, собрано 6700 постов (последний: 2020-02-01)
Обработано offset 6700, собрано 6800 постов (последний: 2020-01-13)

- Достигли 2019 года -
Последний пост: 52813 от 2019-12-31
Всего собрано постов: 6839
Диапазон дат: 2020-01-01 - 2026-05-05

In [ ]:
# ргхпу
group_id = '-187809308'
name = 'rghpu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-16)
Обработано offset 100, собрано 200 постов (последний: 2026-01-23)
Обработано offset 200, собрано 300 постов (последний: 2025-11-24)
Обработано offset 300, собрано 400 постов (последний: 2025-10-13)
Обработано offset 400, собрано 500 постов (последний: 2025-08-20)
Обработано offset 500, собрано 600 постов (последний: 2025-06-26)
Обработано offset 600, собрано 700 постов (последний: 2025-05-04)
Обработано offset 700, собрано 800 постов (последний: 2025-03-27)
Обработано offset 800, собрано 900 постов (последний: 2025-02-17)
Обработано offset 900, собрано 1000 постов (последний: 2024-12-26)
Обработано offset 1000, собрано 1100 постов (последний: 2024-11-05)
Обработано offset 1100, собрано 1200 постов (последний: 2024-09-13)
Обработано offset 1200, собрано 1300 постов (последний: 2024-07-01)
Обработано offset 1300, собрано 1400 постов (последний: 2024-05-17)
Обработано offset 1400, собрано 1500 постов (последний: 2024-04-04)
Обработано offset 1500, собрано 1600 постов (последний: 2024-02-26)
Обработано offset 1600, собрано 1700 постов (последний: 2024-01-22)
Обработано offset 1700, собрано 1800 постов (последний: 2023-12-08)
Обработано offset 1800, собрано 1900 постов (последний: 2023-10-02)
Обработано offset 1900, собрано 2000 постов (последний: 2023-05-23)
Обработано offset 2000, собрано 2100 постов (последний: 2023-02-23)
Обработано offset 2100, собрано 2200 постов (последний: 2022-11-15)
Обработано offset 2200, собрано 2300 постов (последний: 2022-07-06)
Обработано offset 2300, собрано 2400 постов (последний: 2022-02-25)
Обработано offset 2400, собрано 2500 постов (последний: 2021-07-05)
Обработано offset 2500, собрано 2600 постов (последний: 2020-10-07)
Обработано offset 2600, собрано 2700 постов (последний: 2020-03-16)

- Достигли 2019 года -
Последний пост: 43 от 2019-12-30
Всего собрано постов: 2731
Диапазон дат: 2020-01-08 - 2026-05-06

In [ ]:
# инсти психоанализа
group_id = '-11290126'
name = 'inpsyho.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-01-18)
Обработано offset 100, собрано 200 постов (последний: 2025-09-15)
Обработано offset 200, собрано 300 постов (последний: 2025-06-04)
Обработано offset 300, собрано 400 постов (последний: 2025-03-17)
Обработано offset 400, собрано 500 постов (последний: 2024-12-27)
Обработано offset 500, собрано 600 постов (последний: 2024-10-10)
Обработано offset 600, собрано 700 постов (последний: 2024-06-12)
Обработано offset 700, собрано 800 постов (последний: 2024-02-27)
Обработано offset 800, собрано 900 постов (последний: 2023-12-19)
Обработано offset 900, собрано 1000 постов (последний: 2023-10-20)
Обработано offset 1000, собрано 1100 постов (последний: 2023-08-29)
Обработано offset 1100, собрано 1200 постов (последний: 2023-06-13)
Обработано offset 1200, собрано 1300 постов (последний: 2023-04-05)
Обработано offset 1300, собрано 1400 постов (последний: 2023-01-09)
Обработано offset 1400, собрано 1500 постов (последний: 2022-10-11)
Обработано offset 1500, собрано 1600 постов (последний: 2022-07-15)
Обработано offset 1600, собрано 1700 постов (последний: 2022-04-07)
Обработано offset 1700, собрано 1800 постов (последний: 2021-11-19)
Обработано offset 1800, собрано 1900 постов (последний: 2021-08-16)
Обработано offset 1900, собрано 2000 постов (последний: 2021-05-10)
Обработано offset 2000, собрано 2100 постов (последний: 2021-02-05)
Обработано offset 2100, собрано 2200 постов (последний: 2020-10-28)
Обработано offset 2200, собрано 2300 постов (последний: 2020-07-31)
Обработано offset 2300, собрано 2400 постов (последний: 2020-04-21)
Обработано offset 2400, собрано 2500 постов (последний: 2020-01-20)

- Достигли 2019 года -
Последний пост: 10160 от 2019-12-31
Всего собрано постов: 2511
Диапазон дат: 2020-01-09 - 2026-05-06

In [ ]:
# мглу
group_id = '-214354323'
name = 'mslu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-16)
Обработано offset 100, собрано 200 постов (последний: 2026-02-09)
Обработано offset 200, собрано 300 постов (последний: 2025-12-18)
Обработано offset 300, собрано 400 постов (последний: 2025-11-02)
Обработано offset 400, собрано 500 постов (последний: 2025-09-10)
Обработано offset 500, собрано 600 постов (последний: 2025-06-27)
Обработано offset 600, собрано 700 постов (последний: 2025-05-15)
Обработано offset 700, собрано 800 постов (последний: 2025-03-28)
Обработано offset 800, собрано 900 постов (последний: 2025-02-03)
Обработано offset 900, собрано 931 постов (последний: 2023-11-06)
Постов больше нет
Всего собрано постов: 931
Диапазон дат: 2023-11-06 - 2026-05-06

In [ ]:
# мадм
group_id = '-138541024'
name = 'madi.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-08)
Обработано offset 100, собрано 200 постов (последний: 2025-12-12)
Обработано offset 200, собрано 300 постов (последний: 2025-07-24)
Обработано offset 300, собрано 400 постов (последний: 2025-03-24)
Обработано offset 400, собрано 500 постов (последний: 2024-11-23)
Обработано offset 500, собрано 600 постов (последний: 2024-06-03)
Обработано offset 600, собрано 700 постов (последний: 2024-03-07)
Обработано offset 700, собрано 800 постов (последний: 2023-11-08)
Обработано offset 800, собрано 900 постов (последний: 2023-07-05)
Обработано offset 900, собрано 1000 постов (последний: 2023-04-01)
Обработано offset 1000, собрано 1100 постов (последний: 2023-01-25)
Обработано offset 1100, собрано 1200 постов (последний: 2022-11-14)
Обработано offset 1200, собрано 1300 постов (последний: 2022-09-13)
Обработано offset 1300, собрано 1400 постов (последний: 2022-06-16)
Обработано offset 1400, собрано 1500 постов (последний: 2022-03-23)
Обработано offset 1500, собрано 1600 постов (последний: 2021-11-23)
Обработано offset 1600, собрано 1700 постов (последний: 2021-09-01)
Обработано offset 1700, собрано 1800 постов (последний: 2021-06-02)
Обработано offset 1800, собрано 1900 постов (последний: 2021-04-19)
Обработано offset 1900, собрано 2000 постов (последний: 2021-01-29)
Обработано offset 2000, собрано 2100 постов (последний: 2020-11-03)
Обработано offset 2100, собрано 2200 постов (последний: 2020-08-27)
Обработано offset 2200, собрано 2300 постов (последний: 2020-05-29)
Обработано offset 2300, собрано 2400 постов (последний: 2020-02-20)

- Достигли 2019 года -
Последний пост: 2059 от 2019-12-31
Всего собрано постов: 2443
Диапазон дат: 2020-01-09 - 2026-05-05

In [ ]:
# скрябина
group_id = '-103477801'
name = 'mgavm.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-31)
Обработано offset 100, собрано 200 постов (последний: 2026-02-17)
Обработано offset 200, собрано 300 постов (последний: 2026-01-12)
Обработано offset 300, собрано 400 постов (последний: 2025-11-21)
Обработано offset 400, собрано 500 постов (последний: 2025-10-20)
Обработано offset 500, собрано 600 постов (последний: 2025-09-16)
Обработано offset 600, собрано 700 постов (последний: 2025-07-23)
Обработано offset 700, собрано 800 постов (последний: 2025-06-03)
Обработано offset 800, собрано 900 постов (последний: 2025-04-16)
Обработано offset 900, собрано 1000 постов (последний: 2025-03-05)
Обработано offset 1000, собрано 1100 постов (последний: 2025-01-31)
Обработано offset 1100, собрано 1200 постов (последний: 2024-12-16)
Обработано offset 1200, собрано 1300 постов (последний: 2024-11-15)
Обработано offset 1300, собрано 1400 постов (последний: 2024-10-12)
Обработано offset 1400, собрано 1500 постов (последний: 2024-09-13)
Обработано offset 1500, собрано 1600 постов (последний: 2024-07-22)
Обработано offset 1600, собрано 1700 постов (последний: 2024-06-11)
Обработано offset 1700, собрано 1800 постов (последний: 2024-04-27)
Обработано offset 1800, собрано 1900 постов (последний: 2024-02-26)
Обработано offset 1900, собрано 2000 постов (последний: 2023-12-08)
Обработано offset 2000, собрано 2100 постов (последний: 2023-09-12)
Обработано offset 2100, собрано 2200 постов (последний: 2023-06-01)
Обработано offset 2200, собрано 2300 постов (последний: 2023-03-27)
Обработано offset 2300, собрано 2400 постов (последний: 2023-01-24)
Обработано offset 2400, собрано 2500 постов (последний: 2022-11-01)
Обработано offset 2500, собрано 2600 постов (последний: 2022-06-07)
Обработано offset 2600, собрано 2700 постов (последний: 2022-04-20)
Обработано offset 2700, собрано 2800 постов (последний: 2022-02-17)
Обработано offset 2800, собрано 2900 постов (последний: 2021-11-13)
Обработано offset 2900, собрано 3000 постов (последний: 2021-09-05)
Обработано offset 3000, собрано 3100 постов (последний: 2021-04-11)
Обработано offset 3100, собрано 3200 постов (последний: 2020-12-25)
Обработано offset 3200, собрано 3300 постов (последний: 2020-08-07)
Обработано offset 3300, собрано 3400 постов (последний: 2020-03-15)

- Достигли 2019 года -
Последний пост: 2406 от 2019-12-31
Всего собрано постов: 3452
Диапазон дат: 2020-01-07 - 2026-05-05

In [ ]:
# консерватория
group_id = '-36100537'
name = 'mocsons.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2025-10-20)
Обработано offset 100, собрано 200 постов (последний: 2025-04-02)
Обработано offset 200, собрано 300 постов (последний: 2025-02-16)
Обработано offset 300, собрано 400 постов (последний: 2024-12-17)
Обработано offset 400, собрано 500 постов (последний: 2024-10-30)
Обработано offset 500, собрано 600 постов (последний: 2024-09-16)
Обработано offset 600, собрано 700 постов (последний: 2024-07-04)
Обработано offset 700, собрано 800 постов (последний: 2024-04-29)
Обработано offset 800, собрано 900 постов (последний: 2024-03-05)
Обработано offset 900, собрано 1000 постов (последний: 2024-01-18)
Обработано offset 1000, собрано 1100 постов (последний: 2023-11-02)
Обработано offset 1100, собрано 1200 постов (последний: 2023-09-14)
Обработано offset 1200, собрано 1300 постов (последний: 2023-06-18)
Обработано offset 1300, собрано 1400 постов (последний: 2023-04-11)
Обработано offset 1400, собрано 1500 постов (последний: 2023-02-21)
Обработано offset 1500, собрано 1600 постов (последний: 2022-12-07)
Обработано offset 1600, собрано 1700 постов (последний: 2022-05-04)
Обработано offset 1700, собрано 1800 постов (последний: 2021-02-15)
Обработано offset 1800, собрано 1900 постов (последний: 2020-02-19)

- Достигли 2019 года -
Последний пост: 5140 от 2019-12-31
Всего собрано постов: 1944
Диапазон дат: 2020-01-09 - 2026-05-05

In [ ]:
# евдокимова
group_id = '-46611574'
name = 'msmsu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-01-25)
Обработано offset 100, собрано 200 постов (последний: 2025-10-23)
Обработано offset 200, собрано 300 постов (последний: 2025-08-10)
Обработано offset 300, собрано 400 постов (последний: 2025-05-08)
Обработано offset 400, собрано 500 постов (последний: 2025-03-13)
Обработано offset 500, собрано 600 постов (последний: 2025-01-09)
Обработано offset 600, собрано 700 постов (последний: 2024-11-14)
Обработано offset 700, собрано 800 постов (последний: 2024-09-06)
Обработано offset 800, собрано 900 постов (последний: 2024-05-17)
Обработано offset 900, собрано 1000 постов (последний: 2024-02-10)
Обработано offset 1000, собрано 1100 постов (последний: 2023-11-29)
Обработано offset 1100, собрано 1200 постов (последний: 2023-10-16)
Обработано offset 1200, собрано 1300 постов (последний: 2023-06-22)
Обработано offset 1300, собрано 1400 постов (последний: 2023-04-25)
Обработано offset 1400, собрано 1500 постов (последний: 2023-03-04)
Обработано offset 1500, собрано 1600 постов (последний: 2022-12-27)
Обработано offset 1600, собрано 1700 постов (последний: 2022-11-14)
Обработано offset 1700, собрано 1800 постов (последний: 2022-10-10)
Обработано offset 1800, собрано 1900 постов (последний: 2022-09-06)
Обработано offset 1900, собрано 2000 постов (последний: 2022-07-11)
Обработано offset 2000, собрано 2100 постов (последний: 2022-05-26)
Обработано offset 2100, собрано 2200 постов (последний: 2022-04-22)
Обработано offset 2200, собрано 2300 постов (последний: 2022-03-28)
Обработано offset 2300, собрано 2400 постов (последний: 2022-02-12)
Обработано offset 2400, собрано 2500 постов (последний: 2021-12-24)
Обработано offset 2500, собрано 2600 постов (последний: 2021-11-19)
Обработано offset 2600, собрано 2700 постов (последний: 2021-10-09)
Обработано offset 2700, собрано 2800 постов (последний: 2021-08-12)
Обработано offset 2800, собрано 2900 постов (последний: 2021-05-28)
Обработано offset 2900, собрано 3000 постов (последний: 2021-04-29)
Обработано offset 3000, собрано 3100 постов (последний: 2021-03-13)
Обработано offset 3100, собрано 3200 постов (последний: 2021-01-06)
Обработано offset 3200, собрано 3300 постов (последний: 2020-11-23)
Обработано offset 3300, собрано 3400 постов (последний: 2020-09-29)
Обработано offset 3400, собрано 3500 постов (последний: 2020-07-14)
Обработано offset 3500, собрано 3600 постов (последний: 2020-06-06)
Обработано offset 3600, собрано 3700 постов (последний: 2020-05-11)
Обработано offset 3700, собрано 3800 постов (последний: 2020-04-22)
Обработано offset 3800, собрано 3900 постов (последний: 2020-04-07)
Обработано offset 3900, собрано 4000 постов (последний: 2020-03-16)
Обработано offset 4000, собрано 4100 постов (последний: 2020-02-22)
Обработано offset 4100, собрано 4200 постов (последний: 2020-01-05)

- Достигли 2019 года -
Последний пост: 27132 от 2019-12-31
Всего собрано постов: 4207
Диапазон дат: 2020-01-01 - 2026-05-05

In [ ]:
# рэш
group_id = '-471300'
name = 'rash.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-20)
Обработано offset 100, собрано 200 постов (последний: 2026-01-29)
Обработано offset 200, собрано 300 постов (последний: 2025-11-27)
Обработано offset 300, собрано 400 постов (последний: 2025-10-09)
Обработано offset 400, собрано 500 постов (последний: 2025-08-18)
Обработано offset 500, собрано 600 постов (последний: 2025-06-30)
Обработано offset 600, собрано 700 постов (последний: 2025-05-12)
Обработано offset 700, собрано 800 постов (последний: 2025-03-21)
Обработано offset 800, собрано 900 постов (последний: 2025-01-29)
Обработано offset 900, собрано 1000 постов (последний: 2024-11-27)
Обработано offset 1000, собрано 1100 постов (последний: 2024-10-10)
Обработано offset 1100, собрано 1200 постов (последний: 2024-08-02)
Обработано offset 1200, собрано 1300 постов (последний: 2024-05-17)
Обработано offset 1300, собрано 1400 постов (последний: 2024-02-01)
Обработано offset 1400, собрано 1500 постов (последний: 2023-11-17)
Обработано offset 1500, собрано 1600 постов (последний: 2023-08-03)
Обработано offset 1600, собрано 1700 постов (последний: 2023-05-29)
Обработано offset 1700, собрано 1800 постов (последний: 2023-03-02)
Обработано offset 1800, собрано 1900 постов (последний: 2022-11-16)
Обработано offset 1900, собрано 2000 постов (последний: 2022-08-24)
Обработано offset 2000, собрано 2100 постов (последний: 2022-06-15)
Обработано offset 2100, собрано 2200 постов (последний: 2022-04-11)
Обработано offset 2200, собрано 2300 постов (последний: 2022-01-25)
Обработано offset 2300, собрано 2400 постов (последний: 2021-10-28)
Обработано offset 2400, собрано 2500 постов (последний: 2021-07-21)
Обработано offset 2500, собрано 2600 постов (последний: 2021-05-13)
Обработано offset 2600, собрано 2700 постов (последний: 2021-03-03)
Обработано offset 2700, собрано 2800 постов (последний: 2020-12-01)
Обработано offset 2800, собрано 2900 постов (последний: 2020-08-19)
Обработано offset 2900, собрано 3000 постов (последний: 2020-05-15)
Обработано offset 3000, собрано 3100 постов (последний: 2020-02-20)

- Достигли 2019 года -
Последний пост: 4402 от 2019-12-30
Всего собрано постов: 3140
Диапазон дат: 2020-01-10 - 2026-05-06

In [ ]:
# мии гаик
group_id = '-44133092'
name = 'miigaik.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-17)
Обработано offset 100, собрано 200 постов (последний: 2026-03-31)
Обработано offset 200, собрано 300 постов (последний: 2026-03-13)
Обработано offset 300, собрано 400 постов (последний: 2026-02-26)
Обработано offset 400, собрано 500 постов (последний: 2026-02-08)
Обработано offset 500, собрано 600 постов (последний: 2025-12-31)
Обработано offset 600, собрано 700 постов (последний: 2025-12-10)
Обработано offset 700, собрано 800 постов (последний: 2025-11-25)
Обработано offset 800, собрано 900 постов (последний: 2025-11-02)
Обработано offset 900, собрано 1000 постов (последний: 2025-09-15)
Обработано offset 1000, собрано 1100 постов (последний: 2025-07-29)
Обработано offset 1100, собрано 1200 постов (последний: 2025-06-10)
Обработано offset 1200, собрано 1300 постов (последний: 2025-05-05)
Обработано offset 1300, собрано 1400 постов (последний: 2025-04-10)
Обработано offset 1400, собрано 1500 постов (последний: 2025-03-04)
Обработано offset 1500, собрано 1600 постов (последний: 2025-01-09)
Обработано offset 1600, собрано 1700 постов (последний: 2024-11-27)
Обработано offset 1700, собрано 1800 постов (последний: 2024-10-29)
Обработано offset 1800, собрано 1900 постов (последний: 2024-09-19)
Обработано offset 1900, собрано 2000 постов (последний: 2024-07-24)
Обработано offset 2000, собрано 2100 постов (последний: 2024-05-27)
Обработано offset 2100, собрано 2200 постов (последний: 2024-04-11)
Обработано offset 2200, собрано 2300 постов (последний: 2024-03-01)
Обработано offset 2300, собрано 2400 постов (последний: 2024-01-19)
Обработано offset 2400, собрано 2500 постов (последний: 2023-12-06)
Обработано offset 2500, собрано 2600 постов (последний: 2023-11-15)
Обработано offset 2600, собрано 2700 постов (последний: 2023-10-27)
Обработано offset 2700, собрано 2800 постов (последний: 2023-10-02)
Обработано offset 2800, собрано 2900 постов (последний: 2023-09-12)
Обработано offset 2900, собрано 3000 постов (последний: 2023-08-18)
Обработано offset 3000, собрано 3100 постов (последний: 2023-07-19)
Обработано offset 3100, собрано 3200 постов (последний: 2023-06-09)
Обработано offset 3200, собрано 3300 постов (последний: 2023-05-06)
Обработано offset 3300, собрано 3400 постов (последний: 2023-04-11)
Обработано offset 3400, собрано 3500 постов (последний: 2023-03-14)
Обработано offset 3500, собрано 3600 постов (последний: 2022-12-31)
Обработано offset 3600, собрано 3700 постов (последний: 2022-11-11)
Обработано offset 3700, собрано 3800 постов (последний: 2022-09-19)
Обработано offset 3800, собрано 3900 постов (последний: 2022-07-14)
Обработано offset 3900, собрано 4000 постов (последний: 2022-05-04)
Обработано offset 4000, собрано 4100 постов (последний: 2022-03-22)
Обработано offset 4100, собрано 4200 постов (последний: 2021-12-23)
Обработано offset 4200, собрано 4300 постов (последний: 2021-10-22)
Обработано offset 4300, собрано 4400 постов (последний: 2021-08-30)
Обработано offset 4400, собрано 4500 постов (последний: 2021-05-25)
Обработано offset 4500, собрано 4600 постов (последний: 2020-12-23)
Обработано offset 4600, собрано 4700 постов (последний: 2020-10-19)
Обработано offset 4700, собрано 4800 постов (последний: 2020-05-25)
Обработано offset 4800, собрано 4900 постов (последний: 2020-03-15)

- Достигли 2019 года -
Последний пост: 9329 от 2019-12-31
Всего собрано постов: 4949
Диапазон дат: 2020-01-06 - 2026-05-06

In [ ]:
# мфуа
group_id = '-4292'
name = 'mfua.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2025-09-03)
Обработано offset 100, собрано 200 постов (последний: 2024-12-06)
Обработано offset 200, собрано 300 постов (последний: 2024-05-07)
Обработано offset 300, собрано 400 постов (последний: 2023-11-23)
Обработано offset 400, собрано 500 постов (последний: 2023-06-19)
Обработано offset 500, собрано 600 постов (последний: 2023-02-15)
Обработано offset 600, собрано 700 постов (последний: 2022-11-22)
Обработано offset 700, собрано 800 постов (последний: 2022-09-09)
Обработано offset 800, собрано 900 постов (последний: 2022-06-05)
Обработано offset 900, собрано 1000 постов (последний: 2022-03-29)
Обработано offset 1000, собрано 1100 постов (последний: 2021-12-22)
Обработано offset 1100, собрано 1200 постов (последний: 2021-09-10)
Обработано offset 1200, собрано 1300 постов (последний: 2021-04-19)
Обработано offset 1300, собрано 1400 постов (последний: 2021-02-03)
Обработано offset 1400, собрано 1500 постов (последний: 2020-12-01)
Обработано offset 1500, собрано 1600 постов (последний: 2020-09-23)
Обработано offset 1600, собрано 1700 постов (последний: 2020-06-17)
Обработано offset 1700, собрано 1800 постов (последний: 2020-04-06)

- Достигли 2019 года -
Последний пост: 9363 от 2019-12-31
Всего собрано постов: 1892
Диапазон дат: 2020-01-03 - 2026-05-05

In [ ]:
# мархи
group_id = '-203483546'
name = 'marhi.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-02-13)
Обработано offset 100, собрано 200 постов (последний: 2025-10-03)
Обработано offset 200, собрано 300 постов (последний: 2025-07-16)
Обработано offset 300, собрано 400 постов (последний: 2025-04-28)
Обработано offset 400, собрано 500 постов (последний: 2025-02-28)
Обработано offset 500, собрано 600 постов (последний: 2024-12-03)
Обработано offset 600, собрано 700 постов (последний: 2024-09-26)
Обработано offset 700, собрано 800 постов (последний: 2024-01-24)
Обработано offset 800, собрано 900 постов (последний: 2023-10-02)
Обработано offset 900, собрано 1000 постов (последний: 2023-05-17)
Обработано offset 1000, собрано 1100 постов (последний: 2023-02-14)
Обработано offset 1100, собрано 1200 постов (последний: 2022-11-18)
Обработано offset 1200, собрано 1300 постов (последний: 2022-09-22)
Обработано offset 1300, собрано 1400 постов (последний: 2022-06-22)
Обработано offset 1400, собрано 1500 постов (последний: 2022-03-16)
Обработано offset 1500, собрано 1600 постов (последний: 2021-09-27)
Обработано offset 1600, собрано 1700 постов (последний: 2021-05-14)
Обработано offset 1700, собрано 1748 постов (последний: 2021-03-23)
Постов больше нет
Всего собрано постов: 1748
Диапазон дат: 2021-03-23 - 2026-05-05

In [ ]:
# пушкина
group_id = '-30164925'
name = 'pushkin.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-02-17)
Обработано offset 100, собрано 200 постов (последний: 2025-11-19)
Обработано offset 200, собрано 300 постов (последний: 2025-09-08)
Обработано offset 300, собрано 400 постов (последний: 2025-07-09)
Обработано offset 400, собрано 500 постов (последний: 2025-05-21)
Обработано offset 500, собрано 600 постов (последний: 2025-03-10)
Обработано offset 600, собрано 700 постов (последний: 2024-12-13)
Обработано offset 700, собрано 800 постов (последний: 2024-10-28)
Обработано offset 800, собрано 900 постов (последний: 2024-09-16)
Обработано offset 900, собрано 1000 постов (последний: 2024-07-29)
Обработано offset 1000, собрано 1100 постов (последний: 2024-06-14)
Обработано offset 1100, собрано 1200 постов (последний: 2024-05-24)
Обработано offset 1200, собрано 1300 постов (последний: 2024-04-30)
Обработано offset 1300, собрано 1400 постов (последний: 2024-04-09)
Обработано offset 1400, собрано 1500 постов (последний: 2024-03-18)
Обработано offset 1500, собрано 1600 постов (последний: 2024-02-29)
Обработано offset 1600, собрано 1700 постов (последний: 2024-02-10)
Обработано offset 1700, собрано 1800 постов (последний: 2024-01-16)
Обработано offset 1800, собрано 1900 постов (последний: 2023-12-13)
Обработано offset 1900, собрано 2000 постов (последний: 2023-11-20)
Обработано offset 2000, собрано 2100 постов (последний: 2023-10-31)
Обработано offset 2100, собрано 2200 постов (последний: 2023-10-05)
Обработано offset 2200, собрано 2300 постов (последний: 2023-09-06)
Обработано offset 2300, собрано 2400 постов (последний: 2023-08-04)
Обработано offset 2400, собрано 2500 постов (последний: 2023-06-24)
Обработано offset 2500, собрано 2600 постов (последний: 2023-06-01)
Обработано offset 2600, собрано 2700 постов (последний: 2023-05-16)
Обработано offset 2700, собрано 2800 постов (последний: 2023-04-15)
Обработано offset 2800, собрано 2900 постов (последний: 2023-03-21)
Обработано offset 2900, собрано 3000 постов (последний: 2023-02-21)
Обработано offset 3000, собрано 3100 постов (последний: 2023-01-24)
Обработано offset 3100, собрано 3200 постов (последний: 2022-12-01)
Обработано offset 3200, собрано 3300 постов (последний: 2022-10-23)
Обработано offset 3300, собрано 3400 постов (последний: 2022-09-05)
Обработано offset 3400, собрано 3500 постов (последний: 2022-05-26)
Обработано offset 3500, собрано 3600 постов (последний: 2021-12-16)
Обработано offset 3600, собрано 3700 постов (последний: 2021-10-04)
Обработано offset 3700, собрано 3800 постов (последний: 2021-06-12)
Обработано offset 3800, собрано 3900 постов (последний: 2021-03-19)
Обработано offset 3900, собрано 4000 постов (последний: 2020-11-10)
Обработано offset 4000, собрано 4100 постов (последний: 2020-08-05)
Обработано offset 4100, собрано 4200 постов (последний: 2020-05-14)
Обработано offset 4200, собрано 4300 постов (последний: 2020-01-31)

- Достигли 2019 года -
Последний пост: 6697 от 2019-12-31
Всего собрано постов: 4313
Диапазон дат: 2020-01-03 - 2026-05-06

In [ ]:
# мхат
group_id = '-1010597'
name = 'mhat.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2025-01-10)
Обработано offset 100, собрано 200 постов (последний: 2024-06-28)
Обработано offset 200, собрано 300 постов (последний: 2024-03-30)
Обработано offset 300, собрано 400 постов (последний: 2024-01-19)
Обработано offset 400, собрано 500 постов (последний: 2023-10-27)
Обработано offset 500, собрано 600 постов (последний: 2023-09-08)
Обработано offset 600, собрано 700 постов (последний: 2023-06-11)
Обработано offset 700, собрано 800 постов (последний: 2023-04-13)
Обработано offset 800, собрано 900 постов (последний: 2023-02-28)
Обработано offset 900, собрано 1000 постов (последний: 2022-12-08)
Обработано offset 1000, собрано 1100 постов (последний: 2022-09-21)
Обработано offset 1100, собрано 1200 постов (последний: 2022-06-13)
Обработано offset 1200, собрано 1300 постов (последний: 2022-03-27)
Обработано offset 1300, собрано 1400 постов (последний: 2022-02-03)
Обработано offset 1400, собрано 1500 постов (последний: 2021-11-14)
Обработано offset 1500, собрано 1600 постов (последний: 2021-09-01)
Обработано offset 1600, собрано 1700 постов (последний: 2021-06-09)
Обработано offset 1700, собрано 1800 постов (последний: 2021-04-16)
Обработано offset 1800, собрано 1900 постов (последний: 2021-02-22)
Обработано offset 1900, собрано 2000 постов (последний: 2020-12-27)
Обработано offset 2000, собрано 2100 постов (последний: 2020-11-11)
Обработано offset 2100, собрано 2200 постов (последний: 2020-09-16)
Обработано offset 2200, собрано 2300 постов (последний: 2020-07-24)
Обработано offset 2300, собрано 2400 постов (последний: 2020-06-10)
Обработано offset 2400, собрано 2500 постов (последний: 2020-05-05)
Обработано offset 2500, собрано 2600 постов (последний: 2020-04-01)
Обработано offset 2600, собрано 2700 постов (последний: 2020-02-18)

- Достигли 2019 года -
Последний пост: 36665 от 2019-12-31
Всего собрано постов: 2786
Диапазон дат: 2020-01-01 - 2026-05-05

In [ ]:
# мгутм
group_id = '-94240017'
name = 'mgutm.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-31)
Обработано offset 100, собрано 200 постов (последний: 2026-02-11)
Обработано offset 200, собрано 300 постов (последний: 2025-12-04)
Обработано offset 300, собрано 400 постов (последний: 2025-10-15)
Обработано offset 400, собрано 500 постов (последний: 2025-08-12)
Обработано offset 500, собрано 600 постов (последний: 2025-05-02)
Обработано offset 600, собрано 700 постов (последний: 2025-02-05)
Обработано offset 700, собрано 800 постов (последний: 2024-10-21)
Обработано offset 800, собрано 900 постов (последний: 2024-07-25)
Обработано offset 900, собрано 1000 постов (последний: 2024-05-15)
Обработано offset 1000, собрано 1100 постов (последний: 2024-02-21)
Обработано offset 1100, собрано 1200 постов (последний: 2023-11-22)
Обработано offset 1200, собрано 1300 постов (последний: 2023-09-19)
Обработано offset 1300, собрано 1400 постов (последний: 2023-07-06)
Обработано offset 1400, собрано 1500 постов (последний: 2023-06-01)
Обработано offset 1500, собрано 1600 постов (последний: 2023-05-02)
Обработано offset 1600, собрано 1700 постов (последний: 2023-03-29)
Обработано offset 1700, собрано 1800 постов (последний: 2023-02-22)
Обработано offset 1800, собрано 1900 постов (последний: 2023-01-16)
Обработано offset 1900, собрано 2000 постов (последний: 2022-10-04)
Обработано offset 2000, собрано 2100 постов (последний: 2022-05-31)
Обработано offset 2100, собрано 2200 постов (последний: 2022-04-02)
Обработано offset 2200, собрано 2300 постов (последний: 2021-11-25)
Обработано offset 2300, собрано 2400 постов (последний: 2021-06-25)
Обработано offset 2400, собрано 2500 постов (последний: 2021-02-27)
Обработано offset 2500, собрано 2600 постов (последний: 2020-11-23)
Обработано offset 2600, собрано 2700 постов (последний: 2020-07-03)
Обработано offset 2700, собрано 2800 постов (последний: 2020-04-15)
Обработано offset 2800, собрано 2900 постов (последний: 2020-01-20)

- Достигли 2019 года -
Последний пост: 6549 от 2019-12-31
Всего собрано постов: 2906
Диапазон дат: 2020-01-10 - 2026-05-06

In [ ]:
# мтуси
group_id = '-786'
name = 'mtusi.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-02-12)
Обработано offset 100, собрано 200 постов (последний: 2025-10-14)
Обработано offset 200, собрано 300 постов (последний: 2025-06-06)
Обработано offset 300, собрано 400 постов (последний: 2025-04-30)
Обработано offset 400, собрано 500 постов (последний: 2025-03-28)
Обработано offset 500, собрано 600 постов (последний: 2025-02-19)
Обработано offset 600, собрано 700 постов (последний: 2024-12-31)
Обработано offset 700, собрано 800 постов (последний: 2024-11-27)
Обработано offset 800, собрано 900 постов (последний: 2024-11-02)
Обработано offset 900, собрано 1000 постов (последний: 2024-10-02)
Обработано offset 1000, собрано 1100 постов (последний: 2024-09-02)
Обработано offset 1100, собрано 1200 постов (последний: 2024-06-29)
Обработано offset 1200, собрано 1300 постов (последний: 2024-05-21)
Обработано offset 1300, собрано 1400 постов (последний: 2024-04-11)
Обработано offset 1400, собрано 1500 постов (последний: 2024-03-04)
Обработано offset 1500, собрано 1600 постов (последний: 2024-01-31)
Обработано offset 1600, собрано 1700 постов (последний: 2023-12-15)
Обработано offset 1700, собрано 1800 постов (последний: 2023-11-15)
Обработано offset 1800, собрано 1900 постов (последний: 2023-10-10)
Обработано offset 1900, собрано 2000 постов (последний: 2023-09-04)
Обработано offset 2000, собрано 2100 постов (последний: 2023-07-06)
Обработано offset 2100, собрано 2200 постов (последний: 2023-06-01)
Обработано offset 2200, собрано 2300 постов (последний: 2023-04-27)
Обработано offset 2300, собрано 2400 постов (последний: 2023-03-21)
Обработано offset 2400, собрано 2500 постов (последний: 2023-02-08)
Обработано offset 2500, собрано 2600 постов (последний: 2022-12-24)
Обработано offset 2600, собрано 2700 постов (последний: 2022-11-23)
Обработано offset 2700, собрано 2800 постов (последний: 2022-10-13)
Обработано offset 2800, собрано 2900 постов (последний: 2022-09-05)
Обработано offset 2900, собрано 3000 постов (последний: 2022-06-20)
Обработано offset 3000, собрано 3100 постов (последний: 2022-05-12)
Обработано offset 3100, собрано 3200 постов (последний: 2022-04-06)
Обработано offset 3200, собрано 3300 постов (последний: 2022-02-07)
Обработано offset 3300, собрано 3400 постов (последний: 2021-11-22)
Обработано offset 3400, собрано 3500 постов (последний: 2021-09-21)
Обработано offset 3500, собрано 3600 постов (последний: 2021-07-20)
Обработано offset 3600, собрано 3700 постов (последний: 2021-05-11)
Обработано offset 3700, собрано 3800 постов (последний: 2021-03-09)
Обработано offset 3800, собрано 3900 постов (последний: 2020-12-21)
Обработано offset 3900, собрано 4000 постов (последний: 2020-10-07)
Обработано offset 4000, собрано 4100 постов (последний: 2020-07-11)
Обработано offset 4100, собрано 4200 постов (последний: 2020-04-17)

- Достигли 2019 года -
Последний пост: 4805 от 2019-12-26
Всего собрано постов: 4280
Диапазон дат: 2020-01-16 - 2026-05-05

In [ ]:
# гуз
group_id = '-8990'
name = 'guz.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-07)
Обработано offset 100, собрано 200 постов (последний: 2026-03-06)
Обработано offset 200, собрано 300 постов (последний: 2026-01-27)
Обработано offset 300, собрано 400 постов (последний: 2025-12-10)
Обработано offset 400, собрано 500 постов (последний: 2025-11-17)
Обработано offset 500, собрано 600 постов (последний: 2025-10-15)
Обработано offset 600, собрано 700 постов (последний: 2025-09-10)
Обработано offset 700, собрано 800 постов (последний: 2025-07-11)
Обработано offset 800, собрано 900 постов (последний: 2025-05-27)
Обработано offset 900, собрано 1000 постов (последний: 2025-04-20)
Обработано offset 1000, собрано 1100 постов (последний: 2025-03-24)
Обработано offset 1100, собрано 1200 постов (последний: 2025-02-25)
Обработано offset 1200, собрано 1300 постов (последний: 2025-01-21)
Обработано offset 1300, собрано 1400 постов (последний: 2024-11-15)
Обработано offset 1400, собрано 1500 постов (последний: 2024-09-30)
Обработано offset 1500, собрано 1600 постов (последний: 2024-08-20)
Обработано offset 1600, собрано 1700 постов (последний: 2024-07-10)
Обработано offset 1700, собрано 1800 постов (последний: 2024-06-05)
Обработано offset 1800, собрано 1900 постов (последний: 2024-04-26)
Обработано offset 1900, собрано 2000 постов (последний: 2024-03-18)
Обработано offset 2000, собрано 2100 постов (последний: 2024-02-08)
Обработано offset 2100, собрано 2200 постов (последний: 2023-11-25)
Обработано offset 2200, собрано 2300 постов (последний: 2023-09-08)
Обработано offset 2300, собрано 2400 постов (последний: 2023-04-20)
Обработано offset 2400, собрано 2500 постов (последний: 2023-02-10)
Обработано offset 2500, собрано 2600 постов (последний: 2022-10-28)
Обработано offset 2600, собрано 2700 постов (последний: 2022-08-18)
Обработано offset 2700, собрано 2800 постов (последний: 2022-04-04)
Обработано offset 2800, собрано 2900 постов (последний: 2021-10-30)
Обработано offset 2900, собрано 3000 постов (последний: 2021-04-15)
Обработано offset 3000, собрано 3100 постов (последний: 2020-09-13)
Обработано offset 3100, собрано 3200 постов (последний: 2020-02-11)

- Достигли 2019 года -
Последний пост: 21989 от 2019-12-31
Всего собрано постов: 3217
Диапазон дат: 2020-01-01 - 2026-05-05

In [ ]:
# гитр
group_id = '-32851'
name = 'gitr.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-13)
Обработано offset 100, собрано 200 постов (последний: 2025-12-31)
Обработано offset 200, собрано 300 постов (последний: 2025-10-30)
Обработано offset 300, собрано 400 постов (последний: 2025-08-30)
Обработано offset 400, собрано 500 постов (последний: 2025-05-26)
Обработано offset 500, собрано 600 постов (последний: 2025-04-12)
Обработано offset 600, собрано 700 постов (последний: 2025-02-10)
Обработано offset 700, собрано 800 постов (последний: 2024-12-21)
Обработано offset 800, собрано 900 постов (последний: 2024-11-13)
Обработано offset 900, собрано 1000 постов (последний: 2024-07-22)
Обработано offset 1000, собрано 1100 постов (последний: 2024-05-02)
Обработано offset 1100, собрано 1200 постов (последний: 2024-03-07)
Обработано offset 1200, собрано 1300 постов (последний: 2023-12-21)
Обработано offset 1300, собрано 1400 постов (последний: 2023-09-26)
Обработано offset 1400, собрано 1500 постов (последний: 2023-07-03)
Обработано offset 1500, собрано 1600 постов (последний: 2023-05-06)
Обработано offset 1600, собрано 1700 постов (последний: 2023-03-05)
Обработано offset 1700, собрано 1800 постов (последний: 2022-12-03)
Обработано offset 1800, собрано 1900 постов (последний: 2022-10-14)
Обработано offset 1900, собрано 2000 постов (последний: 2022-08-24)
Обработано offset 2000, собрано 2100 постов (последний: 2022-07-01)
Обработано offset 2100, собрано 2200 постов (последний: 2022-05-09)
Обработано offset 2200, собрано 2300 постов (последний: 2022-04-02)
Обработано offset 2300, собрано 2400 постов (последний: 2022-01-25)
Обработано offset 2400, собрано 2500 постов (последний: 2021-11-13)
Обработано offset 2500, собрано 2600 постов (последний: 2021-09-26)
Обработано offset 2600, собрано 2700 постов (последний: 2021-07-24)
Обработано offset 2700, собрано 2800 постов (последний: 2021-05-04)
Обработано offset 2800, собрано 2900 постов (последний: 2021-01-16)
Обработано offset 2900, собрано 3000 постов (последний: 2020-11-05)
Обработано offset 3000, собрано 3100 постов (последний: 2020-09-22)
Обработано offset 3100, собрано 3200 постов (последний: 2020-07-29)
Обработано offset 3200, собрано 3300 постов (последний: 2020-06-12)
Обработано offset 3300, собрано 3400 постов (последний: 2020-05-04)
Обработано offset 3400, собрано 3500 постов (последний: 2020-03-24)
Обработано offset 3500, собрано 3600 постов (последний: 2020-03-03)
Обработано offset 3600, собрано 3700 постов (последний: 2020-02-09)
Обработано offset 3700, собрано 3800 постов (последний: 2020-01-14)

- Достигли 2019 года -
Последний пост: 7142 от 2019-12-31
Всего собрано постов: 3859
Диапазон дат: 2020-01-01 - 2026-05-05

In [ ]:
# вавт
group_id = '-194691927'
name = 'vavt.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-24)
Обработано offset 100, собрано 200 постов (последний: 2026-01-25)
Обработано offset 200, собрано 300 постов (последний: 2025-12-01)
Обработано offset 300, собрано 400 постов (последний: 2025-10-06)
Обработано offset 400, собрано 500 постов (последний: 2025-07-30)
Обработано offset 500, собрано 600 постов (последний: 2025-05-26)
Обработано offset 600, собрано 700 постов (последний: 2025-04-10)
Обработано offset 700, собрано 800 постов (последний: 2025-02-09)
Обработано offset 800, собрано 900 постов (последний: 2024-11-29)
Обработано offset 900, собрано 1000 постов (последний: 2024-10-14)
Обработано offset 1000, собрано 1100 постов (последний: 2024-08-13)
Обработано offset 1100, собрано 1200 постов (последний: 2024-06-06)
Обработано offset 1200, собрано 1300 постов (последний: 2024-03-09)
Обработано offset 1300, собрано 1400 постов (последний: 2023-10-09)
Обработано offset 1400, собрано 1500 постов (последний: 2023-05-26)
Обработано offset 1500, собрано 1600 постов (последний: 2023-03-17)
Обработано offset 1600, собрано 1700 постов (последний: 2022-07-19)
Обработано offset 1700, собрано 1800 постов (последний: 2021-05-17)
Обработано offset 1800, собрано 1900 постов (последний: 2020-08-19)
Обработано offset 1900, собрано 1978 постов (последний: 2020-06-02)
Постов больше нет
Всего собрано постов: 1978
Диапазон дат: 2020-06-02 - 2026-05-06

In [ ]:
# гаугн
group_id = '-37520'
name = 'gaugn.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-04-06)
Обработано offset 100, собрано 200 постов (последний: 2026-02-27)
Обработано offset 200, собрано 300 постов (последний: 2026-01-20)
Обработано offset 300, собрано 400 постов (последний: 2025-12-05)
Обработано offset 400, собрано 500 постов (последний: 2025-11-07)
Обработано offset 500, собрано 600 постов (последний: 2025-09-29)
Обработано offset 600, собрано 700 постов (последний: 2025-08-18)
Обработано offset 700, собрано 800 постов (последний: 2025-07-10)
Обработано offset 800, собрано 900 постов (последний: 2025-06-11)
Обработано offset 900, собрано 1000 постов (последний: 2025-05-01)
Обработано offset 1000, собрано 1100 постов (последний: 2025-04-04)
Обработано offset 1100, собрано 1200 постов (последний: 2025-03-08)
Обработано offset 1200, собрано 1300 постов (последний: 2025-02-12)
Обработано offset 1300, собрано 1400 постов (последний: 2025-01-20)
Обработано offset 1400, собрано 1500 постов (последний: 2024-12-11)
Обработано offset 1500, собрано 1600 постов (последний: 2024-11-14)
Обработано offset 1600, собрано 1700 постов (последний: 2024-10-18)
Обработано offset 1700, собрано 1800 постов (последний: 2024-09-02)
Обработано offset 1800, собрано 1900 постов (последний: 2024-07-23)
Обработано offset 1900, собрано 2000 постов (последний: 2024-06-11)
Обработано offset 2000, собрано 2100 постов (последний: 2024-04-18)
Обработано offset 2100, собрано 2200 постов (последний: 2024-03-01)
Обработано offset 2200, собрано 2300 постов (последний: 2023-12-31)
Обработано offset 2300, собрано 2400 постов (последний: 2023-11-17)
Обработано offset 2400, собрано 2500 постов (последний: 2023-10-10)
Обработано offset 2500, собрано 2600 постов (последний: 2023-08-04)
Обработано offset 2600, собрано 2700 постов (последний: 2023-06-16)
Обработано offset 2700, собрано 2800 постов (последний: 2023-05-01)
Обработано offset 2800, собрано 2900 постов (последний: 2023-03-21)
Обработано offset 2900, собрано 3000 постов (последний: 2022-12-23)
Обработано offset 3000, собрано 3100 постов (последний: 2022-10-26)
Обработано offset 3100, собрано 3200 постов (последний: 2022-08-16)
Обработано offset 3200, собрано 3300 постов (последний: 2022-06-12)
Обработано offset 3300, собрано 3400 постов (последний: 2022-04-12)
Обработано offset 3400, собрано 3500 постов (последний: 2021-12-19)
Обработано offset 3500, собрано 3600 постов (последний: 2021-09-13)
Обработано offset 3600, собрано 3700 постов (последний: 2021-07-02)
Обработано offset 3700, собрано 3800 постов (последний: 2021-04-26)
Обработано offset 3800, собрано 3900 постов (последний: 2021-02-24)
Обработано offset 3900, собрано 4000 постов (последний: 2020-11-10)
Обработано offset 4000, собрано 4100 постов (последний: 2020-09-02)
Обработано offset 4100, собрано 4200 постов (последний: 2020-07-14)
Обработано offset 4200, собрано 4300 постов (последний: 2020-05-10)
Обработано offset 4300, собрано 4400 постов (последний: 2020-02-25)

- Достигли 2019 года -
Последний пост: 6321 от 2019-12-31
Всего собрано постов: 4466
Диапазон дат: 2020-01-09 - 2026-05-06

In [ ]:
# ипполитовка
group_id = '-160773003'
name = 'ippolit.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-22)
Обработано offset 100, собрано 200 постов (последний: 2026-01-25)
Обработано offset 200, собрано 300 постов (последний: 2025-11-30)
Обработано offset 300, собрано 400 постов (последний: 2025-10-21)
Обработано offset 400, собрано 500 постов (последний: 2025-08-28)
Обработано offset 500, собрано 600 постов (последний: 2025-05-23)
Обработано offset 600, собрано 700 постов (последний: 2025-04-18)
Обработано offset 700, собрано 800 постов (последний: 2025-03-18)
Обработано offset 800, собрано 900 постов (последний: 2025-02-04)
Обработано offset 900, собрано 1000 постов (последний: 2024-12-14)
Обработано offset 1000, собрано 1100 постов (последний: 2024-11-14)
Обработано offset 1100, собрано 1200 постов (последний: 2024-10-10)
Обработано offset 1200, собрано 1300 постов (последний: 2024-07-29)
Обработано offset 1300, собрано 1400 постов (последний: 2024-05-28)
Обработано offset 1400, собрано 1500 постов (последний: 2024-04-29)
Обработано offset 1500, собрано 1600 постов (последний: 2024-03-29)
Обработано offset 1600, собрано 1700 постов (последний: 2024-02-24)
Обработано offset 1700, собрано 1800 постов (последний: 2024-01-24)
Обработано offset 1800, собрано 1900 постов (последний: 2023-12-14)
Обработано offset 1900, собрано 2000 постов (последний: 2023-11-14)
Обработано offset 2000, собрано 2100 постов (последний: 2023-10-16)
Обработано offset 2100, собрано 2200 постов (последний: 2023-09-04)
Обработано offset 2200, собрано 2300 постов (последний: 2023-05-30)
Обработано offset 2300, собрано 2400 постов (последний: 2023-04-28)
Обработано offset 2400, собрано 2500 постов (последний: 2023-03-29)
Обработано offset 2500, собрано 2600 постов (последний: 2023-02-19)
Обработано offset 2600, собрано 2700 постов (последний: 2022-12-24)
Обработано offset 2700, собрано 2800 постов (последний: 2022-10-31)
Обработано offset 2800, собрано 2900 постов (последний: 2022-06-24)
Обработано offset 2900, собрано 3000 постов (последний: 2022-05-19)
Обработано offset 3000, собрано 3100 постов (последний: 2022-03-31)
Обработано offset 3100, собрано 3200 постов (последний: 2021-12-22)
Обработано offset 3200, собрано 3300 постов (последний: 2021-09-24)
Обработано offset 3300, собрано 3400 постов (последний: 2021-05-23)
Обработано offset 3400, собрано 3500 постов (последний: 2021-03-03)
Обработано offset 3500, собрано 3600 постов (последний: 2020-11-05)
Обработано offset 3600, собрано 3700 постов (последний: 2020-06-29)
Обработано offset 3700, собрано 3800 постов (последний: 2020-05-07)

- Достигли 2019 года -
Последний пост: 713 от 2019-12-30
Всего собрано постов: 3888
Диапазон дат: 2020-01-15 - 2026-05-06

In [ ]:
# rosnou
group_id = '-152003'
name = 'rosnou.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2025-11-12)
Обработано offset 100, собрано 200 постов (последний: 2025-06-24)
Обработано offset 200, собрано 300 постов (последний: 2024-12-11)
Обработано offset 300, собрано 400 постов (последний: 2024-07-24)
Обработано offset 400, собрано 500 постов (последний: 2024-02-09)
Обработано offset 500, собрано 600 постов (последний: 2023-09-27)
Обработано offset 600, собрано 700 постов (последний: 2023-06-09)
Обработано offset 700, собрано 800 постов (последний: 2023-02-27)
Обработано offset 800, собрано 900 постов (последний: 2022-11-24)
Обработано offset 900, собрано 1000 постов (последний: 2022-09-06)
Обработано offset 1000, собрано 1100 постов (последний: 2022-05-26)
Обработано offset 1100, собрано 1200 постов (последний: 2022-02-10)
Обработано offset 1200, собрано 1300 постов (последний: 2021-10-01)
Обработано offset 1300, собрано 1400 постов (последний: 2021-04-28)
Обработано offset 1400, собрано 1500 постов (последний: 2021-01-25)
Обработано offset 1500, собрано 1600 постов (последний: 2020-11-02)
Обработано offset 1600, собрано 1700 постов (последний: 2020-08-03)
Обработано offset 1700, собрано 1800 постов (последний: 2020-03-20)

- Достигли 2019 года -
Последний пост: 37319 от 2019-12-28
Всего собрано постов: 1867
Диапазон дат: 2020-01-04 - 2026-05-01

In [ ]:
# андриак
group_id = '-35003319'
name = 'andriaka.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-02-20)
Обработано offset 100, собрано 200 постов (последний: 2025-11-05)
Обработано offset 200, собрано 300 постов (последний: 2025-06-16)
Обработано offset 300, собрано 400 постов (последний: 2025-02-21)
Обработано offset 400, собрано 500 постов (последний: 2024-10-11)
Обработано offset 500, собрано 600 постов (последний: 2024-06-06)
Обработано offset 600, собрано 700 постов (последний: 2024-03-08)
Обработано offset 700, собрано 800 постов (последний: 2023-10-16)
Обработано offset 800, собрано 900 постов (последний: 2023-05-15)
Обработано offset 900, собрано 1000 постов (последний: 2023-01-19)
Обработано offset 1000, собрано 1100 постов (последний: 2022-10-09)
Обработано offset 1100, собрано 1200 постов (последний: 2022-07-08)
Обработано offset 1200, собрано 1300 постов (последний: 2022-04-20)
Обработано offset 1300, собрано 1400 постов (последний: 2021-12-27)
Обработано offset 1400, собрано 1500 постов (последний: 2021-08-14)
Обработано offset 1500, собрано 1600 постов (последний: 2021-04-06)

- Достигли 2019 года -
Последний пост: 4036 от 2019-12-26
Всего собрано постов: 1670
Диапазон дат: 2020-01-30 - 2026-05-05

In [ ]:
# иси
group_id = '-26099662'
name = 'isi.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-24)
Обработано offset 100, собрано 200 постов (последний: 2025-12-20)
Обработано offset 200, собрано 300 постов (последний: 2025-09-28)
Обработано offset 300, собрано 400 постов (последний: 2025-07-19)
Обработано offset 400, собрано 500 постов (последний: 2025-06-24)
Обработано offset 500, собрано 600 постов (последний: 2025-05-27)
Обработано offset 600, собрано 700 постов (последний: 2025-05-03)
Обработано offset 700, собрано 800 постов (последний: 2025-04-14)
Обработано offset 800, собрано 900 постов (последний: 2025-03-21)
Обработано offset 900, собрано 1000 постов (последний: 2025-02-26)
Обработано offset 1000, собрано 1100 постов (последний: 2025-02-01)
Обработано offset 1100, собрано 1200 постов (последний: 2025-01-03)
Обработано offset 1200, собрано 1300 постов (последний: 2024-12-13)
Обработано offset 1300, собрано 1400 постов (последний: 2024-11-22)
Обработано offset 1400, собрано 1500 постов (последний: 2024-10-29)
Обработано offset 1500, собрано 1600 постов (последний: 2024-10-07)
Обработано offset 1600, собрано 1700 постов (последний: 2024-09-13)
Обработано offset 1700, собрано 1800 постов (последний: 2024-08-20)
Обработано offset 1800, собрано 1900 постов (последний: 2024-07-18)
Обработано offset 1900, собрано 2000 постов (последний: 2024-06-25)
Обработано offset 2000, собрано 2100 постов (последний: 2024-05-25)
Обработано offset 2100, собрано 2200 постов (последний: 2024-04-19)
Обработано offset 2200, собрано 2300 постов (последний: 2024-03-14)
Обработано offset 2300, собрано 2400 постов (последний: 2024-01-22)
Обработано offset 2400, собрано 2500 постов (последний: 2023-11-24)
Обработано offset 2500, собрано 2600 постов (последний: 2023-09-26)
Обработано offset 2600, собрано 2700 постов (последний: 2023-07-25)
Обработано offset 2700, собрано 2800 постов (последний: 2023-05-25)
Обработано offset 2800, собрано 2900 постов (последний: 2023-03-31)
Обработано offset 2900, собрано 3000 постов (последний: 2023-01-25)
Обработано offset 3000, собрано 3100 постов (последний: 2022-12-01)
Обработано offset 3100, собрано 3200 постов (последний: 2022-10-28)
Обработано offset 3200, собрано 3300 постов (последний: 2022-09-14)
Обработано offset 3300, собрано 3400 постов (последний: 2022-07-06)
Обработано offset 3400, собрано 3500 постов (последний: 2022-05-25)
Обработано offset 3500, собрано 3600 постов (последний: 2022-04-12)
Обработано offset 3600, собрано 3700 постов (последний: 2022-02-14)
Обработано offset 3700, собрано 3800 постов (последний: 2021-11-29)
Обработано offset 3800, собрано 3900 постов (последний: 2021-09-24)
Обработано offset 3900, собрано 4000 постов (последний: 2021-07-01)
Обработано offset 4000, собрано 4100 постов (последний: 2021-03-30)
Обработано offset 4100, собрано 4200 постов (последний: 2020-12-18)
Обработано offset 4200, собрано 4300 постов (последний: 2020-08-17)
Обработано offset 4300, собрано 4400 постов (последний: 2020-06-11)
Обработано offset 4400, собрано 4500 постов (последний: 2020-04-20)
Обработано offset 4500, собрано 4600 постов (последний: 2020-02-09)

- Достигли 2019 года -
Последний пост: 5253 от 2019-12-31
Всего собрано постов: 4624
Диапазон дат: 2020-01-05 - 2026-05-06

In [ ]:
# имес
group_id = '-104797'
name = 'imes.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-01-08)
Обработано offset 100, собрано 200 постов (последний: 2025-10-01)
Обработано offset 200, собрано 300 постов (последний: 2025-06-02)
Обработано offset 300, собрано 400 постов (последний: 2025-04-03)
Обработано offset 400, собрано 500 постов (последний: 2025-02-12)
Обработано offset 500, собрано 600 постов (последний: 2024-12-03)
Обработано offset 600, собрано 700 постов (последний: 2024-10-07)
Обработано offset 700, собрано 800 постов (последний: 2024-07-12)
Обработано offset 800, собрано 900 постов (последний: 2024-05-07)
Обработано offset 900, собрано 1000 постов (последний: 2024-01-25)
Обработано offset 1000, собрано 1100 постов (последний: 2023-10-17)
Обработано offset 1100, собрано 1200 постов (последний: 2023-03-14)
Обработано offset 1200, собрано 1300 постов (последний: 2022-11-21)
Обработано offset 1300, собрано 1400 постов (последний: 2022-07-26)
Обработано offset 1400, собрано 1500 постов (последний: 2021-07-23)
Обработано offset 1500, собрано 1600 постов (последний: 2020-03-02)

- Достигли 2019 года -
Последний пост: 3019 от 2019-12-30
Всего собрано постов: 1635
Диапазон дат: 2020-01-05 - 2026-05-05

In [ ]:
# щепка
group_id = '-7555704'
name = 'shepka.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-03)
Обработано offset 100, собрано 200 постов (последний: 2025-12-24)
Обработано offset 200, собрано 300 постов (последний: 2025-10-26)
Обработано offset 300, собрано 400 постов (последний: 2025-08-08)
Обработано offset 400, собрано 500 постов (последний: 2025-05-30)
Обработано offset 500, собрано 600 постов (последний: 2025-04-12)
Обработано offset 600, собрано 700 постов (последний: 2025-02-09)
Обработано offset 700, собрано 800 постов (последний: 2024-12-04)
Обработано offset 800, собрано 900 постов (последний: 2024-10-24)
Обработано offset 900, собрано 1000 постов (последний: 2024-09-11)
Обработано offset 1000, собрано 1100 постов (последний: 2024-07-27)
Обработано offset 1100, собрано 1200 постов (последний: 2024-06-12)
Обработано offset 1200, собрано 1300 постов (последний: 2024-05-09)
Обработано offset 1300, собрано 1400 постов (последний: 2024-03-29)
Обработано offset 1400, собрано 1500 постов (последний: 2024-02-10)
Обработано offset 1500, собрано 1600 постов (последний: 2023-12-12)
Обработано offset 1600, собрано 1700 постов (последний: 2023-10-04)
Обработано offset 1700, собрано 1800 постов (последний: 2023-07-26)
Обработано offset 1800, собрано 1900 постов (последний: 2023-06-03)
Обработано offset 1900, собрано 2000 постов (последний: 2023-04-18)
Обработано offset 2000, собрано 2100 постов (последний: 2023-02-08)
Обработано offset 2100, собрано 2200 постов (последний: 2022-11-19)
Обработано offset 2200, собрано 2300 постов (последний: 2022-09-05)
Обработано offset 2300, собрано 2400 постов (последний: 2022-06-25)
Обработано offset 2400, собрано 2500 постов (последний: 2022-04-29)
Обработано offset 2500, собрано 2600 постов (последний: 2022-01-27)
Обработано offset 2600, собрано 2700 постов (последний: 2021-10-24)
Обработано offset 2700, собрано 2800 постов (последний: 2021-07-21)
Обработано offset 2800, собрано 2900 постов (последний: 2021-04-16)
Обработано offset 2900, собрано 3000 постов (последний: 2021-01-09)
Обработано offset 3000, собрано 3100 постов (последний: 2020-10-18)
Обработано offset 3100, собрано 3200 постов (последний: 2020-07-20)
Обработано offset 3200, собрано 3300 постов (последний: 2020-05-09)
Обработано offset 3300, собрано 3400 постов (последний: 2020-02-06)

- Достигли 2019 года -
Последний пост: 3966 от 2019-12-31
Всего собрано постов: 3420
Диапазон дат: 2020-01-10 - 2026-05-06

In [ ]:
# ииле
group_id = '-33044983'
name = 'iile.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-04)
Обработано offset 100, собрано 200 постов (последний: 2026-01-13)
Обработано offset 200, собрано 300 постов (последний: 2025-10-20)
Обработано offset 300, собрано 400 постов (последний: 2025-06-20)
Обработано offset 400, собрано 500 постов (последний: 2025-04-04)
Обработано offset 500, собрано 600 постов (последний: 2025-01-18)
Обработано offset 600, собрано 700 постов (последний: 2024-10-25)
Обработано offset 700, собрано 800 постов (последний: 2024-06-17)
Обработано offset 800, собрано 900 постов (последний: 2024-02-19)
Обработано offset 900, собрано 1000 постов (последний: 2023-12-20)
Обработано offset 1000, собрано 1100 постов (последний: 2023-11-12)
Обработано offset 1100, собрано 1200 постов (последний: 2023-09-16)
Обработано offset 1200, собрано 1300 постов (последний: 2023-06-28)
Обработано offset 1300, собрано 1400 постов (последний: 2023-04-24)
Обработано offset 1400, собрано 1500 постов (последний: 2023-03-02)
Обработано offset 1500, собрано 1600 постов (последний: 2022-12-21)
Обработано offset 1600, собрано 1700 постов (последний: 2022-11-15)
Обработано offset 1700, собрано 1800 постов (последний: 2022-09-16)
Обработано offset 1800, собрано 1900 постов (последний: 2022-06-28)
Обработано offset 1900, собрано 2000 постов (последний: 2022-05-02)
Обработано offset 2000, собрано 2100 постов (последний: 2022-02-09)
Обработано offset 2100, собрано 2200 постов (последний: 2021-07-26)
Обработано offset 2200, собрано 2300 постов (последний: 2020-09-18)

- Достигли 2019 года -
Последний пост: 7186 от 2019-12-26
Всего собрано постов: 2376
Диапазон дат: 2020-01-06 - 2026-05-06

In [ ]:
# мос ити
group_id = '-71768146'
name = 'mositi.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-26)
Обработано offset 100, собрано 200 постов (последний: 2026-01-30)
Обработано offset 200, собрано 300 постов (последний: 2025-12-05)
Обработано offset 300, собрано 400 постов (последний: 2025-10-17)
Обработано offset 400, собрано 500 постов (последний: 2025-09-20)
Обработано offset 500, собрано 600 постов (последний: 2025-07-26)
Обработано offset 600, собрано 700 постов (последний: 2025-06-17)
Обработано offset 700, собрано 800 постов (последний: 2025-04-24)
Обработано offset 800, собрано 900 постов (последний: 2025-02-16)
Обработано offset 900, собрано 1000 постов (последний: 2024-11-29)
Обработано offset 1000, собрано 1100 постов (последний: 2024-09-11)
Обработано offset 1100, собрано 1200 постов (последний: 2024-06-04)
Обработано offset 1200, собрано 1300 постов (последний: 2023-11-22)
Обработано offset 1300, собрано 1400 постов (последний: 2023-04-26)
Обработано offset 1400, собрано 1500 постов (последний: 2022-07-22)
Обработано offset 1500, собрано 1600 постов (последний: 2021-07-17)
Обработано offset 1600, собрано 1700 постов (последний: 2020-08-31)

- Достигли 2019 года -
Последний пост: 1713 от 2019-12-29
Всего собрано постов: 1772
Диапазон дат: 2020-01-14 - 2026-05-06

In [ ]:
# мосгу
group_id = '-4456'
name = 'mosgu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-18)
Обработано offset 100, собрано 200 постов (последний: 2026-01-20)
Обработано offset 200, собрано 300 постов (последний: 2025-11-21)
Обработано offset 300, собрано 400 постов (последний: 2025-09-29)
Обработано offset 400, собрано 500 постов (последний: 2025-07-22)
Обработано offset 500, собрано 600 постов (последний: 2025-05-15)
Обработано offset 600, собрано 700 постов (последний: 2025-03-04)
Обработано offset 700, собрано 800 постов (последний: 2024-11-25)
Обработано offset 800, собрано 900 постов (последний: 2024-08-27)
Обработано offset 900, собрано 1000 постов (последний: 2024-05-11)
Обработано offset 1000, собрано 1100 постов (последний: 2023-12-04)
Обработано offset 1100, собрано 1200 постов (последний: 2023-09-02)
Обработано offset 1200, собрано 1300 постов (последний: 2023-06-09)
Обработано offset 1300, собрано 1400 постов (последний: 2023-03-02)
Обработано offset 1400, собрано 1500 постов (последний: 2022-12-01)
Обработано offset 1500, собрано 1600 постов (последний: 2022-10-10)
Обработано offset 1600, собрано 1700 постов (последний: 2022-09-06)
Обработано offset 1700, собрано 1800 постов (последний: 2022-08-02)
Обработано offset 1800, собрано 1900 постов (последний: 2022-06-07)
Обработано offset 1900, собрано 2000 постов (последний: 2022-04-11)
Обработано offset 2000, собрано 2100 постов (последний: 2022-02-26)
Обработано offset 2100, собрано 2200 постов (последний: 2022-01-04)
Обработано offset 2200, собрано 2300 постов (последний: 2021-11-08)
Обработано offset 2300, собрано 2400 постов (последний: 2021-09-06)
Обработано offset 2400, собрано 2500 постов (последний: 2021-07-08)
Обработано offset 2500, собрано 2600 постов (последний: 2021-05-06)
Обработано offset 2600, собрано 2700 постов (последний: 2021-03-24)
Обработано offset 2700, собрано 2800 постов (последний: 2021-01-25)
Обработано offset 2800, собрано 2900 постов (последний: 2020-11-12)
Обработано offset 2900, собрано 3000 постов (последний: 2020-06-26)
Обработано offset 3000, собрано 3100 постов (последний: 2020-05-09)
Обработано offset 3100, собрано 3200 постов (последний: 2020-03-02)

- Достигли 2019 года -
Последний пост: 6641 от 2019-12-31
Всего собрано постов: 3254
Диапазон дат: 2020-01-09 - 2026-05-06

In [ ]:
# витте
group_id = '-58519483'
name = 'vitte.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-01-13)
Обработано offset 100, собрано 200 постов (последний: 2025-09-15)
Обработано offset 200, собрано 300 постов (последний: 2025-06-12)
Обработано offset 300, собрано 400 постов (последний: 2025-02-17)
Обработано offset 400, собрано 500 постов (последний: 2024-10-30)
Обработано offset 500, собрано 600 постов (последний: 2024-08-27)
Обработано offset 600, собрано 700 постов (последний: 2024-05-24)
Обработано offset 700, собрано 800 постов (последний: 2023-12-28)
Обработано offset 800, собрано 900 постов (последний: 2023-09-05)
Обработано offset 900, собрано 1000 постов (последний: 2023-05-03)
Обработано offset 1000, собрано 1100 постов (последний: 2023-02-20)
Обработано offset 1100, собрано 1200 постов (последний: 2022-11-07)
Обработано offset 1200, собрано 1300 постов (последний: 2022-09-05)
Обработано offset 1300, собрано 1400 постов (последний: 2022-06-15)
Обработано offset 1400, собрано 1500 постов (последний: 2022-04-11)
Обработано offset 1500, собрано 1600 постов (последний: 2022-01-24)
Обработано offset 1600, собрано 1700 постов (последний: 2021-11-03)
Обработано offset 1700, собрано 1800 постов (последний: 2021-09-13)
Обработано offset 1800, собрано 1900 постов (последний: 2021-07-09)
Обработано offset 1900, собрано 2000 постов (последний: 2021-06-01)
Обработано offset 2000, собрано 2100 постов (последний: 2021-04-02)
Обработано offset 2100, собрано 2200 постов (последний: 2021-02-16)
Обработано offset 2200, собрано 2300 постов (последний: 2020-12-24)
Обработано offset 2300, собрано 2400 постов (последний: 2020-11-11)
Обработано offset 2400, собрано 2500 постов (последний: 2020-09-25)
Обработано offset 2500, собрано 2600 постов (последний: 2020-08-12)
Обработано offset 2600, собрано 2700 постов (последний: 2020-06-29)
Обработано offset 2700, собрано 2800 постов (последний: 2020-05-11)
Обработано offset 2800, собрано 2900 постов (последний: 2020-03-26)
Обработано offset 2900, собрано 3000 постов (последний: 2020-02-11)

- Достигли 2019 года -
Последний пост: 28645 от 2019-12-31
Всего собрано постов: 3091
Диапазон дат: 2020-01-01 - 2026-05-06

In [ ]:
# юстиции
group_id = '-111837730'
name = 'rpamu.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2024-01-11)
Обработано offset 100, собрано 200 постов (последний: 2022-11-17)
Обработано offset 200, собрано 300 постов (последний: 2021-05-08)
Обработано offset 300, собрано 400 постов (последний: 2020-10-14)
Обработано offset 400, собрано 500 постов (последний: 2020-04-28)

- Достигли 2019 года -
Последний пост: 3312 от 2019-12-30
Всего собрано постов: 598
Диапазон дат: 2020-01-09 - 2026-05-01

In [ ]:
# mhpidesign
group_id = '-29550550'
name = 'mhpidesign.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2025-10-17)
Обработано offset 100, собрано 200 постов (последний: 2025-07-28)
Обработано offset 200, собрано 300 постов (последний: 2025-05-14)
Обработано offset 300, собрано 400 постов (последний: 2025-02-09)
Обработано offset 400, собрано 500 постов (последний: 2024-10-24)
Обработано offset 500, собрано 600 постов (последний: 2024-07-16)
Обработано offset 600, собрано 700 постов (последний: 2024-03-17)
Обработано offset 700, собрано 800 постов (последний: 2023-10-13)
Обработано offset 800, собрано 900 постов (последний: 2023-01-10)
Обработано offset 900, собрано 1000 постов (последний: 2022-06-02)
Обработано offset 1000, собрано 1100 постов (последний: 2021-05-29)
Обработано offset 1100, собрано 1200 постов (последний: 2020-04-23)

- Достигли 2019 года -
Последний пост: 1921 от 2019-12-26
Всего собрано постов: 1236
Диапазон дат: 2020-01-21 - 2026-05-05

In [ ]:
# суриков
group_id = '-194894715'
name = 'surikov.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 21 постов (последний: 2024-12-19)
Постов больше нет
Всего собрано постов: 21
Диапазон дат: 2024-12-19 - 2026-03-24

In [ ]:
# жирик
group_id = '-19923410'
name = 'uwc.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-21)
Обработано offset 100, собрано 200 постов (последний: 2025-11-30)
Обработано offset 200, собрано 300 постов (последний: 2025-09-25)
Обработано offset 300, собрано 400 постов (последний: 2025-06-16)
Обработано offset 400, собрано 500 постов (последний: 2025-03-12)
Обработано offset 500, собрано 600 постов (последний: 2024-10-15)
Обработано offset 600, собрано 700 постов (последний: 2024-05-20)
Обработано offset 700, собрано 800 постов (последний: 2024-01-24)
Обработано offset 800, собрано 900 постов (последний: 2023-10-16)
Обработано offset 900, собрано 1000 постов (последний: 2023-07-20)
Обработано offset 1000, собрано 1100 постов (последний: 2023-04-27)
Обработано offset 1100, собрано 1200 постов (последний: 2023-02-15)
Обработано offset 1200, собрано 1300 постов (последний: 2022-11-11)
Обработано offset 1300, собрано 1400 постов (последний: 2022-07-09)
Обработано offset 1400, собрано 1500 постов (последний: 2022-03-14)
Обработано offset 1500, собрано 1600 постов (последний: 2021-10-19)
Обработано offset 1600, собрано 1700 постов (последний: 2020-06-18)

- Достигли 2019 года -
Последний пост: 3375 от 2019-12-31
Всего собрано постов: 1739
Диапазон дат: 2020-01-21 - 2026-05-06

In [ ]:
# rgupru
group_id = '-212123803'
name = 'rgupru.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2024-08-28)
Обработано offset 100, собрано 200 постов (последний: 2024-04-24)
Обработано offset 200, собрано 300 постов (последний: 2023-08-10)
Обработано offset 300, собрано 400 постов (последний: 2022-12-26)
Обработано offset 400, собрано 500 постов (последний: 2022-05-21)
Обработано offset 500, собрано 517 постов (последний: 2022-04-08)
Постов больше нет
Всего собрано постов: 517
Диапазон дат: 2022-04-08 - 2026-05-05

In [ ]:
# ммамос
group_id = '-84480950'
name = 'mmamos.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-07)
Обработано offset 100, собрано 200 постов (последний: 2025-12-10)
Обработано offset 200, собрано 300 постов (последний: 2025-09-26)
Обработано offset 300, собрано 400 постов (последний: 2025-06-25)
Обработано offset 400, собрано 500 постов (последний: 2025-04-21)
Обработано offset 500, собрано 600 постов (последний: 2025-03-02)
Обработано offset 600, собрано 700 постов (последний: 2024-12-27)
Обработано offset 700, собрано 800 постов (последний: 2024-11-16)
Обработано offset 800, собрано 900 постов (последний: 2024-09-30)
Обработано offset 900, собрано 1000 постов (последний: 2024-05-29)
Обработано offset 1000, собрано 1100 постов (последний: 2024-03-19)
Обработано offset 1100, собрано 1200 постов (последний: 2023-12-25)
Обработано offset 1200, собрано 1300 постов (последний: 2023-10-19)
Обработано offset 1300, собрано 1400 постов (последний: 2023-07-03)
Обработано offset 1400, собрано 1500 постов (последний: 2023-05-10)
Обработано offset 1500, собрано 1600 постов (последний: 2023-04-10)
Обработано offset 1600, собрано 1700 постов (последний: 2022-12-05)
Обработано offset 1700, собрано 1800 постов (последний: 2022-09-06)
Обработано offset 1800, собрано 1900 постов (последний: 2022-05-12)
Обработано offset 1900, собрано 2000 постов (последний: 2022-03-15)
Обработано offset 2000, собрано 2100 постов (последний: 2021-12-24)
Обработано offset 2100, собрано 2200 постов (последний: 2021-10-20)
Обработано offset 2200, собрано 2300 постов (последний: 2021-01-19)
Обработано offset 2300, собрано 2400 постов (последний: 2020-06-15)

- Достигли 2019 года -
Последний пост: 1492 от 2019-12-31
Всего собрано постов: 2487
Диапазон дат: 2020-01-06 - 2026-05-05

In [ ]:
# miuniversity
group_id = '-9003905'
name = 'miuniversity.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2025-09-16)
Обработано offset 100, собрано 200 постов (последний: 2024-12-12)
Обработано offset 200, собрано 300 постов (последний: 2024-06-03)
Обработано offset 300, собрано 400 постов (последний: 2023-09-06)
Обработано offset 400, собрано 500 постов (последний: 2022-11-22)
Обработано offset 500, собрано 600 постов (последний: 2022-05-11)
Обработано offset 600, собрано 700 постов (последний: 2021-04-09)
Обработано offset 700, собрано 800 постов (последний: 2020-09-17)

- Достигли 2019 года -
Последний пост: 9133 от 2019-12-16
Всего собрано постов: 836
Диапазон дат: 2020-02-13 - 2026-05-06

In [ ]:
# муии
group_id = '-32026522'
name = 'mui.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2025-12-13)
Обработано offset 100, собрано 200 постов (последний: 2025-06-11)
Обработано offset 200, собрано 300 постов (последний: 2025-02-11)
Обработано offset 300, собрано 400 постов (последний: 2024-05-08)
Обработано offset 400, собрано 500 постов (последний: 2023-10-03)
Обработано offset 500, собрано 600 постов (последний: 2023-01-24)
Обработано offset 600, собрано 700 постов (последний: 2022-07-28)
Обработано offset 700, собрано 800 постов (последний: 2021-10-13)
Обработано offset 800, собрано 900 постов (последний: 2020-12-09)
Обработано offset 900, собрано 1000 постов (последний: 2020-01-02)

- Достигли 2019 года -
Последний пост: 4329 от 2019-12-31
Всего собрано постов: 1000
Диапазон дат: 2020-01-02 - 2026-05-05

In [ ]:
# шанинка
group_id = '-82402911'
name = 'shanin.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2025-10-14)
Обработано offset 100, собрано 200 постов (последний: 2025-04-04)
Обработано offset 200, собрано 300 постов (последний: 2024-11-22)
Обработано offset 300, собрано 400 постов (последний: 2024-07-29)
Обработано offset 400, собрано 500 постов (последний: 2024-04-18)
Обработано offset 500, собрано 600 постов (последний: 2024-01-18)
Обработано offset 600, собрано 700 постов (последний: 2023-09-25)
Обработано offset 700, собрано 800 постов (последний: 2023-05-27)
Обработано offset 800, собрано 900 постов (последний: 2023-02-04)
Обработано offset 900, собрано 1000 постов (последний: 2022-10-19)
Обработано offset 1000, собрано 1100 постов (последний: 2022-06-27)
Обработано offset 1100, собрано 1200 постов (последний: 2022-03-29)
Обработано offset 1200, собрано 1300 постов (последний: 2021-12-15)
Обработано offset 1300, собрано 1400 постов (последний: 2021-07-15)
Обработано offset 1400, собрано 1500 постов (последний: 2021-04-15)
Обработано offset 1500, собрано 1600 постов (последний: 2020-12-15)
Обработано offset 1600, собрано 1700 постов (последний: 2020-06-19)
Обработано offset 1700, собрано 1800 постов (последний: 2020-02-15)

- Достигли 2019 года -
Последний пост: 1703 от 2019-12-30
Всего собрано постов: 1826
Диапазон дат: 2020-01-04 - 2026-04-27

In [ ]:
# райкин
group_id = '-59762666'
name = 'raikin.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2025-04-21)
Обработано offset 100, собрано 200 постов (последний: 2024-10-29)
Обработано offset 200, собрано 300 постов (последний: 2024-02-27)
Обработано offset 300, собрано 400 постов (последний: 2023-10-06)
Обработано offset 400, собрано 500 постов (последний: 2023-02-17)
Обработано offset 500, собрано 600 постов (последний: 2022-10-29)
Обработано offset 600, собрано 700 постов (последний: 2021-03-19)

- Достигли 2019 года -
Последний пост: 963 от 2019-12-27
Всего собрано постов: 786
Диапазон дат: 2020-01-13 - 2026-05-05

In [ ]:
# миту маси
group_id = '-29193864'
name = 'mitumasi.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-02-27)
Обработано offset 100, собрано 200 постов (последний: 2025-12-12)
Обработано offset 200, собрано 300 постов (последний: 2025-09-25)
Обработано offset 300, собрано 400 постов (последний: 2025-07-30)
Обработано offset 400, собрано 500 постов (последний: 2025-06-20)
Обработано offset 500, собрано 600 постов (последний: 2025-05-21)
Обработано offset 600, собрано 700 постов (последний: 2025-04-29)
Обработано offset 700, собрано 800 постов (последний: 2025-04-01)
Обработано offset 800, собрано 900 постов (последний: 2025-02-27)
Обработано offset 900, собрано 1000 постов (последний: 2025-01-25)
Обработано offset 1000, собрано 1100 постов (последний: 2024-12-17)
Обработано offset 1100, собрано 1200 постов (последний: 2024-11-14)
Обработано offset 1200, собрано 1300 постов (последний: 2024-09-12)
Обработано offset 1300, собрано 1400 постов (последний: 2024-04-15)
Обработано offset 1400, собрано 1500 постов (последний: 2023-12-09)
Обработано offset 1500, собрано 1600 постов (последний: 2023-07-04)
Обработано offset 1600, собрано 1700 постов (последний: 2022-08-30)
Обработано offset 1700, собрано 1800 постов (последний: 2022-05-13)
Обработано offset 1800, собрано 1900 постов (последний: 2021-09-10)
Обработано offset 1900, собрано 2000 постов (последний: 2021-03-22)
Обработано offset 2000, собрано 2100 постов (последний: 2020-11-20)
Обработано offset 2100, собрано 2200 постов (последний: 2020-07-02)

- Достигли 2019 года -
Последний пост: 2574 от 2019-12-28
Всего собрано постов: 2291
Диапазон дат: 2020-01-17 - 2026-05-06

In [ ]:
# мстука и
group_id = '-45732330'
name = 'mstuca.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2025-12-05)
Обработано offset 100, собрано 200 постов (последний: 2025-05-12)
Обработано offset 200, собрано 300 постов (последний: 2025-01-13)
Обработано offset 300, собрано 400 постов (последний: 2024-07-02)
Обработано offset 400, собрано 500 постов (последний: 2023-11-18)
Обработано offset 500, собрано 600 постов (последний: 2023-03-07)
Обработано offset 600, собрано 700 постов (последний: 2022-10-08)
Обработано offset 700, собрано 800 постов (последний: 2022-05-11)
Обработано offset 800, собрано 900 постов (последний: 2021-12-08)
Обработано offset 900, собрано 1000 постов (последний: 2021-05-31)
Обработано offset 1000, собрано 1100 постов (последний: 2020-11-18)

- Достигли 2019 года -
Последний пост: 2763 от 2019-12-31
Всего собрано постов: 1194
Диапазон дат: 2020-01-22 - 2026-05-04

In [ ]:
# мпсру
group_id = '-180525620'
name = 'mpsuru.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-03)
Обработано offset 100, собрано 200 постов (последний: 2025-12-05)
Обработано offset 200, собрано 300 постов (последний: 2025-10-09)
Обработано offset 300, собрано 400 постов (последний: 2025-07-11)
Обработано offset 400, собрано 500 постов (последний: 2025-05-12)
Обработано offset 500, собрано 600 постов (последний: 2025-03-10)
Обработано offset 600, собрано 700 постов (последний: 2024-12-18)
Обработано offset 700, собрано 800 постов (последний: 2024-10-16)
Обработано offset 800, собрано 900 постов (последний: 2024-08-06)
Обработано offset 900, собрано 1000 постов (последний: 2024-06-10)
Обработано offset 1000, собрано 1100 постов (последний: 2024-04-12)
Обработано offset 1100, собрано 1200 постов (последний: 2024-03-07)
Обработано offset 1200, собрано 1300 постов (последний: 2023-12-28)
Обработано offset 1300, собрано 1400 постов (последний: 2023-11-04)
Обработано offset 1400, собрано 1500 постов (последний: 2023-08-01)
Обработано offset 1500, собрано 1600 постов (последний: 2023-05-19)
Обработано offset 1600, собрано 1700 постов (последний: 2023-03-02)
Обработано offset 1700, собрано 1800 постов (последний: 2022-12-17)
Обработано offset 1800, собрано 1900 постов (последний: 2022-10-23)
Обработано offset 1900, собрано 2000 постов (последний: 2022-08-19)
Обработано offset 2000, собрано 2100 постов (последний: 2022-06-06)
Обработано offset 2100, собрано 2200 постов (последний: 2022-04-14)
Обработано offset 2200, собрано 2300 постов (последний: 2022-02-08)
Обработано offset 2300, собрано 2400 постов (последний: 2021-12-05)
Обработано offset 2400, собрано 2500 постов (последний: 2021-10-01)
Обработано offset 2500, собрано 2600 постов (последний: 2021-07-08)
Обработано offset 2600, собрано 2700 постов (последний: 2021-05-19)
Обработано offset 2700, собрано 2800 постов (последний: 2021-04-19)
Обработано offset 2800, собрано 2900 постов (последний: 2021-03-16)
Обработано offset 2900, собрано 3000 постов (последний: 2021-02-10)
Обработано offset 3000, собрано 3100 постов (последний: 2020-12-30)
Обработано offset 3100, собрано 3200 постов (последний: 2020-11-16)
Обработано offset 3200, собрано 3300 постов (последний: 2020-10-01)
Обработано offset 3300, собрано 3400 постов (последний: 2020-08-18)
Обработано offset 3400, собрано 3500 постов (последний: 2020-07-03)
Обработано offset 3500, собрано 3600 постов (последний: 2020-05-25)
Обработано offset 3600, собрано 3700 постов (последний: 2020-04-12)

- Достигли 2019 года -
Последний пост: 161 от 2019-10-30
Всего собрано постов: 3754
Диапазон дат: 2020-01-27 - 2026-05-06

In [ ]:
# шнитке
group_id = '-60900154'
name = 'shnitke.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2025-10-08)
Обработано offset 100, собрано 200 постов (последний: 2025-01-14)
Обработано offset 200, собрано 300 постов (последний: 2024-05-25)
Обработано offset 300, собрано 400 постов (последний: 2023-10-12)
Обработано offset 400, собрано 500 постов (последний: 2023-03-03)
Обработано offset 500, собрано 600 постов (последний: 2022-10-18)
Обработано offset 600, собрано 700 постов (последний: 2022-04-25)
Обработано offset 700, собрано 800 постов (последний: 2021-12-21)
Обработано offset 800, собрано 900 постов (последний: 2021-06-12)
Обработано offset 900, собрано 1000 постов (последний: 2020-10-07)
Обработано offset 1000, собрано 1100 постов (последний: 2020-04-16)

- Достигли 2019 года -
Последний пост: 1012 от 2019-11-22
Всего собрано постов: 1138
Диапазон дат: 2020-02-12 - 2026-05-03

In [ ]:
# глазунов
group_id = '-58035731'
name = 'glasunov.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-17)
Обработано offset 100, собрано 200 постов (последний: 2026-01-25)
Обработано offset 200, собрано 300 постов (последний: 2025-11-24)
Обработано offset 300, собрано 400 постов (последний: 2025-09-26)
Обработано offset 400, собрано 500 постов (последний: 2025-08-03)
Обработано offset 500, собрано 600 постов (последний: 2025-06-12)
Обработано offset 600, собрано 700 постов (последний: 2025-05-01)
Обработано offset 700, собрано 800 постов (последний: 2025-03-19)
Обработано offset 800, собрано 900 постов (последний: 2025-02-07)
Обработано offset 900, собрано 1000 постов (последний: 2024-12-25)
Обработано offset 1000, собрано 1100 постов (последний: 2024-11-12)
Обработано offset 1100, собрано 1200 постов (последний: 2024-09-27)
Обработано offset 1200, собрано 1300 постов (последний: 2024-08-27)
Обработано offset 1300, собрано 1400 постов (последний: 2024-07-24)
Обработано offset 1400, собрано 1500 постов (последний: 2024-06-28)
Обработано offset 1500, собрано 1600 постов (последний: 2024-06-04)
Обработано offset 1600, собрано 1700 постов (последний: 2024-04-26)
Обработано offset 1700, собрано 1800 постов (последний: 2024-03-05)
Обработано offset 1800, собрано 1900 постов (последний: 2023-12-16)
Обработано offset 1900, собрано 2000 постов (последний: 2023-10-06)
Обработано offset 2000, собрано 2100 постов (последний: 2023-07-05)
Обработано offset 2100, собрано 2200 постов (последний: 2023-04-26)
Обработано offset 2200, собрано 2300 постов (последний: 2023-02-03)
Обработано offset 2300, собрано 2400 постов (последний: 2022-12-12)
Обработано offset 2400, собрано 2500 постов (последний: 2022-09-30)
Обработано offset 2500, собрано 2600 постов (последний: 2022-06-28)
Обработано offset 2600, собрано 2700 постов (последний: 2022-03-24)
Обработано offset 2700, собрано 2800 постов (последний: 2021-12-16)
Обработано offset 2800, собрано 2900 постов (последний: 2021-09-20)
Обработано offset 2900, собрано 3000 постов (последний: 2021-06-24)
Обработано offset 3000, собрано 3100 постов (последний: 2021-04-18)
Обработано offset 3100, собрано 3200 постов (последний: 2021-02-01)
Обработано offset 3200, собрано 3300 постов (последний: 2020-10-25)
Обработано offset 3300, собрано 3400 постов (последний: 2020-09-03)
Обработано offset 3400, собрано 3500 постов (последний: 2020-06-21)
Обработано offset 3500, собрано 3600 постов (последний: 2020-05-02)
Обработано offset 3600, собрано 3700 постов (последний: 2020-03-04)
Обработано offset 3700, собрано 3800 постов (последний: 2020-01-19)

- Достигли 2019 года -
Последний пост: 4682 от 2019-12-31
Всего собрано постов: 3824
Диапазон дат: 2020-01-02 - 2026-05-06

In [ ]:
# филарет
group_id = '-117974920'
name = 'filaret.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-01-06)
Обработано offset 100, собрано 200 постов (последний: 2025-09-29)
Обработано offset 200, собрано 300 постов (последний: 2025-04-21)
Обработано offset 300, собрано 400 постов (последний: 2024-11-25)
Обработано offset 400, собрано 500 постов (последний: 2024-06-13)
Обработано offset 500, собрано 600 постов (последний: 2023-12-29)
Обработано offset 600, собрано 700 постов (последний: 2023-06-26)
Обработано offset 700, собрано 800 постов (последний: 2022-10-06)
Обработано offset 800, собрано 900 постов (последний: 2021-12-14)
Обработано offset 900, собрано 1000 постов (последний: 2021-03-29)
Обработано offset 1000, собрано 1100 постов (последний: 2020-07-09)
Обработано offset 1100, собрано 1200 постов (последний: 2020-03-20)

- Достигли 2019 года -
Последний пост: 851 от 2019-12-31
Всего собрано постов: 1251
Диапазон дат: 2020-01-06 - 2026-05-05

In [ ]:
# рг иис
group_id = '-193133254'
name = 'rgiis.csv'

posts = get_posts(api_token, group_id, start_offset=0)

df = pd.DataFrame(posts)

print(f'Всего собрано постов: {len(df)}')
print(f'Диапазон дат: {df['date'].min()} - {df['date'].max()}')

df.to_csv(name, index=False, encoding='utf-8')

Начинаем сбор с offset = 0
Цель: дойти до 01.01.2020
--------------------------------------------------
Обработано offset 0, собрано 100 постов (последний: 2026-03-26)
Обработано offset 100, собрано 200 постов (последний: 2026-02-23)
Обработано offset 200, собрано 300 постов (последний: 2026-01-05)
Обработано offset 300, собрано 400 постов (последний: 2025-12-02)
Обработано offset 400, собрано 500 постов (последний: 2025-10-31)
Обработано offset 500, собрано 600 постов (последний: 2025-10-02)
Обработано offset 600, собрано 700 постов (последний: 2025-08-13)
Обработано offset 700, собрано 800 постов (последний: 2025-06-09)
Обработано offset 800, собрано 900 постов (последний: 2025-05-08)
Обработано offset 900, собрано 1000 постов (последний: 2025-04-16)
Обработано offset 1000, собрано 1100 постов (последний: 2025-03-14)
Обработано offset 1100, собрано 1200 постов (последний: 2025-01-30)
Обработано offset 1200, собрано 1300 постов (последний: 2024-12-05)
Обработано offset 1300, собрано 1400 постов (последний: 2024-10-28)
Обработано offset 1400, собрано 1500 постов (последний: 2024-08-28)
Обработано offset 1500, собрано 1600 постов (последний: 2024-06-07)
Обработано offset 1600, собрано 1700 постов (последний: 2024-05-03)
Обработано offset 1700, собрано 1800 постов (последний: 2024-04-03)
Обработано offset 1800, собрано 1900 постов (последний: 2024-02-19)
Обработано offset 1900, собрано 2000 постов (последний: 2023-12-17)
Обработано offset 2000, собрано 2100 постов (последний: 2023-10-26)
Обработано offset 2100, собрано 2200 постов (последний: 2023-09-07)
Обработано offset 2200, собрано 2300 постов (последний: 2023-06-19)
Обработано offset 2300, собрано 2400 постов (последний: 2023-05-04)
Обработано offset 2400, собрано 2500 постов (последний: 2023-04-11)
Обработано offset 2500, собрано 2600 постов (последний: 2023-03-02)
Обработано offset 2600, собрано 2700 постов (последний: 2023-01-01)
Обработано offset 2700, собрано 2800 постов (последний: 2022-11-24)
Обработано offset 2800, собрано 2900 постов (последний: 2022-10-17)
Обработано offset 2900, собрано 3000 постов (последний: 2022-09-12)
Обработано offset 3000, собрано 3100 постов (последний: 2022-08-02)
Обработано offset 3100, собрано 3200 постов (последний: 2022-07-06)
Обработано offset 3200, собрано 3300 постов (последний: 2022-06-14)
Обработано offset 3300, собрано 3400 постов (последний: 2022-05-19)
Обработано offset 3400, собрано 3500 постов (последний: 2022-04-23)
Обработано offset 3500, собрано 3600 постов (последний: 2022-03-30)
Обработано offset 3600, собрано 3700 постов (последний: 2022-02-21)
Обработано offset 3700, собрано 3800 постов (последний: 2021-11-17)
Обработано offset 3800, собрано 3900 постов (последний: 2021-09-22)
Обработано offset 3900, собрано 4000 постов (последний: 2021-05-28)
Обработано offset 4000, собрано 4100 постов (последний: 2021-04-09)
Обработано offset 4100, собрано 4200 постов (последний: 2021-02-12)
Обработано offset 4200, собрано 4300 постов (последний: 2020-11-03)
Обработано offset 4300, собрано 4400 постов (последний: 2020-06-26)
Обработано offset 4400, собрано 4500 постов (последний: 2020-04-29)
Обработано offset 4500, собрано 4536 постов (последний: 2020-03-19)
Постов больше нет
Всего собрано постов: 4536
Диапазон дат: 2020-03-19 - 2026-05-06

### Агрегация данных в единый датафрейм

In [ ]:
import os

# все файлы были перенесены в отдельную папку, откуда осуществляется их выгрузка
folder_path = '/Users/ekaterinamalkova/Desktop/vkr_analysis/data/data_parsed_unis_csvis'
dataframes = []

# последовательное чтение каждого файла и их присоединение к списку из Dataframe'ов
for file in os.listdir(folder_path):
  file_path = os.path.join(folder_path, file)
  df = pd.read_csv(file_path)
  df['source_nickname'] = file
  print(f'Dataframe {file} содержит {len(df)} публикаций, присоединяем их к основному Dataframe')
  dataframes.append(df)

# преобразование списка из Dataframe'ов в основной Datarame
if dataframes:
  data = pd.concat(dataframes, ignore_index=True)
  data['date'] = pd.to_datetime(data['date'])
  print('')
  print(f'Все готово, основной Dataframe содержит {len(data)} публикаций с 2020-01-01')
  print('')
  data = data.query("date < '2026-01-01'").reset_index(drop=True)
  data = data.dropna()
  print(f'Удалены публикации из 2026 и пропущенные значения, сновной Dataframe содержит {len(data)} публикаций с 2020-01-01 по 2025-12-31')

data.to_csv('/Users/ekaterinamalkova/Desktop/vkr_analysis/data/data_unis.csv', index=False)

Dataframe hse.csv содержит 7560 публикаций, присоединяем их к основному Dataframe
Dataframe mai.csv содержит 7844 публикаций, присоединяем их к основному Dataframe
Dataframe mgu.csv содержит 7728 публикаций, присоединяем их к основному Dataframe
Dataframe mfti.csv содержит 5731 публикаций, присоединяем их к основному Dataframe
Dataframe mirea.csv содержит 10851 публикаций, присоединяем их к основному Dataframe
Dataframe ranepa.csv содержит 11480 публикаций, присоединяем их к основному Dataframe
Dataframe misis.csv содержит 11334 публикаций, присоединяем их к основному Dataframe
Dataframe bmstu.csv содержит 7222 публикаций, присоединяем их к основному Dataframe
Dataframe rudn.csv содержит 6038 публикаций, присоединяем их к основному Dataframe
Dataframe sechenov.csv содержит 4777 публикаций, присоединяем их к основному Dataframe
Dataframe mgimo.csv содержит 7807 публикаций, присоединяем их к основному Dataframe
Dataframe fa.csv содержит 6542 публикаций, присоединяем их к основному Dataframe
Dataframe mephi.csv содержит 9370 публикаций, присоединяем их к основному Dataframe
Dataframe kutafina.csv содержит 5804 публикаций, присоединяем их к основному Dataframe
Dataframe gitis.csv содержит 3710 публикаций, присоединяем их к основному Dataframe
Dataframe gubkin.csv содержит 5472 публикаций, присоединяем их к основному Dataframe
Dataframe rsmu.csv содержит 5209 публикаций, присоединяем их к основному Dataframe
Dataframe mpei.csv содержит 5671 публикаций, присоединяем их к основному Dataframe
Dataframe mpgu.csv содержит 6891 публикаций, присоединяем их к основному Dataframe
Dataframe rggu.csv содержит 7583 публикаций, присоединяем их к основному Dataframe
Dataframe miet.csv содержит 6489 публикаций, присоединяем их к основному Dataframe
Dataframe timacad.csv содержит 5608 публикаций, присоединяем их к основному Dataframe
Dataframe guu.csv содержит 4702 публикаций, присоединяем их к основному Dataframe
Dataframe mgsu.csv содержит 7605 публикаций, присоединяем их к основному Dataframe
Dataframe rguk.csv содержит 7466 публикаций, присоединяем их к основному Dataframe
Dataframe shcukina.csv содержит 6670 публикаций, присоединяем их к основному Dataframe
Dataframe muctr.csv содержит 5286 публикаций, присоединяем их к основному Dataframe
Dataframe gnesin.csv содержит 2214 публикаций, присоединяем их к основному Dataframe
Dataframe synergy.csv содержит 7306 публикаций, присоединяем их к основному Dataframe
Dataframe polytech.csv содержит 5553 публикаций, присоединяем их к основному Dataframe
Dataframe mgppu.csv содержит 8045 публикаций, присоединяем их к основному Dataframe
Dataframe stankin.csv содержит 8830 публикаций, присоединяем их к основному Dataframe
Dataframe mgusit.csv содержит 11099 публикаций, присоединяем их к основному Dataframe
Dataframe rgsu.csv содержит 5115 публикаций, присоединяем их к основному Dataframe
Dataframe rosbiotech.csv содержит 7003 публикаций, присоединяем их к основному Dataframe
Dataframe miit.csv содержит 2995 публикаций, присоединяем их к основному Dataframe
Dataframe dipacademy.csv содержит 9334 публикаций, присоединяем их к основному Dataframe
Dataframe pstgu.csv содержит 3795 публикаций, присоединяем их к основному Dataframe
Dataframe mgri.csv содержит 5935 публикаций, присоединяем их к основному Dataframe
Dataframe gtsolifk.csv содержит 6839 публикаций, присоединяем их к основному Dataframe
Dataframe rghpu.csv содержит 2731 публикаций, присоединяем их к основному Dataframe
Dataframe inpsyho.csv содержит 2511 публикаций, присоединяем их к основному Dataframe
Dataframe madi.csv содержит 2443 публикаций, присоединяем их к основному Dataframe
Dataframe mgavm.csv содержит 3452 публикаций, присоединяем их к основному Dataframe
Dataframe msmsu.csv содержит 4207 публикаций, присоединяем их к основному Dataframe
Dataframe rash.csv содержит 3140 публикаций, присоединяем их к основному Dataframe
Dataframe miigaik.csv содержит 4949 публикаций, присоединяем их к основному Dataframe
Dataframe mfua.csv содержит 1892 публикаций, присоединяем их к основному Dataframe
Dataframe marhi.csv содержит 1748 публикаций, присоединяем их к основному Dataframe
Dataframe pushkin.csv содержит 4313 публикаций, присоединяем их к основному Dataframe
Dataframe mhat.csv содержит 2786 публикаций, присоединяем их к основному Dataframe
Dataframe mgutm.csv содержит 2906 публикаций, присоединяем их к основному Dataframe
Dataframe mtusi.csv содержит 4280 публикаций, присоединяем их к основному Dataframe
Dataframe guz.csv содержит 3217 публикаций, присоединяем их к основному Dataframe
Dataframe gitr.csv содержит 3859 публикаций, присоединяем их к основному Dataframe
Dataframe vavt.csv содержит 1978 публикаций, присоединяем их к основному Dataframe
Dataframe gaugn.csv содержит 4466 публикаций, присоединяем их к основному Dataframe
Dataframe ippolit.csv содержит 3888 публикаций, присоединяем их к основному Dataframe
Dataframe rosnou.csv содержит 1867 публикаций, присоединяем их к основному Dataframe
Dataframe andriaka.csv содержит 1670 публикаций, присоединяем их к основному Dataframe
Dataframe isi.csv содержит 4624 публикаций, присоединяем их к основному Dataframe
Dataframe imes.csv содержит 1635 публикаций, присоединяем их к основному Dataframe
Dataframe shepka.csv содержит 3420 публикаций, присоединяем их к основному Dataframe
Dataframe iile.csv содержит 2376 публикаций, присоединяем их к основному Dataframe
Dataframe mositi.csv содержит 1772 публикаций, присоединяем их к основному Dataframe
Dataframe mosgu.csv содержит 3254 публикаций, присоединяем их к основному Dataframe
Dataframe vitte.csv содержит 3091 публикаций, присоединяем их к основному Dataframe
Dataframe mhpidesign.csv содержит 1236 публикаций, присоединяем их к основному Dataframe
Dataframe uwc.csv содержит 1739 публикаций, присоединяем их к основному Dataframe
Dataframe mmamos.csv содержит 2487 публикаций, присоединяем их к основному Dataframe
Dataframe mui.csv содержит 1000 публикаций, присоединяем их к основному Dataframe
Dataframe shanin.csv содержит 1826 публикаций, присоединяем их к основному Dataframe
Dataframe raikin.csv содержит 786 публикаций, присоединяем их к основному Dataframe
Dataframe mitumasi.csv содержит 2291 публикаций, присоединяем их к основному Dataframe
Dataframe mstuca.csv содержит 1194 публикаций, присоединяем их к основному Dataframe
Dataframe mpsuru.csv содержит 3754 публикаций, присоединяем их к основному Dataframe
Dataframe glasunov.csv содержит 3824 публикаций, присоединяем их к основному Dataframe
Dataframe filaret.csv содержит 1251 публикаций, присоединяем их к основному Dataframe
Dataframe rgiis.csv содержит 4536 публикаций, присоединяем их к основному Dataframe
Dataframe vgik.csv содержит 2622 публикаций, присоединяем их к основному Dataframe
Dataframe mgpu.csv содержит 4002 публикаций, присоединяем их к основному Dataframe
Dataframe surikov.csv содержит 21 публикаций, присоединяем их к основному Dataframe
Dataframe miuniversity.csv содержит 836 публикаций, присоединяем их к основному Dataframe
Dataframe rgupru.csv содержит 517 публикаций, присоединяем их к основному Dataframe
Dataframe mocsons.csv содержит 1944 публикаций, присоединяем их к основному Dataframe
Dataframe mslu.csv содержит 931 публикаций, присоединяем их к основному Dataframe
Dataframe shnitke.csv содержит 1138 публикаций, присоединяем их к основному Dataframe
Dataframe balletacademy.csv содержит 684 публикаций, присоединяем их к основному Dataframe
Dataframe rpamu.csv содержит 598 публикаций, присоединяем их к основному Dataframe
Dataframe reu.csv содержит 6734 публикаций, присоединяем их к основному Dataframe

Все готово, основной Dataframe содержит 400939 публикаций с 2020-01-01

Удалены публикации из 2026 и пропущенные значения, сновной Dataframe содержит 345006 публикаций с 2020-01-01 по 2025-12-31

## Парсинг комментариев

### Дополнение датафрейма для выгрузки комментариев

In [40]:
# списки идентификаторов и названий csv файлов для добавления этой информации в набор данных
data = [['-25205856', 'hse.csv'],
        ['-50409684', 'mai.csv'],
        ['-78019879', 'mgu.csv'],
        ['-1177', 'reu.csv'],
        ['-932', 'mfti.csv'],
        ['-1388', 'mirea.csv'],
        ['-5398', 'ranepa.csv'],
        ['-62258607', 'misis.csv'],
        ['-40427933', 'bmstu.csv'],
        ['-1711', 'rudn.csv'],
        ['-65464437', 'sechenov.csv'],
        ['-26555975', 'mgimo.csv'],
        ['-6319', 'fa.csv'],
        ['-69589815', 'mephi.csv'],
        ['-65417', 'kutafina.csv'],
        ['-145886776', 'gitis.csv'],
        ['-71938736', 'gubkin.csv'],
        ['-53765914', 'rsmu.csv'],
        ['-51345945', 'mpei.csv'],
        ['-30321356', 'mpgu.csv'],
        ['-199859404', 'vgik.csv'],
        ['-3983', 'mgpu.csv'],
        ['-16479782', 'rggu.csv'],
        ['-33509', 'miet.csv'],
        ['-146300938', 'timacad.csv'],
        ['-23628595', 'guu.csv'],
        ['-97639426', 'mgsu.csv'],
        ['-38924', 'rguk.csv'],
        ['-23778827', 'shcukina.csv'],
        ['-31037181', 'muctr.csv'],
        ['-30431394', 'gnesin.csv'],
        ['-38029', 'synergy.csv'],
        ['-33991085', 'polytech.csv'],
        ['-38093474', 'mgppu.csv'],
        ['-1332509', 'stankin.csv'],
        ['-30016632', 'mgusit.csv'],
        ['-39683739', 'rgsu.csv'],
        ['-168484484', 'rosbiotech.csv'],
        ['-159', 'miit.csv'],
        ['-181211182', 'dipacademy.csv'],
        ['-97729', 'pstgu.csv'],
        ['-163624433', 'mgri.csv'],
        ['-211891378', 'balletacademy.csv'],
        ['-41423', 'gtsolifk.csv'],
        ['-187809308', 'rghpu.csv'],
        ['-11290126', 'inpsyho.csv'],
        ['-214354323', 'mslu.csv'],
        ['-138541024', 'madi.csv'],
        ['-103477801', 'mgavm.csv'],
        ['-36100537', 'mocsons.csv'],
        ['-46611574', 'msmsu.csv'],
        ['-471300', 'rash.csv'],
        ['-44133092', 'miigaik.csv'],
        ['-4292', 'mfua.csv'],
        ['-203483546', 'marhi.csv'],
        ['-30164925', 'pushkin.csv'],
        ['-1010597', 'mhat.csv'],
        ['-94240017', 'mgutm.csv'],
        ['-786', 'mtusi.csv'],
        ['-8990', 'guz.csv'],
        ['-32851', 'gitr.csv'],
        ['-194691927', 'vavt.csv'],
        ['-37520', 'gaugn.csv'],
        ['-160773003', 'ippolit.csv'],
        ['-152003', 'rosnou.csv'],
        ['-35003319', 'andriaka.csv'],
        ['-26099662', 'isi.csv'],
        ['-104797', 'imes.csv'],
        ['-7555704', 'shepka.csv'],
        ['-33044983', 'iile.csv'],
        ['-71768146', 'mositi.csv'],
        ['-4456', 'mosgu.csv'],
        ['-58519483', 'vitte.csv'],
        ['-29550550', 'mhpidesign.csv'],
        ['-19923410', 'uwc.csv'],
        ['-212123803', 'rgupru.csv'],
        ['-84480950', 'mmamos.csv'],
        ['-9003905', 'miuniversity.csv'],
        ['-32026522', 'mui.csv'],
        ['-82402911', 'shanin.csv'],
        ['-59762666', 'raikin.csv'],
        ['-29193864', 'mitumasi.csv'],
        ['-45732330', 'mstuca.csv'],
        ['-180525620', 'mpsuru.csv'],
        ['-60900154', 'shnitke.csv'],
        ['-58035731', 'glasunov.csv'],
        ['-117974920', 'filaret.csv'],
        ['-193133254', 'rgiis.csv'],
        ['-194894715', 'surikov.csv'],
        ['-111837730', 'rpamu.csv']]

# создание датафрейма с идентификаторами сообществ и названием файлов с их публикациями
df = pd.DataFrame(data, columns=['group_id', 'source_nickname'])
df.to_csv('/Users/ekaterinamalkova/Desktop/vkr_analysis/data/unis_ids.csv', index=False)

In [41]:
data = pd.read_csv('/Users/ekaterinamalkova/Desktop/vkr_analysis/data/data_unis.csv')
data.head()

,post_id,date,text,likes,comments_count,reposts,views,source_nickname
0,77031,2025-12-31,🎄 Не хотим отвлекать вас от салатно-гирляндных...,42,0,5,4951,hse.csv
1,77030,2025-12-30,🎄 Чем запомнился уходящий год для Вышки?\n\nРа...,44,0,2,6790,hse.csv
2,77028,2025-12-30,🌳 Зеленая трансформация: от мифов к реалиям \n...,20,0,3,3091,hse.csv
3,77026,2025-12-30,"📖 «Тревожность», «зумер», «выгорание» — слова ...",42,0,9,14242,hse.csv
4,77022,2025-12-29,"🔍 Сценарные прогнозы, ИИ-агенты, технологии 6G...",22,0,1,3841,hse.csv

In [42]:
# добавление колонки с идентификатором сообщества
data = data.merge(df[['source_nickname', 'group_id']], on='source_nickname', how='left')

# функция для конструирования колонки, содержащей ссылку на конкретную публикацию
def construct_post_link(row):
  group_id = row['group_id'].split('-')[1]
  post_id = row['post_id']
  return f'https://vk.com/club{group_id}?w=wall-{group_id}_{post_id}'

# добавление колонки со ссылкой на публикацию сообщества
data['post_link'] = data.apply(construct_post_link, axis=1)

data.head()

,post_id,date,text,likes,comments_count,reposts,views,source_nickname,group_id,post_link
0,77031,2025-12-31,🎄 Не хотим отвлекать вас от салатно-гирляндных...,42,0,5,4951,hse.csv,-25205856,https://vk.com/club25205856?w=wall-25205856_77031
1,77030,2025-12-30,🎄 Чем запомнился уходящий год для Вышки?\n\nРа...,44,0,2,6790,hse.csv,-25205856,https://vk.com/club25205856?w=wall-25205856_77030
2,77028,2025-12-30,🌳 Зеленая трансформация: от мифов к реалиям \n...,20,0,3,3091,hse.csv,-25205856,https://vk.com/club25205856?w=wall-25205856_77028
3,77026,2025-12-30,"📖 «Тревожность», «зумер», «выгорание» — слова ...",42,0,9,14242,hse.csv,-25205856,https://vk.com/club25205856?w=wall-25205856_77026
4,77022,2025-12-29,"🔍 Сценарные прогнозы, ИИ-агенты, технологии 6G...",22,0,1,3841,hse.csv,-25205856,https://vk.com/club25205856?w=wall-25205856_77022

### Написание функции по извлечению данных комментариев с помощью VK API

In [1]:
# импорт библиотек
import vk_api
from datetime import datetime
import time
import pandas as pd

# инициализация функции для извлечения комментариев
def get_comments_from_posts(api_token, post_link):
    '''
    Получает тексты комментариев из публикаций сообществ с сайта https://vk.com.

    Параметры:
        api_token: ключ доступа для выполнения запросов к VK API
        post_link: полная ссылка на публикацию
    Вывод функции:
        Возвращает str – тексты всех комментариев к публикации, через разделитель '|'; '0' – если комментарии отсутсвуют
    '''
  # инициализация VK API
    vk_session = vk_api.VkApi(token=api_token)
    vk = vk_session.get_api()

    wall_ = post_link.split('wall')[1]
    owner_id, post_id = wall_.split('_')
    owner_id = int(owner_id)
    post_id = int(post_id)

    # инициализируем вспомогательные элементы
    all_comments = []
    offset = 0
    count = 100

    # пока все комментарии не собраны, выполняется цикл
    while True:
        # отправка запроса для получения кромментариев
        comments_response = vk.wall.getComments(owner_id=owner_id,
                                               post_id=post_id,
                                               count=count,
                                               offset=offset,
                                               need_likes=0,
                                               extended=0)
        
        if comments_response.get('items'):
            for comment in comments_response['items']:
                comment_text = comment.get('text', '')
                if comment_text and comment_text.strip():
                    all_comments.append(comment_text.strip())


            if len(comments_response['items']) < count:
                break
                
        offset += count
        # задержка алгоритма для избежания превышения установленных лимитов запросов (rps)
        time.sleep(0.05)
    # объединение комментариев в ячейку
    if all_comments:
        text = ' | '.join(all_comments)
        return text
    else:
        return '0'

/Users/ekaterinamalkova/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [9]:
from tqdm import tqdm
tqdm.pandas()

# на данном этапе приводится выполнение 2 параллели с новым api_token для ускорения работы
data_with_comments = data[data['comments_count'] > 0]

data_with_comments_3 = data_with_comments[50000:]

In [ ]:
# после пробного применения данного кода стало ясно, что необходимо производить оптимизацию, поскольку
# 1) загрузка происходила очень долго и 2) многократное появление сообщений о превышении числа rps

# comments = []
# for link in tqdm(data_with_comments['post_link']):
#     comments.append(get_comments_from_posts(api_token, link))
#     time.sleep(0.1)
# data_with_comments['comments_text'] = comments

In [ ]:
# сохранение постов с уже прогруженными комментариями для продолжения работы
processed_df = data_with_comments.iloc[:len(comments)].copy()
processed_df['comments_text'] = comments
processed_df.to_csv('processed_posts.csv', index=False)

In [ ]:
# оптимизация выгрузки заключается в следующем:
# 1) изменения для более корректного получения owner_id и post_id
# 2) использование потока для фоновой работы над данными. в случае зависания на 80 секунд, 
    # поток прекращает работу и переходит к следующей строке с данными

In [3]:
import pandas as pd
from tqdm import tqdm
import re
import time
import threading
import warnings
import vk_api


# инициализация функции для корреткного получения owner_id и post_id с обработкой возможной ошибки
def parse_wall_links(post_link):
    '''
    Извлекает идентификаторы сообщества и публикации из ссылки. 
    
    Параметры:
        post_link: полная ссылка на публикацию
    Вывод функции:
        Возвращает int – идентификаторы сообщества и публикации
    '''
    match = re.search(r'wall(-?\d+)_(\d+)', str(post_link))

    if not match:
        raise ValueError('Ссылка не распарсилась')
    owner_id = int(match.group(1))
    post_id = int(match.group(2))

    return owner_id, post_id



# инициализация функции для извлечения комментариев
def get_comments_from_posts(api_token, post_link):
    '''
    Получает тексты комментариев из публикаций сообществ с сайта https://vk.com.

    Параметры:
        api_token: ключ доступа для выполнения запросов к VK API
        post_link: полная ссылка на публикацию
    Вывод функции:
        Возвращает str – тексты всех комментариев к публикации, через разделитель '|'; '0' – если комментарии отсутсвуют
    '''
    try:
        # инициализация VK API
        vk_session = vk_api.VkApi(token=api_token)
        vk = vk_session.get_api()
    
        owner_id, post_id = parse_wall_links(post_link)
        
        # инициализируем вспомогательные элементы
        all_comments = []
        offset = 0
        count = 100
        
        # пока все комментарии не собраны, выполняется цикл
        while True:
            # отправка запроса для получения кромментариев
            comments_response = vk.wall.getComments(owner_id=owner_id,
                                                   post_id=post_id,
                                                   count=count,
                                                   offset=offset,
                                                   need_likes=0,
                                                   extended=0)
            
            if comments_response.get('items'):
                for comment in comments_response['items']:
                    comment_text = comment.get('text', '')
                    if comment_text and comment_text.strip():
                        all_comments.append(comment_text.strip())
    
    
                if len(comments_response['items']) < count:
                    break
            else:
                break
            offset += count
            # задержка алгоритма для избежания превышения установленных лимитов запросов (rps)
            time.sleep(0.45)
        # объединение комментариев в ячейку
        if all_comments:
            text = ' | '.join(all_comments)
            return text
        else:
            return '0'
    
    except Exception:
        return 'нужна проверка'

# инициализация функции защищенного вызова с таймаутом
def get_comments_thread(api_token, post_link, timeout=80):
    result = {'value': 'нужна проверка'}

    # вызывает get_comments_from_posts, если успешно, записывает результат, иначе помечает как 'нужна проверка'
    def target():
        try: 
            result['value'] = get_comments_from_posts(api_token, post_link)
        except Exception:
            result['value'] = 'нужна проверка'

    # инициализация и запуск потока
    thread = threading.Thread(target=target)
    thread.daemon = True
    thread.start()
    thread.join(timeout)

    if thread.is_alive():
        return 'нужна проверка'
    if result['value']:
        return result['value']

    else:
        return 'нужна проверка'

/Users/ekaterinamalkova/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

### Применение функции для выгрузки комментариев из публикаций

Данные были разделены на две части: первые 50тыс строк и оставшиеся 61тыс строк
Это было осуществлено для ускорения выгрузки данных с использованием самостоятельных процессов в отдельных ноутбуках с отдельными ключами.

Первая часть данных:

In [ ]:
warnings.filterwarnings('ignore')

# названия файлов, куда будут сохраняться промежуточные и финальные результаты
progress_file = 'progress.csv'
final_file = 'final_result.csv'

# таймаут в секундах
timeout = 80
# число постов, через которое осуществляется сохранение прогресса
save_loop = 100

# первая часть данных, начиная с 0 и до 50000 строки
data_with_comments_1 = data_with_comments.head(50000).reset_index(drop=True)

progress_df = pd.read_csv(progress_file)
done = len(progress_df)
comments = progress_df['comments'].fillna('нужна проверка').tolist()

# цикл, в котором применяются функции для извлечения комментариев с обработкой ошибок и использованием таймаута в потоке
for i, post_link in enumerate(tqdm(data_with_comments_1['post_link'].iloc[done:],
                                  desc='Cбор комментариев', initial=done,
                                  total=len(data_with_comments_1))):
    current_index = done +i

    comment = get_comments_thread(api_token=api_token, post_link=post_link, timeout=timeout)
    comments.append(comment)
    time.sleep(0.15)

    # сохранение прогресса каждые 100 постов
    if (current_index +1) % save_loop == 0:
        temp_df = data_with_comments_1.iloc[:current_index +1].copy()
        temp_df['comments'] = comments
        temp_df.to_csv(progress_file, index=False)


result_df = data_with_comments_1.iloc[:len(comments)].copy()
result_df['comments'] = comments

result_df.to_csv(progress_file, index=False)
result_df.to_csv(final_file, index=False)

print('Готово!')
print(f'Итоговый файл: {final_file}')

Вторая часть данных, которая обрабатывалась параллельно в другом ноутбуке-копии с новым ключем доступа:

In [14]:
warnings.filterwarnings('ignore')

# названия файлов, куда будут сохраняться промежуточные и финальные результаты
progress_file = 'progress_3.csv'
final_file = 'final_result_3.csv'

# таймаут в секундах
timeout = 80
# число постов, через которое осуществляется сохранение прогресса
save_loop = 100

# вторая часть данных, начиная с 50000 строки и до конца
data_with_comments_3 = data_with_comments.iloc[50000:].reset_index(drop=True)


progress_df = pd.read_csv(progress_file)
done = len(progress_df)
comments = progress_df['comments'].fillna('нужна проверка').tolist()

# цикл, в котором применяются функции для извлечения комментариев с обработкой ошибок и использованием таймаута в потоке
for i, post_link in enumerate(tqdm(data_with_comments_3['post_link'].iloc[done:],
                                  desc='Cбор комментариев', initial=done,
                                  total=len(data_with_comments_3))):
    current_index = done +i

    comment = get_comments_thread(api_token=api_token, post_link=post_link, timeout=timeout)
    comments.append(comment)
    time.sleep(0.15)

    # сохранение прогресса каждые 100 постов
    if (current_index +1) % save_loop == 0:
        temp_df = data_with_comments_3.iloc[:current_index +1].copy()
        temp_df['comments'] = comments
        temp_df.to_csv(progress_file, index=False)


result_df = data_with_comments_3.iloc[:len(comments)].copy()
result_df['comments'] = comments

result_df.to_csv(progress_file, index=False)
result_df.to_csv(final_file, index=False)

print('Готово!')
print(f'Итоговый файл: {final_file}')

Сбор комментариев:  97%|███████████████▍| 59288/61387 [3:32:43<11:40,  3.00it/s]Too many requests! Sleeping 0.5 sec...
Сбор комментариев: 100%|████████████████| 61387/61387 [3:45:42<00:00,  2.41it/s]

Готово!
Итоговый файл: final_result_3.csv

### Объединение комментариев и дополнительная обработка ошибок

In [149]:
# чтение и объединение двух частей данных
da1 = pd.read_csv("final_result.csv")
da2 = pd.read_csv("final_result_3.csv")

data_with_comments = pd.concat([da1, da2], ignore_index=True)

In [23]:
data_with_comments.query('comments == "нужна проверка"').count().iloc[0]

np.int64(161)

In [15]:
data_with_comments.query('comments == "нужна проверка"').source_nickname.value_counts()

source_nickname
misis.csv         45
mirea.csv         30
rosbiotech.csv    25
ranepa.csv         7
mocsons.csv        7
timacad.csv        6
guu.csv            4
isi.csv            3
shcukina.csv       3
reu.csv            3
miigaik.csv        3
surikov.csv        2
gitis.csv          2
mslu.csv           2
pushkin.csv        1
mgpu.csv           1
rgiis.csv          1
vitte.csv          1
mositi.csv         1
imes.csv           1
gitr.csv           1
mgu.csv            1
madi.csv           1
rgsu.csv           1
mfti.csv           1
stankin.csv        1
polytech.csv       1
rguk.csv           1
miet.csv           1
gubkin.csv         1
rudn.csv           1
bmstu.csv          1
mgusit.csv         1
Name: count, dtype: int64

In [18]:
warnings.filterwarnings('ignore')

# названия файлов, куда будут сохраняться промежуточные и финальные результаты
progress_file = 'data_with_comments_clean_progress.csv'
final_file = 'data_with_comments_clean.csv'

# таймаут в секундах
timeout = 20
# число постов, через которое осуществляется сохранение прогресса
save_loop = 5

# выделение индексов проблемных строк 
errors = data_with_comments['comments'].eq('нужна проверка')
error_ind = data_with_comments.index[errors].tolist()
print(f'Повторная обработка {len(error_ind)} строк')

# цикл, в котором применяются функции для извлечения комментариев с обработкой ошибок и использованием таймаута в потоке
for i, index in enumerate(tqdm(error_ind, desc='Повторная обработка ошибок')):

    post_link = data_with_comments.at[index, 'post_link']
    comment = get_comments_thread(api_token=api_token, post_link=post_link, timeout=timeout)    
    data_with_comments.at[index, 'comments'] = comment
    time.sleep(0.15)

    # сохранение прогресса каждые 5 постов
    if (i + 1) % save_loop == 0:
        data_with_comments.to_csv(progress_file, index=False)

data_with_comments.to_csv(progress_file, index=False)
data_with_comments.to_csv(final_file, index=False)

print('Готово!')
print(f'Итоговый файл: {final_file}')
print(f'Осталось строк с ошибкой: {data_with_comments["comments"].eq("нужна проверка").sum()}')

Повторная обработка 161 строк

Повторная обработка ошибок:  10%|█▏          | 16/161 [02:53<1:07:59, 10.81s/it]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  12%|█▊            | 20/161 [03:00<06:19,  1.75s/it]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  19%|██▌           | 30/161 [03:06<01:24,  2.32it/s]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  20%|██▊           | 32/161 [03:08<01:12,  2.65it/s]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  32%|████▌         | 51/161 [03:19<00:51,  3.20it/s]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  46%|█████▉       | 74/161 [05:50<01:04,  2.02it/s]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  53%|███████      | 86/161 [05:57<00:33,  3.25it/s]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  56%|███████▏     | 90/161 [05:58<00:41,  2.60it/s]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  63%|████████▎    | 101/161 [06:06<00:25,  3.47it/s]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  65%|████████▍    | 104/161 [06:07<00:30,  2.80it/s]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  71%|█████████▏   | 114/161 [06:14<00:24,  2.95it/s]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  86%|███████████▏ | 138/161 [06:30<00:11,  2.94it/s]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  89%|███████████▌ | 143/161 [06:33<00:08,  3.11it/s]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок:  98%|████████████▊| 157/161 [06:43<00:01,  2.32it/s]Too many requests! Sleeping 0.5 sec...
Повторная обработка ошибок: 100%|█████████████| 161/161 [10:31<00:00,  2.62s/it]

Готово!
Осталось строк с ошибкой: 24
Итоговый файл: data_with_comments_clean.csv

In [24]:
data_with_comments.query('comments == "нужна проверка"').post_link

25384       https://vk.com/club40427933?w=wall-40427933_327
38165     https://vk.com/club145886776?w=wall-145886776_...
38257     https://vk.com/club145886776?w=wall-145886776_...
86659      https://vk.com/club138541024?w=wall-138541024_35
89058      https://vk.com/club44133092?w=wall-44133092_1984
89059      https://vk.com/club44133092?w=wall-44133092_1975
89068      https://vk.com/club44133092?w=wall-44133092_1964
93392           https://vk.com/club32851?w=wall-32851_26058
96341     https://vk.com/club26099662?w=wall-26099662_68083
96374       https://vk.com/club26099662?w=wall-26099662_146
96392       https://vk.com/club26099662?w=wall-26099662_125
97175          https://vk.com/club104797?w=wall-104797_3889
99101        https://vk.com/club71768146?w=wall-71768146_83
103471    https://vk.com/club193133254?w=wall-193133254_300
104375            https://vk.com/club3983?w=wall-3983_12719
106677    https://vk.com/club36100537?w=wall-36100537_14...
106685     https://vk.com/club36100537?w=wall-36100537_8819
106700    https://vk.com/club36100537?w=wall-36100537_14...
106709    https://vk.com/club36100537?w=wall-36100537_14...
106713    https://vk.com/club36100537?w=wall-36100537_13...
106726    https://vk.com/club36100537?w=wall-36100537_13...
106744    https://vk.com/club36100537?w=wall-36100537_13...
106942    https://vk.com/club214354323?w=wall-214354323_256
106945    https://vk.com/club214354323?w=wall-214354323_...
Name: post_link, dtype: object

Посты по ссылкам выше недосягаемы: они либо удалены, либо скрыты правообладателем. Удалим их из выборки

In [27]:
data_with_comments = data_with_comments.query('comments != "нужна проверка"')

In [25]:
data_with_comments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111387 entries, 0 to 111386
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   post_id          111387 non-null  int64
 1   date             111387 non-null  object
 2   text             111387 non-null  object
 3   likes            111387 non-null  int64
 4   comments_count   111387 non-null  int64
 5   reposts          111387 non-null  int64
 6   views            111387 non-null  int64
 7   source_nickname  111387 non-null  object
 8   group_id         111387 non-null  float64
 9   post_link        111387 non-null  object
 10  comments         111387 non-null  object
dtypes: float64(1), int64(5), object(5)
memory usage: 9.3+ MB

Также удалим посты, комментарии к которым не содержат текста и были помечены как "0"

In [30]:
data_with_comments = data_with_comments.query('comments != "0"')

In [29]:
data_with_comments.query('comments == "0"').count()

post_id            12083
date               12083
text               12083
likes              12083
comments_count     12083
reposts            12083
views              12083
source_nickname    12083
group_id           12083
post_link          12083
comments           12083
dtype: int64

In [61]:
data_with_comments.to_csv('/Users/ekaterinamalkova/Desktop/vkr_analysis/data/data_with_comments.csv')

## Набор данных

Датафрейм, содержащий комментарии к публикациям

In [78]:
data_with_comments = pd.read_csv('/Users/ekaterinamalkova/Desktop/vkr_analysis/data/data_with_comments.csv', index_col=0)
data_with_comments.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99280 entries, 0 to 99279
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   post_id          99280 non-null  int64
 1   date             99280 non-null  object
 2   text             99280 non-null  object
 3   likes            99280 non-null  int64
 4   comments_count   99280 non-null  int64
 5   reposts          99280 non-null  int64
 6   views            99280 non-null  int64
 7   source_nickname  99280 non-null  object
 8   group_id         99280 non-null  float64
 9   post_link        99280 non-null  object
 10  comments         99280 non-null  object
dtypes: float64(1), int64(5), object(5)
memory usage: 9.1+ MB

In [80]:
data_with_comments.head()

,post_id,date,text,likes,comments_count,reposts,views,source_nickname,group_id,post_link,comments
0,77019,2025-12-29,🤨 Понимают ли нейросети каламбуры?\n\nНе очень...,16,1,4,3546,hse.csv,-25205856.0,https://vk.com/club25205856?w=wall-25205856_77019,"ДА!Вы-лучшие!Докажите, что нашего брата этой к..."
1,76983,2025-12-23,"🏅 Наука, бизнес, благотворительность, спорт: в...",57,2,1,12237,hse.csv,-25205856.0,https://vk.com/club25205856?w=wall-25205856_76983,Amazing
2,76975,2025-12-22,"🤖 ИСКРА, АЛЕКС и МИРА — лучшие ИИ-наставники\n...",31,1,2,7496,hse.csv,-25205856.0,https://vk.com/club25205856?w=wall-25205856_76975,а кто у вас младший директор?
3,76962,2025-12-19,💬 Абхазский язык теперь доступен в «Яндекс Пер...,46,1,5,6359,hse.csv,-25205856.0,https://vk.com/club25205856?w=wall-25205856_76962,🤔
4,76950,2025-12-18,✍ Вышка в MAX: новые каналы и призы для подпис...,28,2,9,9664,hse.csv,-25205856.0,https://vk.com/club25205856?w=wall-25205856_76950,"здравствуйте, а когда вы будите писать задания..."

Датафрейм, содержащий все тексты публикаций

In [81]:
data_unis = pd.read_csv('/Users/ekaterinamalkova/Desktop/vkr_analysis/data/data_unis.csv', index_col=False)
data_unis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345006 entries, 0 to 345005
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   post_id          345006 non-null  int64
 1   date             345006 non-null  object
 2   text             345006 non-null  object
 3   likes            345006 non-null  int64
 4   comments_count   345006 non-null  int64
 5   reposts          345006 non-null  int64
 6   views            345006 non-null  int64
 7   source_nickname  345006 non-null  object
dtypes: int64(5), object(3)
memory usage: 21.1+ MB

In [82]:
data_unis.head()

,post_id,date,text,likes,comments_count,reposts,views,source_nickname
0,77031,2025-12-31,🎄 Не хотим отвлекать вас от салатно-гирляндных...,42,0,5,4951,hse.csv
1,77030,2025-12-30,🎄 Чем запомнился уходящий год для Вышки?\n\nРа...,44,0,2,6790,hse.csv
2,77028,2025-12-30,🌳 Зеленая трансформация: от мифов к реалиям \n...,20,0,3,3091,hse.csv
3,77026,2025-12-30,"📖 «Тревожность», «зумер», «выгорание» — слова ...",42,0,9,14242,hse.csv
4,77022,2025-12-29,"🔍 Сценарные прогнозы, ИИ-агенты, технологии 6G...",22,0,1,3841,hse.csv

Вспомогательный датафрейм, содержащий названия файлов csv с выгрузками из университетов и соответствующие им идентификаторы сообществ

In [83]:
unis_ids = pd.read_csv('/Users/ekaterinamalkova/Desktop/vkr_analysis/data/unis_ids.csv', index_col=False)
unis_ids.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   group_id         90 non-null     int64
 1   source_nickname  90 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.5+ KB

In [84]:
unis_ids.head()

   group_id source_nickname
0 -25205856         hse.csv
1 -50409684         mai.csv
2 -78019879         mgu.csv
3     -1177         reu.csv
4      -932        mfti.csv